### ISSUE TITLE
Remove the PVC leftovers after the statefulset scale down

### ISSUE THREAD

**Issue by perk-sumo** [SumoLogic/sumologic-kubernetes-collection#1000]
When the FluentD scales down it leaves the PVC leftovers which can lead to orphaned volumes.

Linked [JIRA issue SUMO-149781](https://jira.kumoroku.com/jira/browse/SUMO-149781)

**Comment by sumo-drosiek** [comment]
https://github.com/kubernetes/kubernetes/issues/55045

**Comment by perk-sumo** [comment]
It seems that PVC created by the statefulset autoremoval [is coming in k8s 1.22](https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/1847-autoremove-statefulset-pvcs)

**Comment by sumo-drosiek** [comment]
We are using PvC cleaner for this functionality
