### ISSUE TITLE
Expose priority class name for fluentd event pod

### ISSUE THREAD

**Issue by AshutoshNirkhe** [SumoLogic/sumologic-kubernetes-collection#1005]
I see you guys are now supporting **priorityClassName** for fluentd logs/metrics pods now as in,
https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/732

I would request to add that unless there was some particular reason **why fluentd event pod was excluded** ?

**Comment by sumo-drosiek** [comment]
@AshutoshNirkhe Thank you for issue :)

**Comment by perk-sumo** [comment]
Let's add this to both `master` and `release-v1.3`
