### ISSUE TITLE
Can't use maxUnavailable in PDB because chart is probably taking both default minAvailable and custom maxUnavailable values

### ISSUE THREAD

**Issue by AshutoshNirkhe** [SumoLogic/sumologic-kubernetes-collection#1007]
Hi,

I have set maxUnavailable under fluentd.logs and fluentd.metrics in my values.yaml file as below - 
    podDisruptionBudget:
      **maxUnavailable: 1**

But because the chart's default values.yaml already defines minAvailable: 2, chart deployment is failing giving the error that you can't specify both values -

`Error: rpc error: code = Unknown desc = release k8s-collection failed: PodDisruptionBudget.policy "k8s-collection-sumologic-fluentd-logs-pdb" is invalid: spec: Invalid value: policy.PodDisruptionBudgetSpec{MinAvailable:(*intstr.IntOrString)(0xc00b520f20), Selector:(*v1.LabelSelector)(0xc00b520f40), MaxUnavailable:(*intstr.IntOrString)(0xc00b520f00)}: minAvailable and maxUnavailable cannot be both set`

**Comment by sumo-drosiek** [comment]
@AshutoshNirkhe Thanks for issue, I would recommend to set `minAvailable` explicitly to `nil` until we figure out the proper solution

rel: https://github.com/helm/helm/pull/2648

**Comment by AshutoshNirkhe** [comment]
Hi @sumo-drosiek thanks for the workaround, but unfortunately that doesn't seem to work either :(

I am setting it this way -

```
      podDisruptionBudget:
          maxUnavailable: 1
          minAvailable: nil
```

Then I get this error -
```
Error: rpc error: code = Unknown desc = release k8s-collection failed: PodDisruptionBudget.policy "k8s-collection-sumologic-fluentd-metrics-pdb" is invalid: [spec: Invalid value: policy.PodDisruptionBudgetSpec{MinAvailable:(*intstr.IntOrString)(0xc00bafaa00), Selector:(*v1.LabelSelector)(0xc00bafaa20), MaxUnavailable:(*intstr.IntOrString)(0xc00bafa9e0)}: minAvailable and maxUnavailable cannot be both set, spec.minAvailable: Invalid value: intstr.IntOrString{Type:1, IntVal:0, StrVal:"nil"}: a valid percent string must be a numeric string followed by an ending '%' (e.g. '1%',  or '93%', regex used for validation is '[0-9]+%')]
```

**Comment by sumo-drosiek** [comment]
@AshutoshNirkhe Sorry, the correct value is `null` not `nil`.
It also stands in documentation: https://helm.sh/docs/chart_template_guide/values_files/#deleting-a-default-key

**Comment by AshutoshNirkhe** [comment]
Thanks @sumo-drosiek , yes null did work :)
