### ISSUE TITLE
Resources created by Terraform could be orphaned after uninstallation

### ISSUE THREAD

**Issue by beyondbill** [SumoLogic/sumologic-kubernetes-collection#1029]
It does not seems that `helm delete --purge sumologic` will remove the HTTP sources and Kubernetes secrets created by [Terraform](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/master/deploy/helm/sumologic/conf/setup/setup.sh) during the initial setup.

Is the expectation that a user should manually clean them up after uninstallation? It will be nice that can be taken care of automatically.

**Comment by pmalek-sumo** [comment]
Hi @beyondbill 

There's a PR that tries to address this via a `pre-delete` hook - https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1092.

This could be enabled via `--set sumologic.cleanUpEnabled=true`.

Feel free to comment if that's something that would help.

**Comment by beyondbill** [comment]
@pmalek-sumo Awesome! The PR looks great! I love using `pre-delete` hook as a solution! Looking forward to the release!

**Comment by pmalek-sumo** [comment]
@beyondbill The PR is merged. It also removes `sumologic` secret.

It will be available in `v2.0` release. I'm closing this for now. Please comment in case you believe there's something more we can do in this subject.
