### ISSUE TITLE
Metrics PodDisruptionBudget not optional

### ISSUE THREAD

**Issue by dlaidlaw** [SumoLogic/sumologic-kubernetes-collection#1044]
The metrics PodDisruptionBudget will always be deployed, even if metrics are disabled.

The first line of the metrics-pdb.yaml file in the helm chart is `{{- if .Values.fluentd.metrics.podDisruptionBudget -}}`

That will always evaluate to true because that configuration is defined in the values.yaml and therefore cannot be removed. It would be better to use `{{- if and (eq .Values.sumologic.metrics.enabled true) (eq .Values.fluentd.metrics.enabled true) }}` because that is the same condition used to conditionally create the metrics StatefulSet. See line 1 of the metrics-statefulset.yaml file.

**Comment by pmalek-sumo** [comment]
Thanks @dlaidlaw for bringing this up. It should be fixed with https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1047
