### ISSUE TITLE
Does /tail-db persist on host filesystem?

### ISSUE THREAD

**Issue by beyondbill** [SumoLogic/sumologic-kubernetes-collection#1045]
Fluentd-bit tail input uses a DB file to keep track of log positions. All these DB files are saved under `/tail-db` folder on container filesystem. For example,
https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/05b6cc55a8be71fc925763ada89bf672a68dd048/deploy/helm/sumologic/values.yaml#L796

However I could not find anywhere in this code base that `/tail-db` is mounted to the host filesystem. I believe it should be persisted on the host otherwise it's meaningless in case the fluentd-bit container died.

**Comment by frankreno** [comment]
@beyondbill - yes.  This property ensures that the DB files are on the host: https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/05b6cc55a8be71fc925763ada89bf672a68dd048/deploy/helm/sumologic/values.yaml#L761

**Comment by beyondbill** [comment]
@frankreno Ah I missed this. Only searched for mounted volumes in this code base but forgot it might be in fluent-bit's code. Thank you!
