### ISSUE TITLE
Change in "fluentd.logs.containers.*" does not roll fluentd pods

### ISSUE THREAD

**Issue by beyondbill** [SumoLogic/sumologic-kubernetes-collection#1046]
### Versions
Chart:           v1.3.1
Helm:            v3.3.0
Kubernetes: v1.18.2

### Reproduction
On an existing installation, run
```
helm upgrade --namespace sumologic --set fluentd.logs.containers.xxx=yyy  sumologic sumologic/sumologic
```
where `xxx` and `yyy` are any valid values and `yyy` is different than the previous value of `fluentd.logs.containers.xxx`

### Expectation
Statefulset `sumologic-sumologic-fluentd-logs` should roll all its pods to take the new setting `fluentd.logs.containers.xxx=yyy` into effect.

### Actual result
Pods in statefulset `sumologic-sumologic-fluentd-logs` remain unchanged. The new setting `fluentd.logs.containers.xxx=yyy` won't take into effect.

### Analysis
Helm takes the new setting `fluentd.logs.containers.xxx=yyy` and update the key-value pair in configMap `sumologic-sumologic-fluentd-logs`. Although statefulset `sumologic-sumologic-fluentd-logs` has a reference to configMap `sumologic-sumologic-fluentd-logs`, the contents of the statefulset template does not change. Therefore the statefulset sees no change and does not roll its pods.

I have not yet come up with any fix for this. Will update the issue when I have any idea.

**Comment by beyondbill** [comment]
@perk-sumo @sumo-drosiek Thanks for the quick response! The checksum annotation solution is brilliant! Looking forward to the release!

**Comment by sumo-drosiek** [comment]
No problem 🚀 

The idea comes from official helm documentation 📖 
https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
