### ISSUE TITLE
Missing kubelet metrics troubleshooting step doesn't work on AKS.

### ISSUE THREAD

**Issue by arunpatyal** [SumoLogic/sumologic-kubernetes-collection#115]
Missing kubelet metrics troubleshooting step doesn't work on AKS, kops doesn't support AKS yet.
I used below commands for AKS and it worked:

kubectl -n sumologic get servicemonitor prometheus-operator-kubelet -o yaml | sed 's/https/http/' >> prometheus-operator-kubelet.yaml
kubectl apply -f prometheus-operator-kubelet.yaml

I think these should be added to the readme for AKS

**Comment by rvmiller89** [comment]
@arunpatyal  does the second suggestion of `2. Disable the kubelet.serviceMonitor.https flag in the Prometheus operator` work for you on AKS?

**Comment by arunpatyal** [comment]
@rvmiller89 Didn't try that. @ankitgoelcmu Could you please check it when you get some time?

**Comment by rvmiller89** [comment]
Going to close for now, please re-open if the 2nd work-around doesn't work on AKS.
