### ISSUE TITLE
[Metrics] Check the Prometheus UI Troubleshooting step needs sumologic namespace

### ISSUE THREAD

**Issue by arunpatyal** [SumoLogic/sumologic-kubernetes-collection#116]
3. [Metrics] Check the Prometheus UI Troubleshooting step needs sumologic namespace as we are installing prometheus in sumologic namespace:

kubectl port-forward prometheus-prometheus-operator-prometheus-0 8080:9090

should be changed to: 

kubectl port-forward prometheus-prometheus-operator-prometheus-0 8080:9090 **-n sumologic**

**Comment by rvmiller89** [comment]
Hi @arunpatyal , we've added a note that the troubleshooting commands assume setting a context with the `--namespace=sumologic` here: https://github.com/SumoLogic/sumologic-kubernetes-collection/tree/master/deploy#namespace-configuration
