### ISSUE TITLE
Backport #1175 to the v1.3 - copying images into ECR Public

### ISSUE THREAD

**Issue by perk-sumo** [SumoLogic/sumologic-kubernetes-collection#1176]
It's a #1175 backport.

**Comment by pmalek-sumo** [comment]
As of now we're copying images to GH registry

https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/c255a2423a31d50ed3ec800f857e65571857e270/ci%2F_build_functions.sh#L73-L80

In case we want to cover pushing images to public ECR public.ecr.aws/sumologic/ we could change this issue's title or create a new one for this occasion.

Thoughts? @perk-sumo

**Comment by perk-sumo** [comment]
@pmalek-sumo good point - I've renamed it :)
