### ISSUE TITLE
Missing proper documentation for helm chart variables

### ISSUE THREAD

**Issue by daroga0002** [SumoLogic/sumologic-kubernetes-collection#1179]
This helm chart is very complex, each time when I want to change in my deployment  I need to reverse engineer helm templates and default values files. I suggest to add here standarized helm chart docs page for all values used in chart.

Example of such table:
![image](https://user-images.githubusercontent.com/20227477/100285226-cef5f400-2f70-11eb-97b9-75471890868c.png)

example link:
https://github.com/bitnami/charts/tree/master/bitnami/apache

This will allow users to customize them easily their deployments.

Automation of such docs can be handled for example using https://github.com/kubepack/chart-doc-gen or [frigate](https://medium.com/rapids-ai/introducing-frigate-a-documentation-generation-tool-for-kubernetes-1791854031a1)

**Comment by sumo-drosiek** [comment]
@daroga0002 Thank you for the issue.

We already have the config parameters table. It's placed in chart directory ([deploy/helm/sumologic](https://github.com/SumoLogic/sumologic-kubernetes-collection/tree/main/deploy/helm/sumologic#configuration)).

**Comment by daroga0002** [comment]
Where exactly it is as I am unable to find it, so maybe I am looking wrong 🙁

**Comment by sumo-drosiek** [comment]
Here is full link -> https://github.com/SumoLogic/sumologic-kubernetes-collection/tree/main/deploy/helm/sumologic/README.md

**Comment by daroga0002** [comment]
@sumo-drosiek 
Thx I dont know how I missed this 🤦  it is exactly what I was looking
