### ISSUE TITLE
Support multiple container registries

### ISSUE THREAD

**Issue by sumo-drosiek** [SumoLogic/sumologic-kubernetes-collection#1220]
**Is your feature request related to a problem? Please describe.**
When registry is unavailable (down or some limits), customer cannot get image from it.

**Describe the solution you'd like**
Send images to multiple registries to avoid single point of failure

**Describe alternatives you've considered**
n/a

**Additional context**
https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1217#discussion_r535976987

**Comment by pmalek-sumo** [comment]
As of now we're not building images in this repo anymore (and we're using images hosted at AWS public ECR), hence no change is required in here.
