### ISSUE TITLE
Getting the following Error: DaemonSet.apps "release-v1-fluent-bit" is invalid: [spec.template.spec.volumes[5].name: Duplicate value: "tail-db", spec.template.spec.containers[0].volumeMounts[10].mountPath: Invalid value: "/tail-db": must be unique]

### ISSUE THREAD

**Issue by ESBA-salman** [SumoLogic/sumologic-kubernetes-collection#1227]
Our install is failing with the error 

We are trying to install with metrics disabled flag.

Error: DaemonSet.apps "release-v1-fluent-bit" is invalid: [spec.template.spec.volumes[5].name: Duplicate value: "tail-db", spec.template.spec.containers[0].volumeMounts[10].mountPath: Invalid value: "/tail-db": must be unique]

**Comment by sumo-drosiek** [comment]
Hi @ESBA-salman,

Could you give us some additional information?

Additionally, please check if `fluent-bit.extraVolumes` and `fluent-bit.extraVolumeMounts` don't contain duplicated values.

---

**Command used to install/upgrade Collection**
Direct command which you used to install/upgrade collection.

**Configuration**
Configuration used for Collection e.g. values.yaml for helm.

**To Reproduce**
Steps to reproduce the behavior.

**Environment (please complete the following information):**
 - **Collection version** (e.g. `helm ls -n sumologic`):
 - **Kubernetes version** (e.g. `kubectl version`):
 - **Cloud provider**:
 - **Others**:

**Comment by ESBA-salman** [comment]
Hi,

There were duplicate values in  fluent-bit.extraVolumes and fluent-bit.extraVolumeMounts in the default values.yaml. I got around by modifying one. 

Thanks
