### ISSUE TITLE
Update docs about installing collection with existing Prometheus Operator

### ISSUE THREAD

**Issue by astencel-sumo** [SumoLogic/sumologic-kubernetes-collection#1313]
**Describe the bug**
There are currently three separate docs describing installing the chart into a cluster with an existing Prometheus instance:

- https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/docs/side-by-side-prometheus.md
- https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/docs/existing-prometheus-doc.md
- https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/docs/standalone-prometheus.md

These docs need to be removed in favor of a single doc describing installing into a cluster with existing Prometheus Operator.

We should not support modifying an existing Prometheus instance; the Sumo collection should always create its own Prometheus instance.

**Comment by sumo-drosiek** [comment]
Done by #2784 #2793
