### ISSUE TITLE
K8s secret created via terraform

### ISSUE THREAD

**Issue by msuterski** [SumoLogic/sumologic-kubernetes-collection#1370]
We've been trying to deploy the agent via the Helm chart and provide _only_ the collector's endpoint (skipping the access keys). Our current process for how we manage Sumologic collectors themselves lives in a separate place and we would prefer not to require the access keys to be bundled into the agent's deployment. We've been running the chart with the `setupEnabled=false` option since we don't want new collectors to be created (in the `setup` job). We also have all the fields already created in our account.

It seems to me that providing only the endpoint to the chart should be sufficient for it to install all the required components. And the correct endpoint should be enough for the fluentd agent to ship logs to the existing collector.

Unfortunately, the secret that holds the value of the sumologic endpoint (which is referenced by the agent's pods) is not created via the chart, but is created in the terraform, which is executed only with the `setupEnabled=true` _and_ creates/defines a collector (which we don't want).

With the `setupEnabled=false`, the chart is essentially deploying a broken deployment because it's not creating the kubernetes secret in the cluster.

Is there a reason why the secret is managed via Terraform and not managed with the chart? 

Thanks,
Marcin

**Comment by sumo-drosiek** [comment]
Hi @msuterski,

Sumologic Kubernetes Collection is part of the whole solution and it's intended that we are managing collector from cluster (so terraform) to avoid additional interaction from customer side. If you want to skip providing `accessId`/`accessKey` you need to create secret with endpoints on your own, as we don't support such scenario right now.

Some clarifications:
 - `sumologic.endpoint` is address of Sumo Logic API, and not a collector endpoint.
 - `sumologic.setupEnabled` is working correctly in case of upgrades, or if you mange you secret on your own.
 
 Is this ok? Do you need help with the secret?

**Comment by msuterski** [comment]
This is great info. Thanks a lot @sumo-drosiek! My mistake of not understanding how it should work.

I wish the chart was providing a way to use an existing collector/endpoint. We manage them through our own automation where roles are assigned access to them automatically on creation. With the chart solution we'll need to define a process to grant access to the data from k8s collectors.
