### ISSUE TITLE
Add way to add custom gems without having to maintain docker image.

### ISSUE THREAD

**Issue by frankreno** [SumoLogic/sumologic-kubernetes-collection#139]
One possible way to do this is via an `init` container.  The user could provide a list of additional gems, the init container would come up and do a gem`gem install` on those.

**Comment by adaughterson** [comment]
+1
We would like the ability to gracefully have additional fluentd plugins installed without having to fork the standard sumo fluentd image (what we are currently doing).

**Comment by perk-sumo** [comment]
@frankreno did #542 solve the issue for you?
Can we close this one?

**Comment by frankreno** [comment]
This does indeed!
