### ISSUE TITLE
Update container registries documentation with ECR Public info

### ISSUE THREAD

**Issue by perk-sumo** [SumoLogic/sumologic-kubernetes-collection#1391]
https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/deploy/docs/Working_with_container_registries.md

We no longer use Docker Hub and switched to ECR Public.
Let's update documentation around that.

There should also be information on how ECR quota looks like and how does it work (eg. you need to authenticate yourself in order to get unlimited inside AWS).

Also it would be nice if we provided information on how to set those secrets to work.

**Comment by pmalek-sumo** [comment]
This believe this has been done as of https://github.com/SumoLogic/sumologic-kubernetes-collection/commit/3361a47eeb03175983a84a803dd39e71106684c8
