### ISSUE TITLE
Use upstream Kubeclient 5 when it is available

### ISSUE THREAD

**Issue by astencel-sumo** [SumoLogic/sumologic-kubernetes-collection#1392]
After this PR https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1390 is merged into `v1` release branch, we will be using an unreleased Kubeclient gem version from GitHub.

This issue exists to remind us to go back to using upstream Kubeclient after the changes we need are released (most likely in version `5.0` of the gem).

**Comment by astencel-sumo** [comment]
This issue is blocked until Kubeclient releases v5.0 https://github.com/astencel-sumo/kubeclient/releases.

**Comment by perk-sumo** [comment]
Original releases: https://github.com/abonas/kubeclient/releases
