### ISSUE TITLE
v2 upgrade script: remoteTimeout is not added to custom remoteWrite section

### ISSUE THREAD

**Issue by astencel-sumo** [SumoLogic/sumologic-kubernetes-collection#1412]
**Describe the bug**

When upgrading from `v1` to `v2`, if you have your Prometheus `remoteWrite` section overridden (that is entry `prometheus-operator.prometheus.prometheusSpec.remoteWrite` in `values.yaml`), the upgrade script does not add `remoteTimeout` parameter to the Fluentd `remoteWrite` entries. We consider this to be a bug, as the `remoteTimeout` parameter is crucial to ensure good performance when sending data from Prometheus to Fluentd.

**To Reproduce**

1. Prepare a `values.yaml` file for `v1` collection that has `prometheus-operator.prometheus.prometheusSpec.remoteWrite` entry customized.
2. Run the upgrade script [upgrade-2.0.0.sh](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/ee6257fce3a5a7f4ff5614fdc12b481f6ef57cc2/deploy/helm/sumologic/upgrade-2.0.0.sh)

```shell
./upgrade-2.0.0.sh values.yaml
```

3. Observe the `prometheus-operator.prometheus.prometheusSpec.remoteWrite` in the output file `new_values.yaml`.

**Expected behavior**

The `prometheus-operator.prometheus.prometheusSpec.remoteWrite` section in the output file should contain `remoteTimeout` parameter for the Fluentd `remoteWrite` entries.

**Actual behaviour**

The `prometheus-operator.prometheus.prometheusSpec.remoteWrite` section in the output file does not contain `remoteTimeout` parameter for the Fluentd `remoteWrite` entries.

**Comment by perk-sumo** [comment]
Backport to `v2.0`: https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1475
