### ISSUE TITLE
CRIO looses logtag 

### ISSUE THREAD

**Issue by frankreno** [SumoLogic/sumologic-kubernetes-collection#1418]
https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/10101015924ebe6c92bcf9ce9a757d5da82ba302/deploy/helm/sumologic/conf/logs/logs.source.containers.conf#L7-L17

CRIO parser parses out the logtag. Due to above block it does not appear in Sumo Logic. 

Ideally we should automatically update this if CRIo parser is used. However in the event of additional data we probably need an override for this block so it can be customized.

**Comment by kkujawa-sumo** [comment]
It seems to be related to https://github.com/fluent/fluent-bit/issues/1316 and also mentioned under https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/758#issuecomment-684135623

**Comment by sumo-drosiek** [comment]
As logtag is used to detect multiline log, we should concatenate them. We can push it until upstream issue is resolved, but logtag doesn't seems to be very useful on sumo side

**Comment by kkujawa-sumo** [comment]
When `multiline` is disabled log is visible in following form:
```
{
   "timestamp":1613653807337,
   "stream":"stdout",
   "logtag":"F",
   "log":"this is a log message"
}
```

or with removed lines in parser configuration (then `time` key is not used as a timestamp)
```
          Time_Key     time
          Time_Format  %Y-%m-%dT%H:%M:%S.%LZ
```
has this form:
```
{
   "timestamp":1613654044683,
   "time":"2021-02-18T13:14:04.683042846Z",
   "stream":"stdout",
   "logtag":"F",
   "log":"this is a log message"
}
```

**Comment by kkujawa-sumo** [comment]
Fixed by https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1441 multiline support for CRIO will be tracked in https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/1449
