### ISSUE TITLE
Can we run sumologic installation without giving it elevated privaleges?

### ISSUE THREAD

**Issue by vakkur** [SumoLogic/sumologic-kubernetes-collection#1424]
I do not want to run them as the root user, how do I approach it? When I specify it in the security context the pods fail to schedule.

```yaml
fluentd:
 persistence:
  enabled: true
 securityContext:
    ## The group ID of all processes in the statefulset containers. By default this needs to be fluent(999).
    fsGroup: 999
    runAsNonRoot: true
fluent-bit:
  image:
    fluent_bit:
      repository: public.ecr.aws/sumologic/fluent-bit
      tag: 1.6.0
  ## Resource limits for fluent-bit
  resources: 
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 8Mi
  securityContext:
    runAsNonRoot: true
```

**Comment by frankreno** [comment]
@vakkur please share errors you are seeing.  Which pods are failing to start? There are multiple pods so we need more details.

**Comment by vakkur** [comment]
![2021-02-13_12-12-09](https://user-images.githubusercontent.com/54898671/107861246-39009580-6e0a-11eb-9c54-90e799654d2e.jpg)

**Comment by pmalek-sumo** [comment]
Hi @vakkur,

I believe the issue stems from the fact that we use a non numeric user ID in our fluentd image:

https://github.com/SumoLogic/sumologic-kubernetes-fluentd/blob/ce2a685da5ea261bff9ca022e4c2719c31aa1334/Dockerfile#L109

I've prepared a patch to fix this issue https://github.com/SumoLogic/sumologic-kubernetes-fluentd/pull/118

You can try building the image yourself using the steps from `Makefile` at https://github.com/SumoLogic/sumologic-kubernetes-fluentd/blob/main/Makefile#L7-L21 or wait until the PR gets merged. We'll most probably need to backport this to 2.0  and 1.3 releases as well.

Thanks for bringing this up 👍🏻

**Comment by vakkur** [comment]
@pmalek-sumo thank you for your response.

The fluent bit pod also errors out when trying to run as non-root users and how do you specify the container level security context settings such as read-only root file systems? 

We are running policy agent that would check the k8s best practices, the sumologic pods threw a lot of voilations here is an report of all the voilations, I am not sure if all of them would be addressed by this PR you mentioned ,


--
  Message:        validation error: Root filesystem must be read-only. Rule autogen-validate-readOnlyRootFilesystem failed at path /spec/template/spec/containers/0/securityContext/readOnlyRootFilesystem/
  Policy:         require-ro-rootfs
  Resources:
    API Version:  apps/v1
    Kind:         DaemonSet
    Name:         av2-fluent-bit
    Namespace:    sumologic
    UID:          c4c20924-33e3-48f8-8973-b5e629ddf6a0
  Rule:           autogen-validate-readOnlyRootFilesystem
  Scored:         true
  Status:         fail
--
  Message:        validation error: Root filesystem must be read-only. Rule autogen-validate-readOnlyRootFilesystem failed at path /spec/template/spec/containers/0/securityContext/
  Policy:         require-ro-rootfs
  Resources:
    API Version:  apps/v1
    Kind:         StatefulSet
    Name:         av2-sumologic-fluentd-events
    Namespace:    sumologic
    UID:          5bb45ab8-795e-47c1-8052-b3b180eb5e75
  Rule:           autogen-validate-readOnlyRootFilesystem
  Scored:         true
  Status:         fail
--
  Message:        validation error: Running as root is not allowed. The fields spec.securityContext.runAsNonRoot, spec.containers[*].securityContext.runAsNonRoot, and spec.initContainers[*].securityContext.runAsNonRoot must be `true`. Rule autogen-check-containers[0] failed at path /spec/template/spec/securityContext/runAsNonRoot/. Rule autogen-check-containers[1] failed at path /spec/template/spec/containers/0/securityContext/.
  Policy:         require-run-as-non-root
  Resources:
    API Version:  apps/v1
    Kind:         StatefulSet
    Name:         av2-sumologic-fluentd-events
    Namespace:    sumologic
    UID:          5bb45ab8-795e-47c1-8052-b3b180eb5e75
  Rule:           autogen-check-containers
  Scored:         true
  Status:         fail
--
  Message:        validation error: Privileged mode is not allowed. Set allowPrivilegeEscalation to false. Rule autogen-validate-allowPrivilegeEscalation failed at path /spec/template/spec/containers/0/securityContext/allowPrivilegeEscalation/
  Policy:         disallow-privileged
  Resources:
    API Version:  apps/v1
    Kind:         DaemonSet
    Name:         av2-fluent-bit
    Namespace:    sumologic
    UID:          c4c20924-33e3-48f8-8973-b5e629ddf6a0
  Rule:           autogen-validate-allowPrivilegeEscalation
  Scored:         true
  Status:         fail
--
  Message:        validation error: Running as root is not allowed. The fields spec.securityContext.runAsNonRoot, spec.containers[*].securityContext.runAsNonRoot, and spec.initContainers[*].securityContext.runAsNonRoot must be `true`. Rule autogen-check-containers[0] failed at path /spec/template/spec/securityContext/runAsNonRoot/. Rule autogen-check-containers[1] failed at path /spec/template/spec/containers/0/securityContext/.
  Policy:         require-run-as-non-root
  Resources:
    API Version:  apps/v1
    Kind:         StatefulSet
    Name:         av2-sumologic-fluentd-logs
    Namespace:    sumologic
    UID:          43ae7c5a-be5c-483f-b774-d57713537f5f
  Rule:           autogen-check-containers
  Scored:         true
  Status:         fail
--
  Message:        validation error: Privileged mode is not allowed. Set allowPrivilegeEscalation to false. Rule autogen-validate-allowPrivilegeEscalation failed at path /spec/template/spec/containers/0/securityContext/
  Policy:         disallow-privileged
  Resources:
    API Version:  apps/v1
    Kind:         StatefulSet
    Name:         av2-sumologic-fluentd-logs
    Namespace:    sumologic
    UID:          43ae7c5a-be5c-483f-b774-d57713537f5f
  Rule:           autogen-validate-allowPrivilegeEscalation
  Scored:         true
  Status:         fail
--
  Message:        validation error: Changing of file system groups is not allowed. The field spec.securityContext.fsGroup must not be defined. Rule autogen-check-fsGroup failed at path /spec/template/spec/securityContext/fsGroup/
  Policy:         require-non-root-groups
  Resources:
    API Version:  apps/v1
    Kind:         StatefulSet
    Name:         av2-sumologic-fluentd-events
    Namespace:    sumologic
    UID:          5bb45ab8-795e-47c1-8052-b3b180eb5e75
  Rule:           autogen-check-fsGroup
  Scored:         true
  Status:         fail
--
  Message:        validation error: Unknown image registry. Rule autogen-validate-registries failed at path /spec/template/spec/containers/0/image/
  Policy:         restrict-image-registries
  Resources:
    API Version:  apps/v1
    Kind:         StatefulSet
    Name:         av2-sumologic-fluentd-logs
    Namespace:    sumologic
    UID:          43ae7c5a-be5c-483f-b774-d57713537f5f
  Rule:           autogen-validate-registries
  Scored:         true
  Status:         fail
--
  Message:        validation error: Unknown image registry. Rule autogen-validate-registries failed at path /spec/template/spec/containers/0/image/
  Policy:         restrict-image-registries
  Resources:
    API Version:  apps/v1
    Kind:         DaemonSet
    Name:         av2-fluent-bit
    Namespace:    sumologic
    UID:          c4c20924-33e3-48f8-8973-b5e629ddf6a0
  Rule:           autogen-validate-registries
  Scored:         true
  Status:         fail
--
  Message:        validation error: Running as root is not allowed. Set runAsNonRoot to true, or use runAsUser. Rule autogen-validate-runAsNonRoot[0] failed at path /spec/template/spec/securityContext/runAsNonRoot/. Rule autogen-validate-runAsNonRoot[1] failed at path /spec/template/spec/securityContext/runAsUser/. Rule autogen-validate-runAsNonRoot[2] failed at path /spec/template/spec/containers/0/securityContext/. Rule autogen-validate-runAsNonRoot[3] failed at path /spec/template/spec/containers/0/securityContext/.
  Policy:         disallow-root-user
  Resources:
    API Version:  apps/v1
    Kind:         StatefulSet
    Name:         av2-sumologic-fluentd-logs
    Namespace:    sumologic
    UID:          43ae7c5a-be5c-483f-b774-d57713537f5f
  Rule:           autogen-validate-runAsNonRoot
  Scored:         true
  Status:         fail
--
  Message:        validation error: Changing of file system groups is not allowed. The field spec.securityContext.fsGroup must not be defined. Rule autogen-check-fsGroup failed at path /spec/template/spec/securityContext/fsGroup/
  Policy:         require-non-root-groups
  Resources:
    API Version:  apps/v1
    Kind:         StatefulSet
    Name:         av2-sumologic-fluentd-logs
    Namespace:    sumologic
    UID:          43ae7c5a-be5c-483f-b774-d57713537f5f
  Rule:           autogen-check-fsGroup
  Scored:         true
  Status:         fail
--
  Message:        validation error: Running as root is not allowed. Set runAsNonRoot to true, or use runAsUser. Rule autogen-validate-runAsNonRoot[0] failed at path /spec/template/spec/securityContext/runAsNonRoot/. Rule autogen-validate-runAsNonRoot[1] failed at path /spec/template/spec/securityContext/runAsUser/. Rule autogen-validate-runAsNonRoot[2] failed at path /spec/template/spec/containers/0/securityContext/runAsNonRoot/. Rule autogen-validate-runAsNonRoot[3] failed at path /spec/template/spec/containers/0/securityContext/runAsUser/.
  Policy:         disallow-root-user
  Resources:
    API Version:  apps/v1
    Kind:         DaemonSet
    Name:         av2-fluent-bit
    Namespace:    sumologic
    UID:          c4c20924-33e3-48f8-8973-b5e629ddf6a0
  Rule:           autogen-validate-runAsNonRoot
  Scored:         true
  Status:         fail
--
  Message:        validation error: Privileged mode is not allowed. Set allowPrivilegeEscalation to false. Rule autogen-validate-allowPrivilegeEscalation failed at path /spec/template/spec/containers/0/securityContext/
  Policy:         disallow-privileged
  Resources:
    API Version:  apps/v1
    Kind:         StatefulSet
    Name:         av2-sumologic-fluentd-events
    Namespace:    sumologic
    UID:          5bb45ab8-795e-47c1-8052-b3b180eb5e75
  Rule:           autogen-validate-allowPrivilegeEscalation
  Scored:         true
  Status:         fail
--
  Message:        validation error: Unknown image registry. Rule autogen-validate-registries failed at path /spec/template/spec/containers/0/image/
  Policy:         restrict-image-registries
  Resources:
    API Version:  apps/v1
    Kind:         StatefulSet
    Name:         av2-sumologic-fluentd-events
    Namespace:    sumologic
    UID:          5bb45ab8-795e-47c1-8052-b3b180eb5e75
  Rule:           autogen-validate-registries
  Scored:         true
  Status:         fail

--
  Message:        validation error: Running as root is not allowed. Set runAsNonRoot to true, or use runAsUser. Rule autogen-validate-runAsNonRoot[0] failed at path /spec/template/spec/securityContext/runAsNonRoot/. Rule autogen-validate-runAsNonRoot[1] failed at path /spec/template/spec/securityContext/runAsUser/. Rule autogen-validate-runAsNonRoot[2] failed at path /spec/template/spec/containers/0/securityContext/. Rule autogen-validate-runAsNonRoot[3] failed at path /spec/template/spec/containers/0/securityContext/.
  Policy:         disallow-root-user
  Resources:
    API Version:  apps/v1
    Kind:         StatefulSet
    Name:         av2-sumologic-fluentd-events
    Namespace:    sumologic
    UID:          5bb45ab8-795e-47c1-8052-b3b180eb5e75
  Rule:           autogen-validate-runAsNonRoot
  Scored:         true
  Status:         fail
--
  Message:        validation error: Running as root is not allowed. The fields spec.securityContext.runAsNonRoot, spec.containers[*].securityContext.runAsNonRoot, and spec.initContainers[*].securityContext.runAsNonRoot must be `true`. Rule autogen-check-containers[0] failed at path /spec/template/spec/securityContext/runAsNonRoot/. Rule autogen-check-containers[1] failed at path /spec/template/spec/containers/0/securityContext/runAsNonRoot/.
  Policy:         require-run-as-non-root
  Resources:
    API Version:  apps/v1
    Kind:         DaemonSet
    Name:         av2-fluent-bit
    Namespace:    sumologic
    UID:          c4c20924-33e3-48f8-8973-b5e629ddf6a0
  Rule:           autogen-check-containers
  Scored:         true
  Status:         fail
--
  Message:        validation error: Root filesystem must be read-only. Rule autogen-validate-readOnlyRootFilesystem failed at path /spec/template/spec/containers/0/securityContext/
  Policy:         require-ro-rootfs
  Resources:
    API Version:  apps/v1
    Kind:         StatefulSet
    Name:         av2-sumologic-fluentd-logs
    Namespace:    sumologic
    UID:          43ae7c5a-be5c-483f-b774-d57713537f5f
  Rule:           autogen-validate-readOnlyRootFilesystem
  Scored:         true
  Status:         fail

**Comment by pmalek-sumo** [comment]
Hi @vakkur,

Change fixing the issue with `runAsNonRoot ` has been merged in https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1427.

If you want to use it before our next release you can bump fluentd image to `1.12.0-sumo-1-rc.1` as follows:

```yaml
fluentd:
  image:
    repository: public.ecr.aws/sumologic/kubernetes-fluentd
    tag: 1.12.0-sumo-1-rc.1
```

As for the other issues reported in your message: some of them will be fixed when https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/1034 is resolved (we're planning to work on it) and users will be able to specify security contexts for individual containers.

In case that doesn't resolve your issues please open a new (specific/concrete) issue with this repo and we'll take a look.
For now I'm closing this as the original problem should be solved.
