### ISSUE TITLE
setup.sh silently fails when -k and -c are ommitted, but a value is passed

### ISSUE THREAD

**Issue by frankreno** [SumoLogic/sumologic-kubernetes-collection#144]
Example, notice the flag is missing but the value is there.  The script silently fails when trying to create the collector:

`curl -s https://raw.githubusercontent.com/SumoLogic/sumologic-kubernetes-collection/master/deploy/kubernetes/setup.sh \
  | bash -s - someCollector  someCluster <api_endpoint> <access_id> <access_key>`

**Comment by abhi-sumo** [comment]
@frankreno Have you tested this with the most recent setup?
