### ISSUE TITLE
container_fs_usage_bytes metric missing when using containerd runtime

### ISSUE THREAD

**Issue by astencel-sumo** [SumoLogic/sumologic-kubernetes-collection#1456]
**Describe the bug**
When using Kubernetes with `containerd` as container runtime (e.g. AKS 1.19), the disk metrics are not available:
- `container_fs_usage_bytes`
- `container_fs_limit_bytes`

**Comment by astencel-sumo** [comment]
This issue seems to cover this problem: https://github.com/google/cadvisor/issues/2785.

**Comment by perk-sumo** [comment]
I'm not sure there is anything we can do about that.
