### ISSUE TITLE
Helm chart support for AWS EKS Fargate

### ISSUE THREAD

**Issue by obenziane2** [SumoLogic/sumologic-kubernetes-collection#1482]
**Fargate Daemon sets won't work with helm chart**
We have a combinations of EC2 and Fargate  PODS on EKS 1.18. It seems like fluend-bit daemon set is getting installed on EC2 instance , but as far as for Fargate Pods which does not support daemon sets. It's showing pending from the screenshot below

![image](https://user-images.githubusercontent.com/11947294/110222092-a2f9e100-7e84-11eb-860d-483f8444a858.png)

**Command used to install/upgrade Collection**
     helm upgrade --install sumologic sumologic/sumologic --namespace=dynamic --set kube-prometheus-stack.enabled=false --set kube-prometheus-stack.nodeExporter.enabled=false --set kube-prometheus-stack.kubeStateMetrics.enabled=false --set sumologic.accessId="xxxxxxxxxx" --set sumologic.accessKey="XXXXXXXXX" --set sumologic.clusterName="${eks_name}" --kube-context ${eks_context}

**To Reproduce**
A regular installation using he command above on EKS 1.18

**Environment :**

 - **Cloud provider**: EKS 1.18

**Comment by frankreno** [comment]
@obenziane2 - our collection method is currently not supported on Fargate, but something we are working on adding support in our next generation collection being developed.

**Comment by dlaidlaw** [comment]
Any news on the SumoLogic support for fargate? It has been almost a year.

**Comment by dlaidlaw** [comment]
@obenziane2 Any news on this "next generation collection"? Almost 2 years has passed since you mentioned that.

**Comment by sumo-drosiek** [comment]
It is supported starting with [3.6.0](https://github.com/SumoLogic/sumologic-kubernetes-collection/releases/tag/v3.6.0)

Documentation for the latest release is available [here](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/v4.3.1/docs/fargate.md)
