### ISSUE TITLE
Link all files in documentation so we don't break the paths while moving them

### ISSUE THREAD

**Issue by sumo-drosiek** [SumoLogic/sumologic-kubernetes-collection#1556]
Ideally we link all files so we don't break the paths while moving them

_Originally posted by @sumo-drosiek in https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/1555#issuecomment-819380068_

**Comment by pmalek-sumo** [comment]
I believe this is done after introducing the links checker. If not then what else would we like to check? Example?

**Comment by sumo-drosiek** [comment]
Aim of task is to link all file mentions in the documentation

**Comment by sumo-drosiek** [comment]
eg. https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/deploy/docs/Troubleshoot_Collection.md#fluentd-logs

`fluentd-sumologic.yaml` which is not linked so we didn't noticed it gone

**Comment by sumo-drosiek** [comment]
I searched in all `md` files for `.yaml` keyword and seems that everything has been linked already
