### ISSUE TITLE
Update sumologic.source for tracing

### ISSUE THREAD

**Issue by sumo-drosiek** [SumoLogic/sumologic-kubernetes-collection#1583]
This looks good to me. From the doc mentioned above by @pmatyjasek-sumo , the `sumologic.source*` properties haven't been available in the chart since v1.0.0. It's about time tracing configuration is updated. 😄

_Originally posted by @astencel-sumo in https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1582#discussion_r617471637_

**Comment by astencel-sumo** [comment]
This was fixed in https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1688 and https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1721.
