### ISSUE TITLE
Getting vulnerability error

### ISSUE THREAD

**Issue by jyu-tera** [SumoLogic/sumologic-kubernetes-collection#1614]
RDoc Gem for Ruby contains a flaw that is triggered as input to filenames is not properly sanitized before opening a file with kernel#open. With a specially crafted Ruby project containing a file with a filename that starts with '|' and ends with 'tags', a context-dependent attacker can inject and execute arbitrary commands. https://cve.mitre.org/cgi-bin/cvename.cgi?name=2021-31799

Discovered this with Sysdig Secure scanning software as a critical vulnerability

**Comment by pmalek-sumo** [comment]
Hello @jyu-tera 

Thanks for creating this issue!

Do you mind sharing a bit more details? Which version of rdoc gem is vulnerable?

**Comment by jyu-tera** [comment]
The rdoc gem version that is vulnerable is 6.1.2, and should be fixed in 6.3.1.

The bug should exist in this path according to our scan: /usr/local/lib/ruby/gems/2.6.0/specifications/default/rdoc-6.1.2.gemspec

**Comment by pmalek-sumo** [comment]
Thanks @jyu-tera https://github.com/SumoLogic/sumologic-kubernetes-fluentd/pull/227 should fix this problem
