### ISSUE TITLE
Fluentbit not running after upgrading to K8s 1.20

### ISSUE THREAD

**Issue by hussainsaify** [SumoLogic/sumologic-kubernetes-collection#1638]
Cluster- EKS 1.20
Sumologic chart - 2.1.1
Fluentbit version - 1.6.10

Hi Team,

After upgrading the k8s cluster to 1.20 , fluentbit failed to start as liveness/readiness probe is failing on port 2020

Below is pod events

```
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  15m                   default-scheduler  Successfully assigned sumologic/sumologic-collector-fluent-bit-lpzck to ip-10-3-91-0.ec2.internal
  Normal   Killing    14m (x2 over 15m)     kubelet            Container fluent-bit failed liveness probe, will be restarted
  Normal   Pulled     14m (x3 over 15m)     kubelet            Container image "public.ecr.aws/sumologic/fluent-bit:1.6.10" already present on machine
  Normal   Created    14m (x3 over 15m)     kubelet            Created container fluent-bit
  Normal   Started    14m (x3 over 15m)     kubelet            Started container fluent-bit
  Warning  Unhealthy  14m (x8 over 15m)     kubelet            Readiness probe failed: Get "http://10.3.90.226:2020/": dial tcp 10.3.90.226:2020: connect: connection refused
  Warning  BackOff    5m43s (x28 over 12m)  kubelet            Back-off restarting failed container
  Warning  Unhealthy  48s (x25 over 15m)    kubelet            Liveness probe failed: Get "http://10.3.90.226:2020/": dial tcp 10.3.90.226:2020: connect: connection refused
```

There is no error in logs and before the upgrade it was working fine. Please let me know in case more information is required.

Thanks,
Hussain

**Comment by pmalek-sumo** [comment]
Do you mind adding a full `kubectl describe` of fluentd logs stateful set as well as `values.yaml` that you've used to install the collection?

Do you use any particular customizations/security enhancements on the cluster itself that might be causing this?

**Comment by hussainsaify** [comment]
@pmalek-sumo Thanks for the response. Please find attach both the values.yaml and fluend logs statefulset file
[sumologic-fluentd.txt](https://github.com/SumoLogic/sumologic-kubernetes-collection/files/6613531/sumologic-fluentd.txt)

[sumologic-values.txt](https://github.com/SumoLogic/sumologic-kubernetes-collection/files/6613536/sumologic-values.txt)

We have not done any modifications other than upgrading k8s to 1.20. Please let me know in case you need more information.

Thanks,
Hussain

**Comment by pmalek-sumo** [comment]
@hussainsaify thanks for those, do you mind also attaching output for `kubectl describe` of one of those failing fluent-bits? BTW are all of them failing or just a subset?

I'm just wondering now if there might be something already listening on port 2020 on your nodes. Do you happen to know something about that? It's EKS so the nodes can be either [managed or unmanaged](https://eksctl.io/usage/eks-managed-nodes/#feature-parity-with-unmanaged-nodegroups) but as you've already stated nothing changed in that regard 🤔

**Comment by pmalek-sumo** [comment]
Oh and maybe one more thing: just a conjuecture but maybe the resources given to fluent-bit:

```yaml
fluent-bit:
  resources:
    limits:
      cpu: 100m
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 8Mi
```

are not sufficient anymore and it doesn't repond to liveness/readiness probes because of that? Can you check its cpu utilization via e.g. `kubectl top pod` or `kubectl top node`?

**Comment by hussainsaify** [comment]
@pmalek-sumo  Please the output from top command

```
kubectl top pod sumologic-collector-fluent-bit-22hgs -n sumologic
NAME                                   CPU(cores)   MEMORY(bytes)   
sumologic-collector-fluent-bit-22hgs   1m  
```

Output from describe command for fluentbit pod

```
Name:         sumologic-collector-fluent-bit-22hgs
Namespace:    sumologic
Priority:     0
Node:         ip-10-**-**-176.ec2.internal/10.**.**.240
Start Time:   Mon, 07 Jun 2021 19:12:52 +0530
Labels:       app.kubernetes.io/instance=sumologic-collector
              app.kubernetes.io/name=fluent-bit
              controller-revision-hash=565b5bfd5d
              pod-template-generation=8
Annotations:  checksum/config: 85bed74c928a7f4ffb0f91024caa284429b492afb95d1c411342e5e02cd3ee8a
              checksum/luascripts: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
              kubernetes.io/psp: eks.privileged
Status:       Running
IP:           10.**.**.240
IPs:
  IP:           10.**.**.240
Controlled By:  DaemonSet/sumologic-collector-fluent-bit
Containers:
  fluent-bit:
    Container ID:   containerd://01b6f5c8116a430a4c8d99e5133fdef696782c5f4db7a4c5836c902540be0f25
    Image:          public.ecr.aws/sumologic/fluent-bit:1.6.10
    Image ID:       public.ecr.aws/sumologic/fluent-bit@sha256:33c7194d435bf6a9fa96257f3255667137e39522b6997e4249adf8a1a577cbf1
    Port:           2020/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Mon, 07 Jun 2021 19:13:45 +0530
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  512Mi
    Requests:
      cpu:     10m
      memory:  8Mi
    Environment:
      FLUENTD_LOGS_SVC:  <set to the key 'fluentdLogs' of config map 'sumologic-configmap'>  Optional: false
      NAMESPACE:         sumologic (v1:metadata.namespace)
    Mounts:
      /etc/machine-id from etcmachineid (ro)
      /fluent-bit/etc/custom_parsers.conf from config (rw,path="custom_parsers.conf")
      /fluent-bit/etc/fluent-bit.conf from config (rw,path="fluent-bit.conf")
      /tail-db from tail-db (rw)
      /var/lib/docker/containers from varlibdockercontainers (ro)
      /var/log from varlog (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from sumologic-collector-fluent-bit-token-vq9p7 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      sumologic-collector-fluent-bit
    Optional:  false
  varlog:
    Type:          HostPath (bare host directory volume)
    Path:          /var/log
    HostPathType:  
  varlibdockercontainers:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/docker/containers
    HostPathType:  
  etcmachineid:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/machine-id
    HostPathType:  File
  tail-db:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/fluent-bit
    HostPathType:  DirectoryOrCreate
  sumologic-collector-fluent-bit-token-vq9p7:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  sumologic-collector-fluent-bit-token-vq9p7
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     :NoSchedule op=Exists
                 node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                 node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                 node.kubernetes.io/not-ready:NoExecute op=Exists
                 node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                 node.kubernetes.io/unreachable:NoExecute op=Exists
                 node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:          <none>
```
This was the problem with all the fluentbit pods after the upgrade.

**Comment by pmalek-sumo** [comment]
One thing seems off with your snippet, namely that the fluent-bit container does not have liveness/readiness probes defined.

I've just tried myself, deployed on EKS 1.20 and I do see them (the same as in vagrant using microk8s 1.20) using your values:

```
Name:         collection-release2-fluent-bit-nrw4p
Namespace:    sumologic
Priority:     0
Node:         ip-192-168-47-0.eu-west-1.compute.internal/192.168.47.0
Start Time:   Tue, 08 Jun 2021 13:43:56 +0200
Labels:       app.kubernetes.io/instance=collection-release2
              app.kubernetes.io/name=fluent-bit
              controller-revision-hash=678669d565
              pod-template-generation=2
Annotations:  checksum/config: 6fe6cc938133e7daf5ed0f0356dc6d09b59a37a2bfa66854a0bcdfa62dc864e1
              checksum/luascripts: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
              kubernetes.io/psp: eks.privileged
Status:       Running
IP:           192.168.53.91
IPs:
  IP:           192.168.53.91
Controlled By:  DaemonSet/collection-release2-fluent-bit
Containers:
  fluent-bit:
    Container ID:   docker://da9f9f15b41c540147eb34df5c352b275e82fcb32f282ad0ef8665db7f93852b
    Image:          public.ecr.aws/sumologic/fluent-bit:1.6.10
    Image ID:       docker-pullable://public.ecr.aws/sumologic/fluent-bit@sha256:33c7194d435bf6a9fa96257f3255667137e39522b6997e4249adf8a1a577cbf1
    Port:           2020/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Tue, 08 Jun 2021 13:43:58 +0200
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  512Mi
    Requests:
      cpu:      10m
      memory:   8Mi
    Liveness:   http-get http://:http/ delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:  http-get http://:http/ delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      FLUENTD_LOGS_SVC:  <set to the key 'fluentdLogs' of config map 'sumologic-configmap'>  Optional: false
      NAMESPACE:         sumologic (v1:metadata.namespace)
    Mounts:
      /etc/machine-id from etcmachineid (ro)
      /fluent-bit/etc/custom_parsers.conf from config (rw,path="custom_parsers.conf")
      /fluent-bit/etc/fluent-bit.conf from config (rw,path="fluent-bit.conf")
      /tail-db from tail-db (rw)
      /var/lib/docker/containers from varlibdockercontainers (ro)
      /var/log from varlog (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from collection-release2-fluent-bit-token-pqs5r (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      collection-release2-fluent-bit
    Optional:  false
  varlog:
    Type:          HostPath (bare host directory volume)
    Path:          /var/log
    HostPathType:  
  varlibdockercontainers:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/docker/containers
    HostPathType:  
  etcmachineid:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/machine-id
    HostPathType:  File
  tail-db:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/fluent-bit
    HostPathType:  DirectoryOrCreate
  collection-release2-fluent-bit-token-pqs5r:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  collection-release2-fluent-bit-token-pqs5r
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     :NoSchedule op=Exists
                 node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                 node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                 node.kubernetes.io/not-ready:NoExecute op=Exists
                 node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                 node.kubernetes.io/unreachable:NoExecute op=Exists
                 node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  86s   default-scheduler  Successfully assigned sumologic/collection-release2-fluent-bit-nrw4p to ip-192-168-47-0.eu-west-1.compute.internal
  Normal  Pulled     84s   kubelet            Container image "public.ecr.aws/sumologic/fluent-bit:1.6.10" already present on machine
  Normal  Created    84s   kubelet            Created container fluent-bit
  Normal  Started    84s   kubelet            Started container fluent-bit
```

**Comment by hussainsaify** [comment]
@pmalek-sumo yes, i have temporarily removed them as it was preventing pod from running.

**Comment by pmalek-sumo** [comment]
I can't think of a different thing that might be causing these failure as of now. It has to be coming from the cluster configuration.

I've looked [EKS 1.20 release notes](https://aws.amazon.com/blogs/containers/amazon-eks-1-20-released/) and nothing suspicious there either.

[k8s changelog between 1.19 and 1.20](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#changelog-since-v1190) doesn't show anything fishy. There are some entries related to probes but nothing that caught my eye (and still, my EKS 1.20 cluster worked just fine).

**Comment by cbuto** [comment]
I recently upgraded from the sumologic-kubernetes-collection `1.3.5` to `2.1.2` and ran into this issue as well with a 1.20 cluster. 

I did not see any issue with fluent bit with `1.3.5` on Kubernetes 1.20.

**Comment by hussainsaify** [comment]
@pmalek-sumo Can you please try using bottlerocket as mentioned in the issue above? We also use bottlerocket nodes.

**Comment by pmalek-sumo** [comment]
Thanks all for chipping in.

@cbuto The reason it worked on `1.3.5` seems to be that on that version we were using a different fluent-bit chart from https://charts.helm.sh/stable (which is now deprecated) which doesn't use liveness/readiness probes.

It is defined in [here](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/v1.3.5/deploy/helm/sumologic/requirements.yaml#L2-L4) on our collection chart - this translates to usage of the following [daemonset template](https://github.com/helm/charts/blob/503c30691e6ec560436ad7f3e0ec64586368cdf3/stable/fluent-bit/templates/daemonset.yaml).

---

We could try verifying this on different versions of fluent-bit but I believe there's no use in that since this bug is about using 1.6.10 but the referenced issue fluent/helm-charts#120 mentions 1.7.5.

My suggestion at this point would be to observe the fluent-bit issue filed at https://github.com/fluent/fluent-bit/issues/3521 and as a work around I suggest to disable the probes in with [these chart options](https://github.com/fluent/helm-charts/blob/fluent-bit-0.12.1/charts/fluent-bit/values.yaml#L98-L106) as indicated by @hussainsaify in https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/1638#issuecomment-856695764

**Comment by hussainsaify** [comment]
@pmalek-sumo Can we have any workaround for the same as disabling probes doesn't help? It is a big issue because logs are not getting punlished to sumo.

**Comment by pmalek-sumo** [comment]
@hussainsaify If I understood correctly the issue stems from using Bottlerocket OS on k8s 1.20 with fluent-bit, correct?

If that's the case and the description in https://github.com/fluent/fluent-bit/issues/3521 is accurate then I can only suggest to use Amazon Linux 2 AMIs as also suggested there

**Comment by hussainsaify** [comment]
@pmalek-sumo Yes that is correct, it doesn't run on Bottlerocket 1.20 ami

**Comment by pmalek-sumo** [comment]
> it doesn't run on Bottlerocket 1.20 ami

What do you mean by that?

**Comment by frankreno** [comment]
@hussainsaify - while the underlying issue is being worked on upstream, I understand your desire to disable the probes so at least the pods can actually run and get data to Sumo. `Can we have any workaround for the same as disabling probes doesn't help? It is a big issue because logs are not getting punlished to sumo.`

It is possible to override the probes in the fluent-bit helm chart, but not disable from what I can see.

https://github.com/fluent/helm-charts/blob/main/charts/fluent-bit/templates/_pod.tpl#L57-L74

Something you can try is setting `fluent-bit.livenessProbe` and `fluent-bit.readinessProbe` to a command that always returns.  This will defeat the purpose of the probe ensuring the pod is healthy but will let the pods run while the upstream issue is dealt with.

This is an untested example you might try adding to our helm chart installation:


```
fluent-bit:
  livenessProbe:
      exec:
        command:
        - /bin/bash
        - pwd
   readinessProbe:
      exec:
        command:
        - /bin/bash
        - pwd
```

**Comment by hussainsaify** [comment]
> > it doesn't run on Bottlerocket 1.20 ami
> 
> What do you mean by that?

I mean this issue is only coming with instances having bottlerocket ami for k8s version 1.20.

**Comment by hussainsaify** [comment]
> @hussainsaify - while the underlying issue is being worked on upstream, I understand your desire to disable the probes so at least the pods can actually run and get data to Sumo. `Can we have any workaround for the same as disabling probes doesn't help? It is a big issue because logs are not getting punlished to sumo.`
> 
> It is possible to override the probes in the fluent-bit helm chart, but not disable from what I can see.
> 
> https://github.com/fluent/helm-charts/blob/main/charts/fluent-bit/templates/_pod.tpl#L57-L74
> 
> Something you can try is setting `fluent-bit.livenessProbe` and `fluent-bit.readinessProbe` to a command that always returns. This will defeat the purpose of the probe ensuring the pod is healthy but will let the pods run while the upstream issue is dealt with.
> 
> This is an untested example you might try adding to our helm chart installation:
> 
> ```
> fluent-bit:
>   livenessProbe:
>       exec:
>         command:
>         - /bin/bash
>         - pwd
>    readinessProbe:
>       exec:
>         command:
>         - /bin/bash
>         - pwd
> ```

Disabling the probe or changing the probe method will not help as the server is not running on port 2020.

**Comment by pmalek-sumo** [comment]
> Disabling the probe or changing the probe method will not help as the server is not running on port 2020.

@hussainsaify I understand and this aligns with findings in the underlying issue in Bottlerocket OS: https://github.com/bottlerocket-os/bottlerocket/issues/1628.

I'd suggest to to try Amazon Linux AMI instead of Bottlerocket OS for the time being because there's not much that can be done if the underlying service inside fluent-bit dies.

**Comment by pmalek-sumo** [comment]
@hussainsaify 

This seems to have a work around now: https://github.com/fluent/helm-charts/issues/120#issuecomment-878951791

> ... by making kubelet's `cpuManagerPolicy: none` as default. With `cpuManagerPolicy: static`, the issue still persists.

**Comment by hussainsaify** [comment]
Thsnka @pmalek-sumo , I will check it

**Comment by hussainsaify** [comment]
@pmalek-sumo  I can confirm that this isssue is fixed with bottlrocket os 1.1.3.

**Comment by pmalek-sumo** [comment]
Thanks for checking this @hussainsaify. I'm closing this issue then. In case you find anything else please report a new issue

**Comment by erkules** [comment]
Got the same issue with:
* Linux ip-10-104-220-154 5.4.0-1056-aws #59~18.04.1-Ubuntu SMP Mon Aug 23 23:07:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux 
* k8s: v1.22.2


I think the reason why this happens it not resolved. Changing something like a cpuManagerPolicy is not a way you can just do whithout a good reason.
