### ISSUE TITLE
collection-setup job fails when collector already exists

### ISSUE THREAD

**Issue by senior88oqz** [SumoLogic/sumologic-kubernetes-collection#1645]
We have `setupEnabled: true` and `cleanupEnabled: false` in our helm chart, however, when we try to reinstall the helm chart and the collection-setup job fails as previous installation has created the collector with the same name, is there anyway to resolve this?

**Comment by pmalek-sumo** [comment]
Hi @senior88oqz ,

We use terraform which imports the resources that we're trying to create before applying the plan. This basically solves the problem that you're for some reason experiencing.

Do you mind sharing the logs of setup job container when it runs and the `values.yaml` that you've used to install the collection?

**Comment by senior88oqz** [comment]
I met this problem when setting `sumologic.clusterName` when leaving `sumologic.collectorName` as it is (`""`, will be the clusterName as per your docs though). Still have the same problem when setting both `clusterName` and `collectorName`, ie
```
Error: {
  "status" : 400,
  "id" : "XXXXX",
  "code" : "collectors.validation.name.duplicate",
  "message" : "A resource with the same name already exists."
}

  on resources.tf line 1, in resource "sumologic_collector" "collector":
   1: resource "sumologic_collector" "collector" {
```

**Comment by senior88oqz** [comment]
okay, the issue being there's a `/` in my collector name, hence it's unable to import.
