### ISSUE TITLE
Will you add fluent-bit 1.8+ support?

### ISSUE THREAD

**Issue by hemanth-codaio** [SumoLogic/sumologic-kubernetes-collection#1709]
From here: https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/1551 it appears fluent-bit is pinned at an older version. We'd really like to use 1.8+ as it adds robust health-checks and also fixes the bug outlined above. Will you be bumping the version of fluent-bit available in your repository?

Thanks!

**Comment by hemanth-codaio** [comment]
Hi, polite bump on this :) If nothing else, would you mind at least adding 1.8.3 to your repository, so that we can manually override the default and pull it? Thanks.

**Comment by sumo-drosiek** [comment]
Hi, sorry for late response

We are careful with upgrading to newest releases as in the past  (as in the issue you mentioned) they were not stable

Is using the docker repository sufficient solution for you, or do you require to have images in ECR repository?

For docker repository:

```yaml
fluent-bit:
  image:
    repository: fluent/fluent-bit
    pullPolicy: IfNotPresent
    tag: 1.8.3
```

**Comment by perk-sumo** [comment]
Hi @hemanth-codaio what Dominik provided is our preferred solution for using images different from what we provide by default.

Is that working for you? Can we close this issue?

**Comment by hemanth-codaio** [comment]
Yup - sorry for the delay here. This is working perfectly for us - thank you!
