### ISSUE TITLE
feat(deploy/otc): ensure backward compatibility for tpl change

### ISSUE THREAD

**Issue by sumo-drosiek** [SumoLogic/sumologic-kubernetes-collection#1729]
Drop backward compatibility for tpl change

revert #1721

**Comment by perk-sumo** [comment]
This needs triage.

**Comment by perk-sumo** [comment]
We need to check if we don't need to migrate off of the `Values.fluentd.logs.` in our values.yaml

**Comment by kkujawa-sumo** [comment]
Fixed by https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/2615

We need to remove references to fluentd configuration in otelcol configuration but in my opinion it is not strictly connected to this issue (this will be made in another pull request).
