### ISSUE TITLE
Remove `.Values.fluentd.logs.containers.sourceHost` from the chart

### ISSUE THREAD

**Issue by pmalek-sumo** [SumoLogic/sumologic-kubernetes-collection#1782]
`.Values.fluentd.logs.containers.sourceHost` is already not referenced anywhere in `values.yaml` so let's remove it.

This would be a breaking change since users had the possibility to manually add this to `values.yaml` and observe the effect of that value changed.

https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/d87aab8d99d63c3ff364c72b85aa9cd2cba4855f/deploy/helm/sumologic/conf/logs/fluentd/logs.kubernetes.sumologic.filter.conf#L2

**Comment by frankreno** [comment]
@pmalek-sumo - so are we sure this setting is not used? i see if referenced in the config - https://github.com/SumoLogic/sumologic-kubernetes-fluentd/blob/main/fluent-plugin-kubernetes-sumologic/lib/fluent/plugin/filter_kubernetes_sumologic.rb#L80. Perhaps its not exposed in values.yaml by default, but people could be setting it and it could effect the metadata it seems

**Comment by pmalek-sumo** [comment]
@frankreno This issue is about having a configuration option in the chart that's not:

* exposed in `values.yaml`
* documented

but it is possible to set. Perhaps we should instead put this option back to `values.yaml` and document it? WDYT @frankreno?

**Comment by astencel-sumo** [comment]
I propose to fix this issue by adding this property to `values.yaml` and documentation.
