### ISSUE TITLE
Support for the Kube State Metrics v2

### ISSUE THREAD

**Issue by perk-sumo** [SumoLogic/sumologic-kubernetes-collection#1808]

**Comment by dindurthy** [comment]
It might, but the metric is unusable for us without exactly that breaking change, so for now, we can't alert on waiting containers. Is a v3.0 sumologic-kubernetes-collection on the horizon?

**Comment by perk-sumo** [comment]
Please triage if we get all the needed metrics etc.

**Comment by perk-sumo** [comment]
Please consult with apps team if all the metrics needed for dashboards are there.

**Comment by kkujawa-sumo** [comment]
apps team confirmed that all metrics are on dashboards.
