### ISSUE TITLE
Update documentation around additionalRemoteWrite for kube-prometheus-stack

### ISSUE THREAD

**Issue by perk-sumo** [SumoLogic/sumologic-kubernetes-collection#1822]

**Comment by perk-sumo** [comment]
We cannot bump the kube-prometheus-stack in v2.2 because that would be a breaking change: https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/1832
This task needs to be done whenever we can update the stack again.

**Comment by rnishtala-sumo** [comment]
@perk-sumo  @sumo-drosiek  The documentation update was merged in the PR below
https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/2549
Could we close this issue?
