### ISSUE TITLE
Add `affinity` sections to the `fluentd` templates

### ISSUE THREAD

**Issue by cailyoung** [SumoLogic/sumologic-kubernetes-collection#1880]
**Is your feature request related to a problem? Please describe.**
We want to control which node pools the collection's pods run in. `nodeSelector` isn't flexible enough for our needs as we don't have a set of labels that could be used as an AND to define a nodeSelector. Also, we can't use `antiAffinity` to space out replicas across nodes. 

**Describe the solution you'd like**
Add `affinity` sections to the `values.yaml` for each of the templates creating Deployments in the chart, and then pull those through to the templates.

**Describe alternatives you've considered**
Applying more labels so that we can do a 'don't run on nodes with this label' by applying another label to every other node pool would work, but is a lot of overhead for us to manage.

**Comment by pmalek-sumo** [comment]
We already expose the following configuration options (in the deploy docc: https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/deploy/helm/sumologic/README.md)

| Parameter                                      | Description                                                            | Default |
|------------------------------------------------|------------------------------------------------------------------------|---------|
| `fluentd.logs.statefulset.affinity`            | Affinity for Fluentd log statefulset.                                  | `{}`    |
| `fluentd.logs.statefulset.podAntiAffinity`     | PodAntiAffinity for Fluentd log statefulset.                           | `soft`  |
| `fluentd.metrics.statefulset.affinity`         | Affinity for Fluentd metrics statefulset.                              | `{}`    |
| `fluentd.metrics.statefulset.podAntiAffinity`  | PodAntiAffinity for Fluentd metrics statefulset.                       | `soft`  |
| `metadata.metrics.statefulset.affinity`        | Affinity for metrics metadata enrichment (otelcol) statefulset.        | `{}`    |
| `metadata.metrics.statefulset.podAntiAffinity` | PodAntiAffinity for metrics metadata enrichment (otelcol) statefulset. | `soft`  |
| `metadata.logs.statefulset.affinity`           | Affinity for logs metadata enrichment (otelcol) statefulset.           | `{}`    |
| `metadata.logs.statefulset.podAntiAffinity`    | PodAntiAffinity for logs metadata enrichment (otelcol) statefulset.    | `soft`  |

and you can find that being used e.g. in https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/e1f8406d818aa6036450279ced0b809e9807c525/deploy/helm/sumologic/templates/logs/fluentd/statefulset.yaml#L53-L91

Let us know if you @cailyoung had something else on your mind.

**Comment by cailyoung** [comment]
Maybe it's just `events`?

https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/e1f8406d818aa6036450279ced0b809e9807c525/deploy/helm/sumologic/templates/events/fluentd/statefulset.yaml#L40-L78

**Comment by pmalek-sumo** [comment]
@cailyoung I believe that's what you meant right? https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1895

**Comment by cailyoung** [comment]
Yep, thanks!

**Comment by pmalek-sumo** [comment]
I've merged in #1895. This will land in our next release whenever it's out.
