### ISSUE TITLE
Installation with helm example

### ISSUE THREAD

**Issue by njparisi** [SumoLogic/sumologic-kubernetes-collection#190]
In order to set the desired cluster metadata field value for both logs and metrics follow the below example when executing the setup script and helm install.

curl -s https://raw.githubusercontent.com/SumoLogic/sumologic-kubernetes-collection/master/deploy/docker/setup/setup.sh \
  | bash -s - -d false -y false -c <collector_name> -k <cluster_name> <api_endpoint> <access_id> <access_key> 

helm install sumologic/sumologic --name collection --namespace sumologic --set prometheus-operator.prometheus.prometheusSpec.externalLabels.cluster=<cluster_name>

Make sure the two <cluster_name> values are the same.

**Comment by rvmiller89** [comment]
This is now documented: https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/master/deploy/docs/Installation_with_Helm.md
