### ISSUE TITLE
fluentdLogLevel in values.yaml has no effect

### ISSUE THREAD

**Issue by emcay** [SumoLogic/sumologic-kubernetes-collection#202]
Either fluentdLogLevel in the values yaml has no effect, or does not perform as described. Changing to values like "warn" or "error" do not actually appear to have any impact on log level.

This is desired because fluentd stdout is exceptionally chatty, particularly when there are warn messages, which in our case were being issued repeatedly in the tens-of-millions which is unhelpful and greatly made issues worse by unexpectedly and dramatically increasing log volume.

**Comment by abhi-sumo** [comment]
Is the desired effect similar to setting this property in the configmap?
https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/master/deploy/README.md#fluentd-logs

**Comment by emcay** [comment]
Yes, that is what I expected from it initially.

**Comment by rvmiller89** [comment]
For Helm installation you can use `fluentdLogLevel`, e.g.
```
helm upgrade collection sumologic/sumologic --reuse-values --set sumologic.fluentdLogLevel="debug"
```

For non-Helm installation you can update the deployment yaml -OR- update the config map and redeploy the fluentd pods:
```
<system>
  log_level debug
</system>
```
explained here: https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/master/deploy/docs/Troubleshoot_Collection.md#fluentd-logs
