### ISSUE TITLE
Installation behind proxy fails

### ISSUE THREAD

**Issue by jonathansloman** [SumoLogic/sumologic-kubernetes-collection#203]
Our kubernetes cluster is on our corporate network, any http/https access to the internet has to go through a proxy. I can see no way to set a proxy to allow this to work. Attempting to install hangs on the pre-install setup

Please make it possible to specify an http/https proxy on install.

**Comment by jonathansloman** [comment]
For anyone else stuck by this - it's possible to get it to work if you follow the steps for 'Non Helm Installation'. At the 'Automatic Source Creation and Setup Script' stage - use the '-d false' option to not deploy, but just to create the fluentd-sumologic.yaml file. You need to then manually edit this file and add to the 'env:' section for both containers an environment variable called PROXY_URI with the value http://proxy-hostname:proxy-port/  - this will probably only work with non-authenticating proxies.

You can then kubectl apply the file and carry on with the rest of the instructions.

**Comment by abhi-sumo** [comment]
Hey @jonathansloman were you able to get it installed with this workaround?

**Comment by jonathansloman** [comment]
hi, I believe so, yes - adding PROXY_URI to the environment for collection-sumologic and collection-sumologic-events allows them to successfully send the data to sumo.

Ideally though the helm install process would work, which would mean also making the pre-install setup phase proxy-aware as well, as I believe it uses curl/wget (which I think would both honour http_proxy and https_proxy environment variables if set).

**Comment by vsinghal13** [comment]
I think this can be solved by #681 as now we have the ability to add additional env variables. Based on the comment looks like we will need to add the same in events sts as well.

**Comment by frankreno** [comment]
In addition to the event STS you also need to add the capability to the setup job so outbound calls to Sumo can be proxied. I believe TF supports the `HTTPS_PROXY` env var.
