### ISSUE TITLE
Update helm install with helm upgrade --install

### ISSUE THREAD

**Issue by carlsalazar1** [SumoLogic/sumologic-kubernetes-collection#204]
We need to have a helm upgrade command example if we want to change parameters in the values.yaml file.

Suggested example:
helm upgrade collection sumologic/sumologic --install --force --namespace sumologic --set sumologic.endpoint=https://api.us2.sumologic.com/api/v1/ --set sumologic.accessId=id --set sumologic.accessKey=key -f values.yaml

**Comment by emcay** [comment]
The below has worked for me in my case, however it is not symptom free. It can create some congestion as it appears to restart some of the pods.

`helm upgrade --reuse-values -f ./sumologic/values.yaml collection sumologic/sumologic`

**Comment by frankreno** [comment]
We have upgraded the `helm upgrade` documentation and it does make note of the `--reuse-values`.  Users can still use either approach so do not think a change is needed at this time.
