### ISSUE TITLE
Rename the configuration file from values.yaml to config.yaml in docs and examples

### ISSUE THREAD

**Issue by perk-sumo** [SumoLogic/sumologic-kubernetes-collection#2109]
Many times customers are confused with the `values.yaml` config file.
Is it `values.yaml` with default chart values?
Is it configuration customer should provide when installing the chart?

Let's switch to using ~`configuration.yaml`~ `config.yaml` whenever we talk about user provided configuration and use `values.yaml` whenever we talk about the default Helm Chart configuration.

Let's make that distinction super clear at the beginning of the docs.

**Comment by rplahn** [comment]
Any thoughts on when this might be merged? Just wondering if there are any new considerations on this guidance for best practice with our chart. Thanks!
