### ISSUE TITLE
Can we default the collection process to exclude Sumologic Logs

### ISSUE THREAD

**Issue by abhi-sumo** [SumoLogic/sumologic-kubernetes-collection#211]
The suggestion that we should default to excluding the sumologic namespace as those are primarily sumo specific logs.

**Comment by frankreno** [comment]
I think a good implementation of this would be to modify the Helm chart to have a flag like sumologic.collectionMonitoring, defaulted to true.  IF you set it to false, it would set EXCLUDE_NAMESPACE=sumologic and not add the fluentD/fluent-bit and Prometheus remotestorage metrics.

**Comment by rvmiller89** [comment]
We rely on those logs to debug issues so it may be best to default to collecting them, but allow the customer to disable them (with the understanding we won't be able to triage issues they may encounter)?

**Comment by frankreno** [comment]
Agreed on default being true, but conditional enablement for the win here
