### ISSUE TITLE
Metrics are not enriched with daemonset when otelcol is used

### ISSUE THREAD

**Issue by perk-sumo** [SumoLogic/sumologic-kubernetes-collection#2118]
The following query shows data when Fluentd is being used and doesn't work when OTC is used:
```daemonset=* metric=container_cpu_usage_seconds_total```

Apparently otelcol does not enrich metrics with daemonset metadata. It does enrich with statefulset and deployment.

**Comment by pmalek-sumo** [comment]
It seems it never worked 😅 

Even the contrib doesn't have this: https://github.com/SumoLogic/opentelemetry-collector-contrib/blob/f5390723a9541f469abcf05df4100d405b6ed5e2/processor/k8sprocessor/kube/owner.go#L103-L132
