### ISSUE TITLE
Problem in chart hook prevents installation

### ISSUE THREAD

**Issue by bergerx** [SumoLogic/sumologic-kubernetes-collection#212]
Our installation is currently fails due to the https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/e61a3f5665cdd75af82befe9daf061f0f12fe1bd/deploy/helm/sumologic/templates/setup/setup-job.yaml.

Here is what we see in helm install:
```
# helm install sumologic/sumologic --name collection --namespace sumologic --set sumologic.endpoint=https://api.sumologic.com/api/v1/ --set sumologic.accessId={...cropped...} --set sumologic.accessKey={...cropped...} -f sumo_values.yaml 
Error: timed out waiting for the condition
```

Checking the events:
```
# kubectl describe job collection-sumologic-setup -n sumologic
...
Events:
  Type     Reason                Age   From            Message
  ----     ------                ----  ----            -------
  Normal   SuccessfulCreate      27m   job-controller  Created pod: collection-sumologic-setup-5hh47
  Normal   SuccessfulDelete      21m   job-controller  Deleted pod: collection-sumologic-setup-5hh47
  Warning  BackoffLimitExceeded  21m   job-controller  Job has reached the specified backoff limit
```

Available logs in the Job's Pod:
```
# kubectl logs collection-sumologic-setup-chxnl -n sumologic
Namespace 'sumologic' exists, skip creating.
Checking for secret 'sumologic'...
Creating collector 'kubernetes-{...cropped...}' for cluster kubernetes...
Failed to create collector:
{ "status" : 301, "id" : "{...cropped...}", "code" : "moved", "message" : "The requested resource SHOULD be accessed through returned URI in Location Header." }
# 
```

**Comment by bergerx** [comment]
Seems like related to https://github.com/SumoLogic/sumo-api-doc/issues/4 but no clue how to figure out the right location or how to set it.

Seems like we need to use a different endpoint listed in https://help.sumologic.com/APIs/General-API-Information/Sumo-Logic-Endpoints-and-Firewall-Security.

**Comment by bergerx** [comment]
After changind the endpoint the job now ends with this error (this is all of the logs from the hook Job):

```
# kubectl logs collection-sumologic-setup-9xxzf -n sumologic -f
Namespace 'sumologic' exists, skip creating.
Checking for secret 'sumologic'...
Creating collector 'kubernetes-1569333843' for cluster kubernetes...
# 
```

**Comment by njparisi** [comment]
@bergerx try deleting the sumologic namespace and make sure that the collector doesn't already exist and the accessId and accessKey have permissions to create collectors.

**Comment by njparisi** [comment]
Looking at the initial command I think you need to use the following api endpoint.
https://api.us2.sumologic.com/api/v1/

**Comment by bergerx** [comment]
Thanks that helped, the chart is now successfully installed..
