### ISSUE TITLE
change default logs scrape path from /var/log/containers to /var/log/pods

### ISSUE THREAD

**Issue by perk-sumo** [SumoLogic/sumologic-kubernetes-collection#2171]
The `/var/log/containers` path is a symlink to `/var/log/pods` now.
Let's switch to using `/var/log/pods` directory directly.

Some context:
https://github.com/kubernetes/kubernetes/issues/53022

**Comment by sumo-drosiek** [comment]
Instruction: https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/53f77a697d0e93a3e4de16123ed1d8cf4599e00f/deploy/docs/Best_Practices.md#collecting-logs-from-varlogpods

**Comment by swiatekm-sumo** [comment]
Do we actually need to do this? We're already using `/var/log/pods` in the otel log collector, and we want to get rid of Fluent-Bit and FluentD completely in v4? It looks like the change is breaking because it changes defaults for some parsing regular expressions,, and I'm wondering if there's any reason to do it other than making things more consistent temporarily. @sumo-drosiek WDYT?

**Comment by swiatekm-sumo** [comment]
> I would change it, as there is multiple components which are using it, fluent-bit, fluentd, otelcol, otellogs and because of the possible combinations it can be troublesome

I don't think we can migrate this automatically, so users who customized those specific configuration options would need to manually adjust them anyway.

**Comment by sumo-drosiek** [comment]
> > I would change it, as there is multiple components which are using it, fluent-bit, fluentd, otelcol, otellogs and because of the possible combinations it can be troublesome
> 
> I don't think we can migrate this automatically, so users who customized those specific configuration options would need to manually adjust them anyway.

For migration we can cover steps from the instruction: https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/53f77a697d0e93a3e4de16123ed1d8cf4599e00f/deploy/docs/Best_Practices.md#collecting-logs-from-varlogpods

**Comment by perk-sumo** [comment]
Turns out this is expensive to do and we should just not do it at all.
