### ISSUE TITLE
Add prometheus pushgateway to the helm chart

### ISSUE THREAD

**Issue by thedevelopnik** [SumoLogic/sumologic-kubernetes-collection#219]
At GoSpotCheck, we use the pushgateway to receive metrics from our Spark jobs from outside the cluster. The prometheus-operator chart does not include the pushgateway from some reason.

The [stable pushgateway chart](https://github.com/helm/charts/tree/master/stable/prometheus-pushgateway) is compatible with the operator in that it can add an optional service monitor. So a dependency on that chart could be added to this.

Right now that isn't compatible with our needs because it doesn't allow annotations on the service, only the ingress (we expose the pushgateway via [Ambassador](https://getambassador.io) which reads service annotations). I have a [PR open](https://github.com/helm/charts/pull/17437) to add annotations to the service on the chart, but no idea how long that will take to get merged. But that personal problem doesn't mean it's not the right solution overall here.

EDIT: oh hey 6 days ago Ambassador added support as an Ingress. So now just adding a dependency on the stable pushgateway chart would work fine.

**Comment by frankreno** [comment]
At the moment, we are not planning on including the Pushgateway chart dependencies.
