### ISSUE TITLE
Silent failure when sourceCategory isn't allowed

### ISSUE THREAD

**Issue by tavin** [SumoLogic/sumologic-kubernetes-collection#2223]
Suppose `kubernetes-collection-sumologic-fluentd-events` is configured to send the messages to a source category which isn't allowed on the sumo side. It's a completely silent failure. You get nothing in the log output from the statefulset indicating there's a problem (not even with debug logging). You simply never see your messages in sumo, which leads to a lot of wasted troubleshooting until you guess that it's the source category that needs to be changed.

**Comment by tavin** [comment]
Btw, the only thing that does appear in the (debug level) fluentd logs when messages are being sent to the sumo collector endpoint is a statement from the fluentd buffer module ("Created new chunk ..."). It would be good to log something about actually sending the logs/events. Perhaps just after the HTTP request, e.g. "200 response from HTTP collector; sent 1 message(s)".

**Comment by astencel-sumo** [comment]
Hi @tavin, thanks for your report. I don't quite understand what you mean by:

> Suppose kubernetes-collection-sumologic-fluentd-events is configured to send the messages to a source category which isn't allowed on the sumo side.

Can you provide a piece of configuration that will help me understand your scenario? Did you set the `fluentd.events.sourceCategory` property in your`values.yaml` file?

**Comment by tavin** [comment]
Hi @astencel-sumo, so I don't know if sumo has a concept of source category write permissions -- I guess not. But my company definitely restricts which source categories I can read when running a log search.

Initially I did not know about setting `fluentd.events.sourceCategory` so the events were (I presume) being dumped into a default category which I was unable to see in sumo log search. Thus I was unable to verify that collection was working.

I'm surprised that it's possible for me to create a collector (via the automated setup) with a source (events) that writes into a source category I'm not allowed to read, and I see that as a bug. I would expect an error during collector setup or else as the HTTP response from that collector endpoint.

**Comment by astencel-sumo** [comment]
Oh I think I understand this better now, thanks. Let me chat about this with the team.

**Comment by astencel-sumo** [comment]
I've discussed this issue with the team. This is a result of how the Sumo backend works and it has its merits. It should be possible for a user to configure data collection (be it with the Sumo Logic Kubernetes Collection solution here, or with some other means) even if this user will not be able to query on this data later. This is a valid scenario in bigger installations / enterprise, where the user that queries the data is different from the one that sets up the collection and they have disjoint sets of permissions.

Given the above, we consider this to not be a bug in the Sumo Logic Kubernetes Collection.

Let me know what you think @tavin.

**Comment by tavin** [comment]
I appreciate you all having looked into it so quickly, and I do understand your conclusion. However, you have at least some opportunities to improve user experience here:

* Log the sending of messages to the collector endpoint as I suggested above.
* Require an explicit choice for `fluentd.events.sourceCategory` and similar parameters, so that people don't get stuck with a bad default.
* And/or, let the user configure a main `sourceCategoryPrefix` in just one place, so that by default events as well as container/kubelet/systemd logs all have source categories under the same root.

Finally, though it's not related to sumologic-kubernetes-collection, this would be nice -- in sumo log search, instead of merely reporting the search returned no results, it could add "but messages were matched in source categories which are not currently visible" or something like that.

Cheers @astencel-sumo and team.

**Comment by astencel-sumo** [comment]
Yes, I agree there is room for improvement here. Thanks a lot for these suggestions, they are very informative and sensible. We will look at them with the team (the first one is I believe a no-brainer).

I will also pass on your feedback about the log search not informing that the results are actually there, you just have no permissions to access them. I agree it would be good to have this.

Thanks @tavin for this productive discussion. I'll try to remember to update this issue when we complete some action items related to this.

**Comment by astencel-sumo** [comment]
@tavin, got a response from the search team with regards to the lack of information that data is available but not accessible due to permissions:

> That's against the usual security practices. If someone doesn't have access to something, they just don't see it instead of telling them that it exists but you don't have permissions.
It's more of a philosophical debate in my opinion - but what we follow is a widely adopted industry standard.

**Comment by astencel-sumo** [comment]
> we're talking about users within the same company here
To be honest, I thought the same thing. I've passed on your remark as well.

I understand your frustration. Here's my change to add debug logs on sending data: https://github.com/SumoLogic/fluentd-output-sumologic/pull/75. We will release a new version of the Sumo Logic Fluentd output plugin and incorporate it in an upcoming release of the Sumo Logic chart.
