### ISSUE TITLE
Error: secrets "sumologic" not found when setupEnabled = false

### ISSUE THREAD

**Issue by christophla** [SumoLogic/sumologic-kubernetes-collection#223]
The setup process is not idempotent and will fail if the collector already exists. As a result, we needed to set `setupEnabled: false`.

When this flag is set, the `sumologic` secret never gets set. The sumologic service pods fail with the error:

```Error: secrets "sumologic" not found```

**Comment by frankreno** [comment]
@christophla : Please try the latest version as we have changed the setup process to be idempotent.

**Comment by rvmiller89** [comment]
This should be fixed with 0.11.0+
