### ISSUE TITLE
Sumologic fluentd v2.7.0 install fails when deployed through argocd / devtron

### ISSUE THREAD

**Issue by prakarsh-dt** [SumoLogic/sumologic-kubernetes-collection#2261]
**Describe the bug**
When installing the sumologic fluentd helm chart v2.7.0 with Argocd or Devtron, it fails.

**Logs**
```parse error at (sumologic/charts/sumologic/templates/setup/configmap.yaml:73): function "dig" not defined Use --debug flag to render out invalid YAML```

**Command used to install/upgrade Collection**
Installed through Devtron UI

**Configuration**
Configuration used for Collection e.g. values.yaml for helm.

**To Reproduce**
Deploy a helm chart through Devtron UI / Argocd

**Expected behavior**
The chart should get deployed without any error.

**Environment (please complete the following information):**
 - **Chart version** (e.g. `helm ls -n sumologic`): v2.7.0
 - **K8s version** (e.g. `kubectl version`): K8s 1.19
 - **Cloud Provider**: AWS

**Anything else do we need to know**
The problem is caused due to a typo which passes through the helm template test. Creating a PR for the fix in a while.

**Comment by sumo-drosiek** [comment]
Hi, what helm version do you use in argocd/devtron?

dig should be available as it is defined in sprig library which is used for helm templates

http://masterminds.github.io/sprig/dicts.html#dig

**Comment by prakarsh-dt** [comment]
Argocd version 1.8

**Comment by sumo-drosiek** [comment]
`dig` is available in `sprig` from https://github.com/Masterminds/sprig/releases/tag/v3.2.0
`sprig` in `3.2.0` is avaialable in `helm` from https://github.com/helm/helm/releases/tag/v3.5.0

**Comment by sumo-drosiek** [comment]
Seems that next helm release has been done in https://github.com/argoproj/argo-cd/releases/tag/v2.2.0
(looking for PR specifically upgrading helm)

Anyway, our collection won't work for `helm < 3.5.0` :/

**Comment by sumo-drosiek** [comment]
Sorry, actually https://github.com/argoproj/argo-cd/releases/tag/v2.0.0 is the next helm upgrade after `v1.8.0`

**Comment by peter-mueller-viacom** [comment]
We ran into this as well.  If you are using terraform, it seems you will need at least hashicorp/helm 2.1.0.  I'm not aware of any reason not use latest helm provider (currently 2.5.1).  Bumping the helm provider resolved issue for us.  Thanks!

**Comment by sumo-drosiek** [comment]
@prakarsh-dt I'm closing this issue as I believe everything is clear now. Please reopen in case there is something we should fix
