### ISSUE TITLE
BoundServiceAccountTokenVolume/service account token TTL on EKS 1.22

### ISSUE THREAD

**Issue by voidlily** [SumoLogic/sumologic-kubernetes-collection#2280]
On EKS 1.22, AWS enabled BoundServiceAccountTokenVolume, which introduces a TTL on service account tokens. Their scanner pointed to sumologic's serviceaccount, and from my research it looks like it may be from fluent-bit.

The fix for this seems like it depends on https://github.com/fluent/fluent-bit/pull/4487, and then a fluent-bit upgrade in the sumologic collection stack.

**Comment by swiatekm-sumo** [comment]
How did you come to the conclusion that it was Fluent-Bit? The purpose of this ServiceAccount is to let metadata enrichment talk to the K8s API, and the only applications that have it set are FluentD and Otelcol.

Otelcol should be fine, as it uses a recent version of client-go.

FluentD, I think we need to update. A cursory glance at https://github.com/ManageIQ/kubeclient doesn't show any mechanism that would take care of rereading the token automatically on an auth error. I suppose we could fix it on our end by recreating the client in that case in https://github.com/SumoLogic/sumologic-kubernetes-fluentd/blob/5fc01c8e668fb3cc90d92e4570c10710a291e090/fluent-plugin-enhance-k8s-metadata/lib/sumologic/kubernetes/reader.rb#L110, but we could also try to fix it in upstream. WDYT @astencel-sumo ?

**Comment by voidlily** [comment]
I'll admit I'm not entirely sure about fluent-bit, it just seemed like a likely lead given a recent fix committed there and it being somewhat out of date in the sumo stack.

All I really had to go on was AWS giving us a list of serviceaccounts and it just said the sumologic serviceaccount from the helm chart

**Comment by swiatekm-sumo** [comment]
@voidlily a new FluentD image with the fix is available: https://github.com/SumoLogic/sumologic-kubernetes-fluentd/releases/tag/v1.14.6-sumo-3. I'm going to issue patch releases for each supported minor version of the Helm Chart, but you can also simply update the version in your configuration if you want to test it first.
