### ISSUE TITLE
Switch to OTLP source for data coming from OpenTelemetry Collector

### ISSUE THREAD

**Issue by perk-sumo** [SumoLogic/sumologic-kubernetes-collection#2282]
We should use the OTLP source for data that comes from OpenTelemetry Collector instead of using the general HTTP source.

Fluentd will use the old method as it doesn't support the OTLP output.

**Comment by swiatekm-sumo** [comment]
Implemented optionally for logs here: #3040 
Implemented optionally for events here: #3093 
Implemented optionally for traces here: #3094

**Comment by swiatekm-sumo** [comment]
Still pending for metrics: https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/2949
