### ISSUE TITLE
Add support for AKS 1.23, GKE 1.22 and EKS 1.22

### ISSUE THREAD

**Issue by perk-sumo** [SumoLogic/sumologic-kubernetes-collection#2307]

**Comment by mars64** [comment]
In case its helpful, I'm currently using this chart (as of [c1f49db](https://github.com/SumoLogic/sumologic-kubernetes-collection/commit/c1f49db24b91382816d01bd0af3e5ddb72183647)) with `v1.22.6-eks-14c7a48`, logs-only. It seems to be working properly for me.
