### ISSUE TITLE
No information given when release name or namespace are changed

### ISSUE THREAD

**Issue by alexbklein91** [SumoLogic/sumologic-kubernetes-collection#234]
When running the helm install, `helm install sumologic/sumologic --name collection --namespace sumologic ` If you change the name or namespace and don't change the remote write and the fluentd endpoint then nothing will work. If someone changes the release name or namespace from the default options we should give some type of info to let them know it won't work without the proper updates to the values.yaml.

**Comment by vsinghal13** [comment]
Now we do not have to change the remote write section manually. Its changed automatically via parameters.

Closing the issue.
