### ISSUE TITLE
fluentd.metrics.enabled is not respected

### ISSUE THREAD

**Issue by sumo-drosiek** [SumoLogic/sumologic-kubernetes-collection#2362]
In order to disable fluentd for logs/metrics, the following configuration should be used [according to `README.md`](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/deploy/helm/sumologic/README.md?plain=1#L185):

```
fluentd:
  metrics:
    enabled: false
```

But it doesn't work

**Comment by sumo-drosiek** [comment]
This is due to misunderstaning of the helm template

**Comment by sumo-drosiek** [comment]
This is probably same case for fluentd logs, but didn't test it

**Comment by astencel-sumo** [comment]
This seems to be a documentation issue. The correct key is `sumologic.metrics.enabled` and `sumologic.logs.enabled`, right?

**Comment by sumo-drosiek** [comment]
https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/d72b43a67de3abbb653575477b2d5d053ff596e9/deploy/helm/sumologic/templates/_helpers.tpl#L1255-L1257
