### ISSUE TITLE
Remove load_config_file from kubernetes terraform

### ISSUE THREAD

**Issue by sumo-drosiek** [SumoLogic/sumologic-kubernetes-collection#2398]
Remove load_config_file it in 3.0

_Originally posted by @sumo-drosiek in https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/2397#discussion_r910694888_

**Comment by sumo-drosiek** [comment]
Remove `load_config_file` and all references as this parameter is not supported from [v2.0.0](https://github.com/hashicorp/terraform-provider-kubernetes/releases/tag/v2.0.0)

**Comment by sumo-drosiek** [comment]
Clean up this line: https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/1087475925265e154a71f66c96a1b96eeb4a0c99/deploy/helm/sumologic/conf/setup/providers.tf#L22

**Comment by perk-sumo** [comment]
Additionally we should make migration tool to remove this key if it was in the values.yaml
