### ISSUE TITLE
docs: Write documentation on collecting metrics from user workloads

### ISSUE THREAD

**Issue by astencel-sumo** [SumoLogic/sumologic-kubernetes-collection#2417]
We need high-level documentation for collecting metrics from user workloads (applications) running in the cluster, similar to https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/v2.11.0/deploy/docs/collecting-kubernetes-events.md for collecting Kubernetes events.

It should describe the frequent use cases, like:
- specifying the pods, namespaces, etc. to collect data from in a chosen format
- using pod annotations to enable collection from a workload and specify collection endpoints
- customizing the collected data - decorating with metadata, filtering, etc.

This might (and hopefully should) result in changes to configuration of the metrics collection, so that the common use cases do not force the user to mess with the raw Prometheus or OTC configuration, or even prevent that configuration from being exposed in the `values.yaml` file.

**Comment by sumo-drosiek** [comment]
This is done by: https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/2724, https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/2716, https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/2524
