### ISSUE TITLE
Be able to schedule the setup job in a tainted nodepool.

### ISSUE THREAD

**Issue by severity1** [SumoLogic/sumologic-kubernetes-collection#2424]
**Is your feature request related to a problem? Please describe.**
There are use-cases wherein you might need to schedule sumologic collector into a tainted nodepool atm all the other components are being scheduled correctly into tainted nodepools but not the sumologic-setup job which means if there are no nodepools in your cluster with no taints the setup job will never be scheduled thus setup will never proceed.

**Describe the solution you'd like**
Ability to define tolerations and affinity in the setup job.

**Describe alternatives you've considered**
Temporarily spinup a nodepool with a single node with no taint just for setup to proceed and tear it down after setup which breaks our preffered automation way and is kinda wasteful.

**Comment by sumo-drosiek** [comment]
Change has been released: https://github.com/SumoLogic/sumologic-kubernetes-collection/releases/v2.12.0
