### ISSUE TITLE
HPA for OtelGateway and OtelCol

### ISSUE THREAD

**Issue by mat-rumian** [SumoLogic/sumologic-kubernetes-collection#2431]
Currently theres no Horizontal Pod Autoscale for collectors related to OT instrumentation data - otelgateway and otelcol will require HPA.

**Comment by prysmakou-sa** [comment]
I'm testing helm upgrade from 2.17 -> 3.8.0
I get:
```
Error from server (NotFound): horizontalpodautoscalers.autoscaling "sumologic-sumologic-otelcol-logs" not found
Provided HPA sumologic-sumologic-otelcol-logs not found.
```
Seems related, Isn't it?

**Comment by astencel-sumo** [comment]
Both tracesGateway and otelcolInstrumentation StatefulSets now have the option of autoscaling with an HPA.
