### ISSUE TITLE
Review and update Fluentd <-> OT comparison

### ISSUE THREAD

**Issue by sumo-drosiek** [SumoLogic/sumologic-kubernetes-collection#2480]
Review and update the following configuration: https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/e4ce5ce2cc846d394e81f6eaef987bda00c6687c/deploy/docs/fluentd_otc_comparison.md#sumologic-supported-fluentd-plugins

**Comment by sumo-drosiek** [comment]
Foe example `json_merge` can be achieved by combination of `json_logs.log_key`, `json_logs.flatten_body` and `log_format`

**Comment by sumo-drosiek** [comment]
Some configuration are no longer available in exporter (like source templates)

**Comment by astencel-sumo** [comment]
We don't have Fluentd anymore.
