### ISSUE TITLE
How can I use fluentd throttle filter plugin with the collector?

### ISSUE THREAD

**Issue by danpilch** [SumoLogic/sumologic-kubernetes-collection#2492]
I'd like to use https://docs.fluentbit.io/manual/pipeline/filters/throttle/ to throttle the logs sent to sumologic, is there a way to configure fluentd filters with this operator?

thanks

**Comment by sumo-drosiek** [comment]
Hi @danpilch 

This is fluent-bit plugin. Do you mean fluentd or fluent-bit?

**Comment by danpilch** [comment]
hi @sumo-drosiek sorry I got the two confused, I'm fairly new to these systems. It doesn't look like throttle is implemented in fluentd so I guess I mean fluent-bit - do you know if this is the best way to throttle logs from kubernetes -> sumologic?

**Comment by sumo-drosiek** [comment]
It sounds like reasonable solution. Throttling should be performed as close as possible to the source, so fluent-bit is a good choice. You can configure it by using `fluent-bit.config.filters`

**Comment by pdelewski** [comment]
@danpilch What's the status of this issue? Have you configured throttling?
