### ISSUE TITLE
Make it possible to connect to the node otel agent

### ISSUE THREAD

**Issue by danchia** [SumoLogic/sumologic-kubernetes-collection#2594]
**Is your feature request related to a problem? Please describe.**
I'm looking for a way for my otel exporter to talk to the node local otel agent, since by design the otel agent is a daemon that runs on every node.

However, I am unable to find a way to do so due to the current way the otel agent is deployed. Perhaps I have missed something.

**Describe the solution you'd like**
[k8s DaemonSet docs](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#communicating-with-daemon-pods) recommend using NodeIP and known port (via `hostPort`) to expose daemons to the pods on the same node. Ideally we could configure the otelagent DaemonSet to configure `hostPort` for the various ports.

**Describe alternatives you've considered**
Alternatively, I could send traffic to the otelagent service, but that is not guaranteed to be node local, which slightly defeats the purpose of running an agent on every node.

**Additional context**
n/a

**Comment by sumo-drosiek** [comment]
Hi @danchia is the issue still valid? What otelcol do you reference by `otelagent DaemonSet`?
Otelcol logs? https://github.com/SumoLogic/sumologic-kubernetes-collection/tree/b1b28ac2036e3c58a0031ef8fd233d5c556fac40/deploy/helm/sumologic/templates/logs/collector/otelcol
