### ISSUE TITLE
Provide information on using the pvc cleaner script

### ISSUE THREAD

**Issue by perk-sumo** [SumoLogic/sumologic-kubernetes-collection#2602]
Kubernetes cannot delete persistent volumes for statefulsets yet.
It's available as [alpha feature since 1.23 and should be available as beta since 1.26](https://github.com/kubernetes/enhancements/issues/1847)

This creates problems in EKS when new instance of the pod is created in different AZ than initial one as PVs cannot be mounted across different AZs.

Until that time we need troubleshooting on how to use the [pvc cleaner script](https://github.com/SumoLogic/sumologic-kubernetes-tools/tree/main/src/examples) updated to be used with OTC.

**Comment by sumo-drosiek** [comment]
Shouldn't we enable it by default?

**Comment by perk-sumo** [comment]
Good question Dominik!

BTW we'd need to update the RBAC API version as well.
