### ISSUE TITLE
Prometheus-Operator(Charts) comes with different record rules for K8S >= 1.14 which renders some dashboards inoperable

### ISSUE THREAD

**Issue by djsly** [SumoLogic/sumologic-kubernetes-collection#268]
For Example

When using K8S >= 1.14, the prometheus-operator charts only installs the following rules

https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/prometheus/rules-1.14/node.rules.yaml

compared to 

https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/prometheus/rules/node.rules.yaml

that is 27 missing rules just for the node...

The following remoteWrite entry contains lots of deprecated recordNames that are used in the different Kubernetes App Dashboards.

https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/master/deploy/helm/sumologic/values.yaml#L355

Note that AKS is about to support N-2 starting in December and that 1.14/1.15 will be 2 of the three supported versions.

https://github.com/Azure/AKS/issues/1235

**Comment by vsinghal13** [comment]
Closing this as it is resolved.
