### ISSUE TITLE
GKE pod logs are being prefixed with timestamp

### ISSUE THREAD

**Issue by rkcastelino** [SumoLogic/sumologic-kubernetes-collection#2703]
For some reason, timestamps are being added as a prefix to the log field for logs pulled from GKE pods. For example:
![Prefixed Log](https://user-images.githubusercontent.com/35676378/207699449-003581c9-1463-4999-8c98-4843830ddecb.PNG)

Oddly, when I check the logs manually via kubectl, the timestamp prefix isn't showing up. I've also verified that we're running the latest version of the helm chart (2.19.0) and the same behavior isn't seen for a similar workload running on EKS.

![Kubctl log check](https://user-images.githubusercontent.com/35676378/207699439-2ab8378e-6806-4d00-8571-cbe637a9bd12.PNG)
![Non-prefixed Log](https://user-images.githubusercontent.com/35676378/207699431-6ad7849f-dc07-4695-b7b7-961aa2f8ac27.PNG)

Has anyone seen this before and/or know what might be causing the different behavior?

**Comment by sumo-drosiek** [comment]
@rkcastelino Please look at [this document](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/docs/container-logs.md#configuration-for-containerd-log-format)

I assume you are using fluent-bit. Am I right?

**Comment by rkcastelino** [comment]
Ah, sorry just saw your response now and thanks for the link! Yes, we're using FluentBit so I'll try modifying the configs to see if that helps.

**Comment by rkcastelino** [comment]
This worked. Thank you for the help!

For anyone else seeing this issue, the link above looks to be broken but the same doc is available here (https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/docs/fluent/container-logs.md#configuration-for-containerd-log-format). GKE runs on the containerd runtime rather than docker so FluentBit's default settings don't work and need to be manually adjusted.
