### ISSUE TITLE
Usage of a deprecated Kubernetes component 'PodSecurityPolicy'

### ISSUE THREAD

**Issue by sidharth-lt** [SumoLogic/sumologic-kubernetes-collection#2729]
**Describe the bug**
I happen to use a single node microk8s flavour of kubernetes which operates on v1.25.4. The helm installation of sumologic (which I followed from _https://service.sumologic.com/ui/#/apps/app/<user-id>?displayContent=INTEGRATION_) contains a deprecated Kubernetes components 'PodSecurityPolicy'. This inturn doesnt let me do the helm install part and fails a lot before that. And there apparently aren't any CRD to enable PSP as well.

Downgrading the kubernetes versions should've helped but they didnt either. I get timed out when tried to install the helm packages 

**Logs**
```
Error: unable to build kubernetes objects from release manifest: [resource mapping not found for name: "my-release-kube-state-metrics" namespace: "" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
ensure CRDs are installed first, resource mapping not found for name: "my-release-prometheus-node-exporter" namespace: "my-namespace" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
ensure CRDs are installed first, resource mapping not found for name: "my-release-kube-prometheus-operator" namespace: "" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
ensure CRDs are installed first, resource mapping not found for name: "my-release-kube-prometheus-prometheus" namespace: "" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
```

**To Reproduce**
- Install helm or minikube (`snap install microk8s --classic` in the case of microk8s)
- helm add sumologic repositry
- helm install with access_key and access_id
  `microk8s helm3 upgrade --install my-release sumologic/sumologic   --namespace=my-namespace   --create-namespace   --set sumologic.accessId=suqMDOatpKxwMt   --set sumologic.accessKey=lSKFXRQjfQtVuYLwc30ABU4wCMslyvR7ok7OfCphUczCxpPKpBsdwiTTcJBqzn9Z   --set sumologic.clusterName=Kubernetes_cluster-2022-12-23T15:02:18.330Z   --set sumologic.collectorName=kubernetes-2022-12-23T15:02:18.330Z   --set "sumologic.setup.monitors.notificationEmails={linkinsid3398@gmail.com}"`
**Expected behavior**

**Environment:**
 - **Kubernetes version** (e.g. `kubectl version`): 1.25.4
 - **Cloud provider**: Azure VM instance 
 - **OS**: ubuntu

**Comment by astencel-sumo** [comment]
This is a valid issue and a duplicate of https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/1742, which was closed but shouldn't have been. I have reopened that issue and will close this as a duplicate. @sidharth-lt please track the original issue instead. 

Also see the current workaround to install the chart in a k8s v1.25 cluster: https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/1742#issuecomment-1272904626.

**Comment by astencel-sumo** [comment]
Let's reopen this and fix in v2.

**Comment by astencel-sumo** [comment]
See https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/1742#issuecomment-1370712106 for the outcome of the discussion.
