### ISSUE TITLE
Not able to receive logs in sumologic from EKS cluster after installing sumologic-kubernetes-collection

### ISSUE THREAD

**Issue by mynkkmr** [SumoLogic/sumologic-kubernetes-collection#2743]
I'm trying to set up sumo logic-Kubernetes-collection in my EKS cluster with fluentd only enabled. I was able to achieve this by overriding the parameters using the values.yaml file. After setting the fluentd pods and seeing the logs stating the worker is running. 

I assumed it would start sending logs to my sumo logic endpoints but after running the sumo queries I don't see any records coming to sumo. I tried running the debug steps as mentioned in the document https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/release-v2.19/deploy/docs/Troubleshoot_Collection.md#gathering-logs as well. They all passed successfully. Not sure what is wrong with my setup.

Attached is the log & pod running screenshot. Hope somebody from the sumolgic-kubernetes-collection team can help on this.

<img width="1371" alt="Screenshot 2023-01-02 at 10 10 13 PM" src="https://user-images.githubusercontent.com/4044226/210259056-380147b2-763a-4d73-a950-16defcf583c6.png">

**Comment by sumo-drosiek** [comment]
It would be helpful for us to have basic information about installation: https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/v2.19.1/deploy/docs/support.md

Fluentd seems to be fine. Do you see any issues in fluent-bit pod?

**Comment by mynkkmr** [comment]
I'm trying Non-helm installation. With version image set to **sumo logic/Kubernetes-tools:2.12.0**.

Do I need to install fluent-bit or any other component except for fluentd for it to work ?

 kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6", GitCommit:"f59f5c2fda36e4036b49ec027e556a15456108f0", GitTreeState:"clean", BuildDate:"2022-01-19T17:33:06Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.15-eks-fb459a0", GitCommit:"be82fa628e60d024275efaa239bfe53a9119c2d9", GitTreeState:"clean", BuildDate:"2022-10-24T20:33:23Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

values.yaml

sumologic:
  accessId: <ACCESS_ID>
  accessKey: <ACCESS_KEY>
  clusterName: <CLUSTER_NAME>
  events:
    enabled: false
  metrics:
    enabled: false
kube-prometheus-stack:
  enabled: false
fluent-bit:
  enabled: false
falco:
  enabled: false
fluentd:
  logLevel: debug
  logs:
    enabled: true
    statefulset:
      topologySpreadConstraints :
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway

**Comment by sumo-drosiek** [comment]
@mynkkmr 
Yes, you need to install Fluent Bit as well

1. Fluent Bit is taking logs from nodes and sends them to Fluentd
2. Fluentd is adding additional metadata to the logs and sends them to Sumo Logic

---

We highly recommend to use `helm` (or at least `helm template`) as from helm3 it doesn't do much more than simple `kubectl apply` and do not use helm tiller

**Comment by mynkkmr** [comment]
Thank you so much @sumo-drosiek 

Yes, It is working now I can see the log moving to sumo from the pod's logs of fluentd. But In the earlier version fluentd was taking care of fluent bit as well. can I know any specific reason for using a fluent bit for the logs?

**Comment by sumo-drosiek** [comment]
What earlier version do you have in mind?

`fluent-bit` has better performance and is able to read more logs using less resources, what is pretty important as it is run as DaemonSet. Fluentd is more powerful so we use it to enrich metadata, but it requires more resources per instance

**Comment by mynkkmr** [comment]
We were using

>  image sumologic/fluentd-kubernetes-sumologic:v2.4.2

 in our earlier version. Which is quite old. We haven't upgraded for a very long time.
