### ISSUE TITLE
Add daemonset annotations to otelcol daemonset

### ISSUE THREAD

**Issue by voidlily** [SumoLogic/sumologic-kubernetes-collection#2762]
**Is your feature request related to a problem? Please describe.**
My cluster has a security scanner that default denies insecure actions like running as root. Exceptions are marked by annotations on deployments/daemonsets. The [otelcol damonset](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/449ecb9dd2f0ff0d235baf734518d12b2f2c8ed8/deploy/helm/sumologic/templates/logs/collector/otelcol/daemonset.yaml) only supports annotations on the pods and not the daemonset itself.

**Describe the solution you'd like**
Add a helm value to put annotations on the otelcol daemonset.

**Describe alternatives you've considered**
We have a workaround to annotate the namespace to exempt the entire namespace, but it's not ideal.

**Additional context**

**Comment by swiatekm-sumo** [comment]
Yeah, we should definitely add this.

I'd like to point out that a better solution to this problem would be to not actually run otelcol as root by setting `otellogs.daemonset.securityContext` as per [this document](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/docs/security-best-practices.md#logs). This just needs to be a user with permission to read files in `/var/log/pods`, which unfortunately depends on your K8s distribution.
