### ISSUE TITLE
Allow customizing busybox image/tag in otelcol init container

### ISSUE THREAD

**Issue by voidlily** [SumoLogic/sumologic-kubernetes-collection#2763]
**Is your feature request related to a problem? Please describe.**
My cluster scans and prevents images from running with the `latest` tag. This includes init containers.

**Describe the solution you'd like**
Add customizable values for the [otelcol init container](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/a1f7ab1f801d2d724b27e07427d797257acb5849/deploy/helm/sumologic/templates/logs/collector/otelcol/daemonset.yaml#L109) to specify repository and tag for the busybox image.

**Describe alternatives you've considered**

**Additional context**

**Comment by swiatekm-sumo** [comment]
Thanks for the report. In principle, everything in the Chart should have a fixed version. The fact that busybox doesn't is definitely an oversight. Since we use busybox in a bunch of places, maybe we should just allow the image to be set via a single configuration option? WDYT @SumoLogic/open-source-collection-team

**Comment by sumo-drosiek** [comment]
@swiatekm-sumo agreee. if it won't be sufficient we can extend it in the future

**Comment by mat-rumian** [comment]
Currently we are forced to use static configuration for busybox becuase of [falco](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/v3.2.0/deploy/helm/sumologic/values.yaml#L4414). But I've moved to separated dictionary busybox configuration for otelcol logs daemonset - https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/2893 and set specific tags for both.
