### ISSUE TITLE
Document that in case of fluentd metadata, source configuration has to be changed

### ISSUE THREAD

**Issue by sumo-drosiek** [SumoLogic/sumologic-kubernetes-collection#2767]
Default source configuration: https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/v3.0.0-beta.1/deploy/helm/sumologic/values.yaml#L256-L265

is incompatible with Fluentd. We need to document it

**Comment by rnishtala-sumo** [comment]
Let's also document that if kube-state-metrics or any other pod/service that we pull metadata from crashloops, we will run into source naming issues.

**Comment by perk-sumo** [comment]
We need to check those potentially problematic cases:
* custom fluentd config in v2 -> copied over to OTC in v3
* defaults for v3 with OTC -> switching to Fluentd

**Comment by sumo-drosiek** [comment]
fluentd plugin related code: https://github.com/SumoLogic/sumologic-kubernetes-fluentd/blob/3a5a2e29e3776107a1bf0c9435de5cc2b14fc7f6/fluent-plugin-kubernetes-sumologic/lib/fluent/plugin/filter_kubernetes_sumologic.rb#L111-L118
