### ISSUE TITLE
Sumo helm chart deployment failing with "docker image pull backoff" error

### ISSUE THREAD

**Issue by ni3rpawar** [SumoLogic/sumologic-kubernetes-collection#2798]
**Describe the bug**
I am trying to deploy sumo helm chart for kubernetes setup, while deployment the job throwing error as added below.
I suspect this could be our network blocking image download. Would like to understand which hosts I need to whitelist in our network if thats the issue. Thanks 

**Logs**
Failed to pull image "public.ecr.aws/sumologic/kubernetes-setup:3.4.0": rpc error: code = Unknown desc = failed to pull and unpack image "public.ecr.aws/sumologic/kubernetes-setup:3.4.0": failed to resolve reference "public.ecr.aws/sumologic/kubernetes-setup:3.4.0": failed to do request: Head "https://public.ecr.aws/v2/sumologic/kubernetes-setup/manifests/3.4.0": EOF

**Command used to install/upgrade Collection**
helm upgrade --install my-release sumologic/sumologic --namespace=<our namespace name> -f values.yaml

**Configuration**
here is the values file

```sumologic:
  accessId: <access ID>
  accessKey: <access key>
  clusterName: <our cluster name>
kube-prometheus-stack:
  nodeExporter:
    enabled: false
  prometheusOperator:
    enabled: false
  prometheus-node-exporter:
    service:
      port: 9200
      targetPort: 9200
  prometheus:
    prometheusSpec:
      initContainers:
        - name: "init-config-reloader"
          env:
            - name: FLUENTD_METRICS_SVC
              valueFrom:
                configMapKeyRef:
                  name: sumologic-configmap
                  key: fluentdMetrics
            - name: NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: sumologic-configmap
                  key: fluentdNamespace

**Comment by sumo-drosiek** [comment]
Hi, the host should be `public.ecr.aws`, to include the following paths

- public.ecr.aws/sumologic/*
- public.ecr.aws/v2/sumologic/*
