### ISSUE TITLE
How to collect logs from files on Kubernetes nodes

### ISSUE THREAD

**Issue by astencel-sumo** [SumoLogic/sumologic-kubernetes-collection#2818]
Version: v3.0.0

This seems to be missing: https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/v3.0.0-rc.0/docs/best-practices.md#collect-logs-from-additional-files-on-the-node.

As a workaround, it's probably possible with `otellogs.config.merge`, but we need a proper, supported way of doing this.

**Comment by captainfalcon23** [comment]
Related to my recent issue: https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/3163

**Comment by astencel-sumo** [comment]
Here's the current documentation for this feature:
- chart v4: https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/v4.0.1/docs/best-practices.md#collect-logs-from-additional-files-on-the-node
- chart v3: https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/v3.16.2/docs/best-practices.md#collect-logs-from-additional-files-on-the-node
