### ISSUE TITLE
Document OOM in troubleshooting for Prometeheus 

### ISSUE THREAD

**Issue by sumo-drosiek** [SumoLogic/sumologic-kubernetes-collection#2877]
We do not provide documentation how to increase prometheus resources in case of OOM

**Comment by kkujawa-sumo** [comment]
Currently we have documentation which is not finished: https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/docs/troubleshoot-collection.md#out-of-memory-oom-failures-for-prometheus-pod

**Comment by sumo-drosiek** [comment]
Yes, the aim is to:
- finish was was started -> `:construction: Add link to Prometheus sharding doc here.`
- add information how to increase resources (now we only mention `and you are not able to increase them then `)

**Comment by astencel-sumo** [comment]
Advise to move from Prometheus to Otelcol
