### ISSUE TITLE
Kubernetes Collection fails in a FluxCD GitOps managed environment

### ISSUE THREAD

**Issue by cfallwell** [SumoLogic/sumologic-kubernetes-collection#2888]
**Describe the bug** 
Deploying the collection with Fluxcd and Kustomize fails in the FluxCD Helm Controller:

Warning  error   9m    helm-controller  Helm install failed: YAML parse error on sumologic/templates/setup/job.yaml: error converting YAML to JSON: yaml: line 49: did not find expected ',' or ']'

**Logs** Logs which can be helpful in investigating the issue.
The failure occurs before 'sumologic-sumologic-setup' pod creation

**Command used to install/upgrade Collection** Direct command which you used to install/upgrade collection.
N/A

**Configuration** Configuration used for Collection e.g. user-values.yaml for helm.
Configuration files are attached. 

**To Reproduce** Steps to reproduce the behavior.
Deploy k3s cluster with Fluxcd & Kustomize, add helm repo, configure external secrets, kustomize and helmrelease per attached.

**Expected behavior** A clear and concise description of what you expected to happen.
Helmrelease should deplou

**Environment (please complete the following information):**

- **Collection version** (e.g. `helm ls -n sumologic`): 3.x (tried with 3.0 through 3.20
- **Kubernetes version** (e.g. `kubectl version`):  v1.26.1+k3s1
- **Cloud provider**: NA
- **Others**:

**Anything else do we need to know** Add any other context about the problem here, e.g. issue happens only occasionally.

Bypassing helm management, by templating the deployment brings the error closer to the source:

var substitution failed for ‘sumologic-sumologic-setup’: YAMLToJSON: variable substitution failed: missing closing brace.  

[sumologic.zip](https://github.com/SumoLogic/sumologic-kubernetes-collection/files/10772113/sumologic.zip)

**Comment by astencel-sumo** [comment]
You have the `sumologic.envFromSecret` property wrong in the chart's values file. The value of the property is a string, not a list. You need to change this:

```yaml
      envFromSecret:
        - name: sumologic-secret
```

into this:

```yaml
      envFromSecret: sumologic-secret
```
