### ISSUE TITLE
Facilitating gitops for setup

### ISSUE THREAD

**Issue by matthewdaltonamount** [SumoLogic/sumologic-kubernetes-collection#293]
We utilize git ops for our Kubernetes deployments and for security reasons we do not want to hold our accessId and accessKey in git. To Facilitate this would it be possible to utilize envFrom in the setup charts to be able to source those secrets from a kubernetes native secret

**Comment by matthewdaltonamount** [comment]
https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/295

**Comment by MrColinJohnson** [comment]
👍
