### ISSUE TITLE
collection-setup job fails when collector already exists

### ISSUE THREAD

**Issue by dindurthy** [SumoLogic/sumologic-kubernetes-collection#2934]
**Describe the bug** A clear and concise description of what the bug is.
[This is the bug](https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/1645)

The issue is this [terraform import](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/dd18f40a7cdf87be919691b1e2d1e79c37b5f314/deploy/helm/sumologic/conf/setup/setup.sh#L125) will not succeed if a `/` is in the COLLECTOR_NAME. Terraform can import slashes, so I think it's just a scripting escape issue. Something like this might work

```
if terraform import sumologic_collector.collector "\'"${COLLECTOR_NAME}"\'"; then
```
or
```
if terraform import sumologic_collector.collector "\"${COLLECTOR_NAME}\""; then
```

**Logs** Logs which can be helpful in investigating the issue.

**Command used to install/upgrade Collection** Direct command which you used to install/upgrade collection.

**Configuration** Configuration used for Collection e.g. user-values.yaml for helm.

**To Reproduce** Steps to reproduce the behavior.
* Install the chart with a `\` in the collector name, e.g. `test/collector` and `setupEnabled: true`
* Make any update change and helm upgrade.

**Expected behavior** A clear and concise description of what you expected to happen.
The helm upgrade succeeds in importing the existing collector

**Environment (please complete the following information):**

- **Collection version** (e.g. `helm ls -n sumologic`):
- **Kubernetes version** (e.g. `kubectl version`):
- **Cloud provider**:
- **Others**:

**Anything else do we need to know** Add any other context about the problem here, e.g. issue happens only occasionally.

**Comment by kkujawa-sumo** [comment]
If you want to register collector with name `test/collector` you need to set following configuration:
```
sumologic:
  accessId: xxx
  accessKey: xxx
  clusterName: "test\\\\collector"
```
<img width="1234" alt="Screenshot 2023-07-04 at 11 50 32" src="https://github.com/SumoLogic/sumologic-kubernetes-collection/assets/73836361/990446c8-5060-4ba4-a110-b78d431f72b4">

 first escaping is for yaml/helm templates, the second escaping is for terraform

**Comment by dindurthy** [comment]
Ah, sorry, I forgot about this issue. Yeah, that isn't quite addressing my problem, although I could be missing it.

* The issue we see is with forwardslash (`/`), not backslash.
* The creation is not a problem. The issue is updates, because the setup job cannot import the existing resource. Here's the relevant log:

```
sumologic_field.statefulset[0]: Import prepared!
  Prepared sumologic_field for import
sumologic_field.statefulset[0]: Refreshing state... [id=0000000000D22DE0]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.

sumologic_collector.collector: Importing from ID "10x/redoxlocal-eks-cluster"...
sumologic_collector.collector: Import prepared!
  Prepared sumologic_collector for import
sumologic_collector.collector: Refreshing state... [id=10x/redoxlocal-eks-cluster]
╷
│ Error: collector with name '10x/redoxlocal-eks-cluster' does not exist
```
Although it _certainly_ does exist and creation errors later in the job:
```
2023-09-14T23:10:30.081Z [DEBUG] provider.terraform-provider-sumologic_v2.22.0: plugin address: address=/tmp/plugin1466527032 network=unix timestamp=2023-09-14T23:10:30.081Z
sumologic_collector.collector: Creating...
2023-09-14T23:10:30.657Z [DEBUG] provider.terraform-provider-sumologic_v2.22.0: 2023/09/14 23:10:30 [DEBUG] Request: [Method=POST] [URL=https://api.us2.sumologic.com/api/v1/collectors] [Headers=map[Authorization:[xxxxxxxxxxx] Content-Type:[application/json] User-Agent:[SumoLogicTerraformProvider/2.22.0]]]. Response: [StatusCode=400 Bad Request]
╷
│ Error: {
│   "status" : 400,
│   "id" : "TZSAX-XQ05W-6W9UP",
│   "code" : "collectors.validation.name.duplicate",
│   "message" : "A resource with the same name already exists."
│ }
│ 
│   with sumologic_collector.collector,
│   on resources.tf line 1, in resource "sumologic_collector" "collector":
│    1: resource "sumologic_collector" "collector" {
│ 
╵
2023-09-14T23:10:30.666Z [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2023-09-14T23:10:30.667Z [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
```

The import actually looks good now that I'm trying this again, so I'm maybe this is an issue with the provider.

**Comment by dindurthy** [comment]
Yeah, nm, I can see the issue locally just with minimal tf setup and creating a collector with a `/`
```
#main.tf
resource "sumologic_collector" "collector" {
  name        = "10x/redoxlocal-eks-cluster"
  description = "Just testing this"
  fields  = {
    environment = "production"
  }
}

provider "sumologic" {
    access_id   = "redacted"
    access_key  = "redacted"
    environment = "us2"
}

terraform {
    required_providers {
        sumologic = {
            source = "sumologic/sumologic"
        }
    }
    required_version = ">= 0.13"
}
```
and sure enough locally:
```
dharmarajindurthy@Dharmarajs-Laptop tf-sumo-collector % terraform import sumologic_collector.collector '10x/redoxlocal-eks-cluster'
sumologic_collector.collector: Importing from ID "10x/redoxlocal-eks-cluster"...
sumologic_collector.collector: Import prepared!
  Prepared sumologic_collector for import
sumologic_collector.collector: Refreshing state... [id=10x/redoxlocal-eks-cluster]
╷
│ Error: collector with name '10x/redoxlocal-eks-cluster' does not exist
│
│
╵
```

**Comment by dindurthy** [comment]
https://github.com/SumoLogic/terraform-provider-sumologic/issues/578
