### ISSUE TITLE
otel collector service fails if collector metrics are disabled

### ISSUE THREAD

**Issue by ib-ak** [SumoLogic/sumologic-kubernetes-collection#2947]
**Describe the bug** A clear and concise description of what the bug is.

otel collector service fails if collector is enabled but collector metrics are disabled

**Logs** Logs which can be helpful in investigating the issue.

```
Error: cannot patch "sumologic-sumologic-otelcol-logs-collector" with kind Service: Service "sumologic-sumologic-otelcol-logs-collector" is invalid: spec.ports: Required value
```

**Command used to install/upgrade Collection** Direct command which you used to install/upgrade collection.

**Configuration** Configuration used for Collection e.g. user-values.yaml for helm.
```
otellogs:
  metrics:
    enabled: false
```

**To Reproduce** Steps to reproduce the behavior.

deploy helm chart with enabled otel but disable otel  metrics

**Expected behavior** A clear and concise description of what you expected to happen.

it should deploy with no errors.

**Environment (please complete the following information):**

- **Collection version** (e.g. `helm ls -n sumologic`): 3.3.0
- **Kubernetes version** (e.g. `kubectl version`): 1.24
- **Cloud provider**: aws
- **Others**:

**Anything else do we need to know** Add any other context about the problem here, e.g. issue happens only occasionally.

https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/070d6109042ae9e7e3a52fceadc979b88b9af845/deploy/helm/sumologic/templates/logs/collector/otelcol/service.yaml#L1-L17

if .Values.otellogs.metrics.enabled  == false , ports becomes empty.

**Comment by kkujawa-sumo** [comment]
@ib-ak fix for this issue is merged now and it will be available in next release.
