### ISSUE TITLE
Add a separate ServiceAccount for Pods which don't need any RBAC

### ISSUE THREAD

**Issue by swiatekm-sumo** [SumoLogic/sumologic-kubernetes-collection#2986]
Right now we use the same ServiceAccount for (almost) everything. This is convenient, as it lets us have a single pullSecrets attached to it, among other benefits. However, it's also bound to Roles which only the metadata components need. We should have separate ServiceAccounts for these usecases, so we don't give unnecessary RBAC permissions to every Pod.

**Comment by kkujawa-sumo** [comment]
One ServiceAccount is used for metadata enrichment (otelcol/fluentd) & tracing, another one for otelcol-logs-collector
The list of ServiceAccounts when Helm Chart is deployed in default configuration:

```yaml
$ kubectl get ServiceAccount -n sumologic
NAME                                          SECRETS   AGE
default                                       1         45h
collection-kube-prometheus-prometheus         1         17h
collection-sumologic                          1         17h
collection-sumologic-otelcol-logs-collector   1         17h
collection-kube-state-metrics                 1         17h
collection-prometheus-node-exporter           1         17h
collection-kube-prometheus-operator           1         17h
```

**Comment by swiatekm-sumo** [comment]
After reviewing, what we have right now is mostly ok. Different components could use slightly trimmed down RBAC, but the differences aren't that big. Closing for now.
