### ISSUE TITLE
Component label for otelcol-instrumentation-component too long (exceeds 63 characters)

### ISSUE THREAD

**Issue by kristinnSnow** [SumoLogic/sumologic-kubernetes-collection#3019]
**Describe the bug** A clear and concise description of what the bug is.

I am trying to install the helm chart with the release name `managment-sumologic`, this results in an error during installation where I'm unable to install the stateful set for the otel collector with the following error:

```
StatefulSet.apps "management-sumologic-sumologic-otelcol-instrumentation" is invalid: metadata.labels: Invalid value: "management-sumologic-sumologic-otelcol-instrumentation-component": must be no more than 63 characters
```

- **Collection version** (e.g. `helm ls -n sumologic`): v3.0.0
- **Kubernetes version** (e.g. `kubectl version`): v1.25.6
- **Cloud provider**: Azure

**Anything else do we need to know** Add any other context about the problem here, e.g. issue happens only occasionally.

Easiest solution would be to truncate the label value to 63 characters, alternatively shorten the value by removing the redundant `-component` or as a last resort by limiting the release name length.

**Comment by swiatekm-sumo** [comment]
Thanks for the report. Honestly, we should have a comprehensive test for this edge case, which is thankfully easy to do with terratest.

**Comment by swiatekm-sumo** [comment]
Unfortunately, we can't actually fix this without a breaking change. This is described in more detail in #3057, but this limit depends on your configuration in practice, so we'd be breaking working configurations if we enforced it at the top level.

For now, #3057 adds a warning, and we'll properly fix it in v4. The workaround is to use a shorter release name until then. Up to you if you want to close this issue and watch #3057, or leave it as is until that one is resolved.

**Comment by kristinnSnow** [comment]
I understand, for now I've added a fullname override to shorten the name, a change to the release name would have also fixed this but this was a better solution for us.

**Comment by aboguszewski-sumo** [comment]
As of `v4` we truncate the chart name if it's longer than 22 characters. I believe this can be closed.
