### ISSUE TITLE
OTEL charts doesn't allow namespace override & inherits default helm namespace

### ISSUE THREAD

**Issue by rupeshnemade** [SumoLogic/sumologic-kubernetes-collection#3026]
Currently Sumo helm charts uses namespace from which Argo or helm is executed. There is no option to override our own namespace so that we can install all OTEL resources in completely different namespace than that of default helm/Argo namespace.
e.g. https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/deploy/helm/sumologic/templates/logs/otelcol/statefulset.yaml#L5

Can you please add ability to pass 'namespaceOverride' from values.yaml like other public helm charts allows?

Example https://github.com/prometheus-community/helm-charts/blob/kube-prometheus-stack-12.10.0/charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml#L6

**Comment by swiatekm-sumo** [comment]
You can set the target namespace in Argo: https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#declarative, and you can also set the namespace for helm via a command-line option. My understanding is that there are some tools (like Spinnaker) where this is a problem, but ArgoCD and Helm itself are not among them.

**Comment by rupeshnemade** [comment]
Yes we can set target namespace in Argo & also in Helm but our use case is single Argo app for setup in 2 different namespace. For this scenario we need namespaceOverride as mentioning target namespace or helm namespace installs OTEL chart in same namespace as Argo's which we don't want.

**Comment by rupeshnemade** [comment]
@astencel-sumo Can you confirm probable release date for this enhancement ?

**Comment by swiatekm-sumo** [comment]
I'm still not clear on what you want to happen, exactly. It sounds like you want some specific resources (the OTEL ones) to be installed in a different namespace than the release namespace, but the setting you linked to in `kube-prometheus-stack` applies to *all* resources. If you set `namespaceOverride` in their values.yaml, it's the same as passing `--namespace` to Helm. Is that want you need our Chart to do?

**Comment by rupeshnemade** [comment]
@swiatekm-sumo As discussed its not the case that we need to install few resources in one namespace & rest in other. Instead we want all OTEL chart resources in same namespace but we want control over what that namespace will be and 'namespaceOverride' can help here.

**Comment by swiatekm-sumo** [comment]
That sounds reasonable. We don't currently have room for this feature on our roadmap, but if you'd like to contribute, we'd welcome it.

**Comment by rupeshnemade** [comment]
@swiatekm-sumo I have raised a PR https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/3068.
Please review & let me know in case of any issues.
