### ISSUE TITLE
helm install fails on prometheus-operator

### ISSUE THREAD

**Issue by strangeminds** [SumoLogic/sumologic-kubernetes-collection#305]
`helm install sumologic/sumologic` is failing on prometheus-operator.  Following the install instructions to install the collector via helm when no prometheus is installed.  I run into this error 

`Error: apiVersion "monitoring.coreos.com/v1" in sumologic/charts/prometheus-operator/templates/prometheus/rules/kubernetes-system.yaml is not available`

```
helm install sumologic/sumologic --name collection --namespace sumologic --set sumologic.endpoint=https://api.us2.sumologic.com/api/v1/ --set sumologic.accessId=XXXXXXXXXX --set sumologic.accessKey=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx --set prometheus-operator.prometheus.prometheusSpec.externalLabels.cluster="my-cluster" --set sumologic.clusterName="my-cluster"
Error: apiVersion "monitoring.coreos.com/v1" in sumologic/charts/prometheus-operator/templates/prometheus/rules/kubernetes-system.yaml is not available
``` 

https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/master/deploy/docs/Installation_with_Helm.md#installation-steps

Helm fails to create CRDs for Prometheus.  The workaround is in the prometheus-operator helm Chart here.

https://github.com/helm/charts/tree/master/stable/prometheus-operator#helm-fails-to-create-crds

```
kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/master/example/prometheus-operator-crd/alertmanager.crd.yaml
kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/master/example/prometheus-operator-crd/prometheus.crd.yaml
kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/master/example/prometheus-operator-crd/prometheusrule.crd.yaml
kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/master/example/prometheus-operator-crd/servicemonitor.crd.yaml
kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/master/example/prometheus-operator-crd/podmonitor.crd.yaml
```

**Comment by rvmiller89** [comment]
Hi @strangeminds  can you provide the output to the following:
```
$ kubectl version
$ helm version
```

**Comment by strangeminds** [comment]
> Hi @strangeminds can you provide the output to the following:
> 
> ```
> $ kubectl version
> $ helm version
> ```

```
kubectl version --short
Client Version: v1.16.3
Server Version: v1.15.6
```

```
helm version
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

**Comment by rvmiller89** [comment]
@strangeminds  we do not yet have support for Helm v3, our currently tested support matrix is at https://github.com/SumoLogic/sumologic-kubernetes-collection/tree/master/deploy#support-matrix

I'm fine leaving this issue open until we have verified support for Helm v3

**Comment by frankreno** [comment]
Helm3 is now supported, closing this issue
