### ISSUE TITLE
Adding capability in Kafka exporter to dynamically fetch the brokers list

### ISSUE THREAD

**Issue by rupeshnemade** [SumoLogic/sumologic-kubernetes-collection#3058]
While using OTEL kafka exporter for forwarding logs to kafka endpoints Kafka exporter allows us to provide a list of brokers in its settings as mentioned [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/kafkaexporter).

With change in k8s clusters our kafka broker endpoints will keep changing. OTEL doesn't allow us to provide dynamic config as their is no operator support for this.

Can we add feature in Kafka exporter to fetch list of brokers dynamically or better way from clusters k8s secrets like below?
`    broker:
      valueFrom:
        secretKeyRef:
          key: brokers
          name: kafka-endpoints`

**Comment by dmolenda-sumo** [comment]
Thank you for your enhancement request. We appreciate your feedback and will discuss this topic internally.

**Comment by rupeshnemade** [comment]
@swiatekm-sumo @perk  If we go with below approach then it will solve our issue -
1. Use k8s ExtrenalSecrets to configure kafka exporter config where ExtrenalSecrets will populate kafka broker values in config dynamically by reading them from AWS Secret manager.
2. Mount the secret generated in step 1 on OTEL agent pod.
3. Instruct OTEL agent to consider extra kafka config by passing extra args as below- 
      `        args:
          - --config=/etc/otel/config.yaml
          - --config=/etc/otel/kafka-config.yaml`

We see issue in step 3, as current helm chart has fixed path to read config [here](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/deploy/helm/sumologic/templates/logs/otelcol/statefulset.yaml#L115)

Can you add capability to pass extra args like we pass extra volume mounts from values.yaml?

**Comment by swiatekm-sumo** [comment]
Adding the ability to override `args` seems like a good solution to this problem. It also has other uses, like setting feature flags.

**Comment by rupeshnemade** [comment]
@swiatekm-sumo Great that will help. Let us know when this can be rolled out.

**Comment by perk-sumo** [comment]
Hey @rupeshnemade that is not on our roadmap yet unfortunately - so not dates yet.

**Comment by rupeshnemade** [comment]
@swiatekm-sumo @perk-sumo I have raised a PR [#3076](https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/3076)
Can you please review & let me know if this can be planned for release?
