### ISSUE TITLE
Bump kube-prometheus-stack dependency

### ISSUE THREAD

**Issue by kristinnSnow** [SumoLogic/sumologic-kubernetes-collection#3089]
**Is your feature request related to a problem? Please describe.**
I would like to be able to add additional arguments to the prometheus instance, support for this was added in version 41.1.0 of kube-prometheus-stack. https://github.com/prometheus-community/helm-charts/pull/2482

**Describe the solution you'd like**
Upgrade the kube-prometheus-stack chart dependency to at least 41.1.0.

**Comment by kkujawa-sumo** [comment]
We cannot easily update kube-prometheus-stack due to incompatibility on OpenShift platforms with Prometheus Operator which is installed there by default(for sure this incompatibility exists on OpenShift 4.10).

What arguments do you want to add to prometheus instance? Maybe we will be able to solve the problem in different way 🤔

**Comment by kristinnSnow** [comment]
I would like to use the flag `scrape.discovery-reload-interval`, I have a lot of service monitors which leads to high CPU usage, I want to use the flag to increase the interval between reloads.

I have already tested this and saw a huge difference in CPU usage.

**Comment by kkujawa-sumo** [comment]
At this moment we can propose you installation of `kube-prometheus-stack` separately but with the configuration that works with our collection, please see this guide https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/docs/best-practices.md#using-newer-kube-prometheus-stack

**Comment by kristinnSnow** [comment]
Closing this since the new version of the helm chart does not include `kube-prometheus-stack` anymore.
