### ISSUE TITLE
Add ability to strip common pod metric labels

### ISSUE THREAD

**Issue by icco** [SumoLogic/sumologic-kubernetes-collection#3090]
**Is your feature request related to a problem? Please describe.** 

The number of labels on metrics coming from default pod level metrics make it so I can't use the metrics for things like SLOs, and also increase our bill. 

**Describe the solution you'd like** 

A label deny-list for pod metrics, or just metrics that come through the collector.

**Describe alternatives you've considered** 

I looked through the config and couldn't figure out if this is something already featured. Also, I know in the next version metric processing is changing, which we'll be switching to when it launches, so if it's supported in that, happy to wait till v4.

**Additional context** 

We use terraform to apply our config. Our current config is as follows:

```
# https://github.com/SumoLogic/sumologic-kubernetes-collection/releases
resource "helm_release" "sumo_logic" {
  name             = "sumologic"
  repository       = "https://sumologic.github.io/sumologic-kubernetes-collection"
  namespace        = "sumologic"
  create_namespace = true
  chart            = "sumologic"
  version          = "3.9.0"
  timeout          = 3000

  set {
    name  = "sumologic.accessId"
    value = var.SUMOLOGIC_ACCESSID
  }

  set {
    name  = "sumologic.accessKey"
    value = var.SUMOLOGIC_ACCESSKEY
  }

  set {
    name  = "sumologic.clusterName"
    value = var.cluster_name
  }

  set {
    name  = "sumologic.collectorName"
    value = "kubernetes-${var.cluster_name}"
  }

  set {
    name  = "sumologic.logs.container.sourceCategoryPrefix"
    value = "k8s/${var.cluster_name}/"
  }

  set {
    name  = "falco.enabled"
    value = "true"
  }

  set {
    name  = "sumologic.logs.container.format"
    value = "fields"
  }

  set {
    name  = "metadata.logs.autoscaling.enabled"
    value = "true"
  }

  set {
    name  = "metadata.metrics.autoscaling.enabled"
    value = "true"
  }

  set {
    name  = "kube-prometheus-stack.kubeApiServer.serviceMonitor.interval"
    value = "60s"
  }

  set {
    name  = "metadata.persistence.storageClass"
    value = "gp2-new"
  }

  set {
    name  = "sumologic.events.persistence.persistentVolume.storageClass"
    value = "gp2-new"
  }

  depends_on = [
    kubernetes_config_map_v1_data.aws_auth,
    module.external-dns,
    module.alb-controller,
    module.karpenter,
    module.secrets_store_csi,
    module.ebs-csi-driver-addon
  ]
}
```

**Comment by kkujawa-sumo** [comment]
Metrics can be modified through changes in configuration for otelcol metrics, 
please see this guide: https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/docs/collecting-application-metrics.md#metrics-modifications

Using [transformprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor) you can add, rename, or delete metadata, please see this example: https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/docs/collecting-application-metrics.md#adding-or-renaming-metadata

You can also configure what metrics are sent to sumo making changes in [Prometheus remote write configuration](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/ca67ae6a29f3385a86c3bb23d8683952f5a3ac86/deploy/helm/sumologic/values.yaml#L2140-L3498)
