### ISSUE TITLE
Error: timed out waiting for the condition

### ISSUE THREAD

**Issue by kamlesh32147** [SumoLogic/sumologic-kubernetes-collection#3116]
I checked the pod logs ,it is giving me error that credentials unauthorized
"sumologic_collector.collector: Creating...
2023-06-30T03:57:51.294Z [DEBUG] provider.terraform-provider-sumologic_v2.24.0: 2023/06/30 03:57:51 [DEBUG] Request: [Method=POST] [URL=https://api.sumologic.com/api/v1/collectors] [Headers=map[Authorization:[xxxxxxxxxxx] Content-Type:[application/json] User-Agent:[SumoLogicTerraformProvider/2.24.0]]]. Response: [StatusCode=401 Unauthorized]
╷
│ Error: {
│   "status" : 401,
│   "id" : "CARV8-GWQGO-44DGK",
│   "code" : "unauthorized",
│   "message" : "Credential could not be verified."
│ }
│
│   with sumologic_collector.collector,
│   on resources.tf line 1, in resource "sumologic_collector" "collector":
│    1: resource "sumologic_collector" "collector" {
│
╵
2023-06-30T03:57:51.299Z [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2023-06-30T03:57:51.300Z [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2023-06-30T03:57:51.301Z [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/sumologic/sumologic/2.24.0/linux_amd64/terraform-provider-sumologic_v2.24.0 pid=189
2023-06-30T03:57:51.301Z [DEBUG] provider: plugin exited
2023-06-30T03:57:51.302Z [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/kubernetes/2.21.1/linux_amd64/terraform-provider-kubernetes_v2.21.1_x5 pid=180
2023-06-30T03:57:51.302Z [DEBUG] provider: plugin exited
Error during applying Terraform changes
"

**Comment by kamlesh32147** [comment]
> I checked the pod logs ,it is giving me error that credentials unauthorized "sumologic_collector.collector: Creating... 2023-06-30T03:57:51.294Z [DEBUG] provider.terraform-provider-sumologic_v2.24.0: 2023/06/30 03:57:51 [DEBUG] Request: [Method=POST] [URL=https://api.sumologic.com/api/v1/collectors] [Headers=map[Authorization:[xxxxxxxxxxx] Content-Type:[application/json] User-Agent:[SumoLogicTerraformProvider/2.24.0]]]. Response: [StatusCode=401 Unauthorized] ╷ │ Error: { │ "status" : 401, │ "id" : "CARV8-GWQGO-44DGK", │ "code" : "unauthorized", │ "message" : "Credential could not be verified." │ } │ │ with sumologic_collector.collector, │ on resources.tf line 1, in resource "sumologic_collector" "collector": │ 1: resource "sumologic_collector" "collector" { │ ╵ 2023-06-30T03:57:51.299Z [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF" 2023-06-30T03:57:51.300Z [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF" 2023-06-30T03:57:51.301Z [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/sumologic/sumologic/2.24.0/linux_amd64/terraform-provider-sumologic_v2.24.0 pid=189 2023-06-30T03:57:51.301Z [DEBUG] provider: plugin exited 2023-06-30T03:57:51.302Z [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/kubernetes/2.21.1/linux_amd64/terraform-provider-kubernetes_v2.21.1_x5 pid=180 2023-06-30T03:57:51.302Z [DEBUG] provider: plugin exited Error during applying Terraform changes "

i checked the creds its fine.

also getting this error in pod
{
  "id": "JYCC2-FEBP0-APGG1",
  "errors": [
    {
      "code": "unauthorized",
      "message": "Credential could not be verified."
    }
  ]
}
null
Failed requesting fields API:
{"id":"JYCC2-FEBP0-APGG1","errors":[{"code":"unauthorized","message":"Credential could not be verified."}]}
Couldn't automatically create fields
You do not have enough field capacity to create the required fields automatically.
Please refer to https://help.sumologic.com/docs/manage/fields/ to manually create the fields after you have removed unused fields to free up capacity.
sumologic_collector.collector: Importing from ID "test"...
sumologic_collector.collector: Import prepared!
  Prepared sumologic_collector for import
sumologic_collector.collector: Refreshing state... [id=test]
╷
│ Error: {
│   "status" : 401,
│   "id" : "WJPEB-44N50-GA7S3",
│   "code" : "unauthorized",
│   "message" : "Credential could not be verified."
│ }

**Comment by kkujawa-sumo** [comment]
@kamlesh32147 Do you still observe this issue?

**Comment by edwlarkey** [comment]
We were running into the same issue. We found that all of our access keys had been disabled by Sumo. We enabled the keys we needed and it started working.

It seems that auto deactivating keys is a new feature added on 2023-06-20 https://help.sumologic.com/release-notes-service/2023/06/20/manage-account/

**Comment by sumo-drosiek** [comment]
@edwlarkey Thank you for the response. We also figured out that the issue was related to deactivated access keys.
