### ISSUE TITLE
Switch from Prometheus to OpenTelemetry Collector for default metrics collection

### ISSUE THREAD

**Issue by perk-sumo** [SumoLogic/sumologic-kubernetes-collection#3152]
- [x] Change the default settings
- [x] Add migration documentation
- [x] Update normal documentation to make clear recording rules don't work under Otel
- [x] Update architecture image in the README

**Comment by swiatekm-sumo** [comment]
Default settings were changed in #3284

**Comment by swiatekm-sumo** [comment]
README diagrams were updated in #3261

**Comment by swiatekm-sumo** [comment]
Migration documentation completed in https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/3302
