### ISSUE TITLE
kube-system services time-out waiting for te pods to direct traffic

### ISSUE THREAD

**Issue by fbarrerafalabella** [SumoLogic/sumologic-kubernetes-collection#3187]
I am installing sumologic-kubernetes-collection in a separate namespace called sumologic, the service comes up and i can see the metrics and everything (or I think so) on the sumologic console, I am installing it following the documentation in the page of quickstart
```
helm upgrade --install my-release sumologic/sumologic \
--namespace=my-namespace \
--create-namespace \
--set sumologic.accessId=SUMO_ACCESS_ID \
--set sumologic.accessKey=SUMO_ACCESS_KEY \
--set sumologic.clusterName=Kubernetes_cluster \
--set sumologic.collectorName=kubernetes \
--set sumologic.setup.monitors.enabled=false
```
but when all is up and ready there are 3 componentes that never finishes, those are this 3 services created on the kube-system namespace for any reason
kube-system/liniopay-sumologic-kube-pr-kube-scheduler
kube-system/liniopay-sumologic-kube-pr-kube-etcd
kube-system/liniopay-sumologic-kube-pr-kube-controller-manager

all of them show the same message whith is the following
```
the Kubernetes API server reported that "kube-system/liniopay-sumologic-kube-pr-kube-controller-manager" failed to fully initialize or become live: 'liniopay-sumologic-kube-pr-kube-controller-manager' timed out waiting to be Ready
    	* Service does not target any Pods. Selected Pods may not be ready, or field '.spec.selector' may not match labels on any Pods
``` 
I tried to describe 1 of them but I dont see any strange behaviour on the events
```
kubectl describe service -n kube-system liniopay-sumologic-kube-pr-kube-controller-manager
Name:              liniopay-sumologic-kube-pr-kube-controller-manager
Namespace:         kube-system
Labels:            app=kube-prometheus-stack-kube-controller-manager
                   app.kubernetes.io/instance=liniopay-sumologic
                   app.kubernetes.io/managed-by=pulumi
                   app.kubernetes.io/part-of=kube-prometheus-stack
                   app.kubernetes.io/version=40.5.0
                   chart=kube-prometheus-stack-40.5.0
                   heritage=Helm
                   jobLabel=kube-controller-manager
                   release=liniopay-sumologic
Annotations:       <none>
Selector:          component=kube-controller-manager
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                None
IPs:               None
Port:              http-metrics  10257/TCP
TargetPort:        10257/TCP
Endpoints:         <none>
Session Affinity:  None
Events:            <none>
```

I got the same begaviour using 3.11.0 and 3.7.0 version, I am using kuberntes 1.24
**Describe the bug** A clear and concise description of what the bug is.

**Environment (please complete the following information):**

- **Collection version** (e.g. `helm ls -n sumologic`): 3.7.0 using helm 3
- **Kubernetes version** (e.g. `kubectl version`): v1.24.15-eks-a5565ad
- **Cloud provider**: AWS

**Comment by swiatekm-sumo** [comment]
Where exactly do you see this message? These are Services exposing metrics ports for control plane components, so it is indeed true that they don't target any Pods.

**Comment by sumo-drosiek** [comment]
Please reopen if the issue is still valid
