### ISSUE TITLE
DPM ingestion rate

### ISSUE THREAD

**Issue by strangeminds** [SumoLogic/sumologic-kubernetes-collection#32]
How can you slow down the DPM ingestion rate?

We ran the one line deploy and our ingestion rate jumped 15,000 overnight.

https://github.com/SumoLogic/sumologic-kubernetes-collection/tree/master/deploy

**Comment by bin3377** [comment]
Thanks for the reporting!
This repo is in an early preview status so any configurations are subjected to be changed. 

The DPM is actually depends on the Prometheus settings. Please check `scrape_interval`/`evaluation_interval`  in the [configuration](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config)
