### ISSUE TITLE
fluentd-logs multi node group collection

### ISSUE THREAD

**Issue by alex-staroselsky-vizio** [SumoLogic/sumologic-kubernetes-collection#3217]
For sumologic-kubernetes-collection version 2.19.x  being installed into a cluster with multiple node groups, sumologic being in its own node group while the target applications being in a different node group, is it possible to have fluentd collect logs metrics in other node groups?

Would this require [daemonset](https://github.com/fluent/fluentd-kubernetes-daemonset/tree/master) to be running an configured in every node/node-group? Is this concept of multi node group infrastructure log collection easier with sumologic-kubernetes-collection 3.x.x?

2.19.x values:
- https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/release-v2.19/deploy/helm/sumologic/README.md

**Comment by swiatekm-sumo** [comment]
Logs are indeed collected using a DaemonSet, and so you do need that running on every Node. Everything else, you can restrict to a specific Node group. This log collector is either Fluent Bit or OpenTelemetry Collector depending on configuration - the former is default in v2, while the latter is default in v3.

I don't think this is any easier in v3, though v3 does let you run different log collectors for different Node groups, if that's what you need. Is there anything specific we could do to make your life easier with this setup?

**Comment by alex-staroselsky-vizio** [comment]
It actually ended up being easier in 3.x using [otellogs.additionalDaemonSets](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/release-v3.12/docs/best-practices.md#setting-different-resources-on-different-nodes-for-logs-collector). I was able to specify a nodeSelector where the target deployments/pods were running.

Is there an equivalent property in sumologic-kubernetes-collection version 2.x where this equivalent additionalDaemonsets can be specified?

**Comment by swiatekm-sumo** [comment]
There isn't such a property in 2.x, unfortunately.

**Comment by alex-staroselsky-vizio** [comment]
Thank you for clarifying. Will focus on upgrading to meet our needs.
