### ISSUE TITLE
Is it recommended to use otel to collect eks(containerd) logs, currently using fluentbit

### ISSUE THREAD

**Issue by txjjjjj** [SumoLogic/sumologic-kubernetes-collection#3239]
We currently use fluentbit to capture logs on eks node `/var/log/containers` . It uses the multi-line processing feature.

Fluentd to report.

I would like to migrate to otel. Do you have any recommendations for documentation.

**Comment by sumo-drosiek** [comment]
Yes, multiline documentation for OpenTelemetry is in [docs/collecting-container-logs.md](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/6f3792955abb7b6df0584afd1a6652c016f33f5e/docs/collecting-container-logs.md#multiline-log-parsing)

**Comment by txjjjjj** [comment]
@sumo-drosiek Thanks for the reply. I was wondering if otel can handle containerd type logs, which have the F P flag, it's the configuration in this link https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/docs/fluent/ container-logs.md#using-new-multiline-parser-fluent-bit-v18

**Comment by sumo-drosiek** [comment]
> I was wondering if otel can handle containerd type logs, which have the F P flag,

Yes, we automatically parse all three formats (crio, containerd and docker): https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/8964ea5fa285dc3304983eb85226d319143535ee/deploy/helm/sumologic/conf/logs/collector/otelcol/config.yaml#L66-L74

**Comment by prysmakou-sa** [comment]
I'm facing with inability to filter the JSONed logs after we migrated to otel. Going to create a separate issue.
