### ISSUE TITLE
Could you please guide me on exporting Sumo logs from an EKS cluster to S3 while applying specific filters to send only the desired logs?

### ISSUE THREAD

**Issue by mynkkmr** [SumoLogic/sumologic-kubernetes-collection#3259]
In the context of managing an Amazon Elastic Kubernetes Service (EKS) cluster and utilizing Sumo Logic for log management, I'm seeking guidance on a specific task. I'm looking to set up a process to export logs from the Sumo Logic platform to an Amazon S3 bucket. However, I want to apply filtering criteria to ensure that only specific logs are sent to the S3 bucket.

More precisely, I'd like to understand the steps and configurations required to achieve this log export functionality. This involves setting up filters or rules within Sumo Logic to select only the logs that meet specific criteria and then directing these filtered logs to be exported to an S3 bucket.

To provide more context, here's a ConfigMap (collection-sumologic-fluentd-logs) snippet that I've been working with:

<match containers.**>
  @type copy
  <store>
    @type sumologic
    @id sumologic.endpoint.logs
    sumo_client "k8s_3.13.0"
    @log_level error
    @include logs.output.conf
    **@type s3
    log_level info
    s3_bucket <s3bucket-name>
    s3_region <AWS_region>
    path logs/
    timekey 3600 # 1-hour partition
    timekey_wait 10m
    timekey_use_utc true # use UTC
    chunk_limit_size 256m
    utc
    <format>
      @type json
    </format>
    <filter>
      @type parser
      format json
      key_name msg
      reserve_data true
    </filter>**
    <buffer>
      @type file
      path /fluentd/buffer/logs.containers
      @include buffer.output.conf
    </buffer>
  </store>
</match>
</label>

While applying the Configmap I'm able to send the logs to the s3 bucket but not able to filter it. when I try to set the filter in the same configuration I get the following warnings
"
2023-09-11 10:47:29 +0000 [warn]: fluent/log.rb:383:warn: section <filter> is not used in <store> of s3 plugin
2023-09-11 10:47:29 +0000 [warn]: fluent/log.rb:383:warn: section <filter> is not used in <store> of s3 plugin
2023-09-11 10:47:29 +0000 [warn]: fluent/log.rb:383:warn: section <filter> is not used in <store> of s3 plugin
2023-09-11 10:47:29 +0000 [warn]: fluent/log.rb:383:warn: section <filter> is not used in <store> of s3 plugin
2023-09-11 10:47:29 +0000 [info]: #0 fluent/log.rb:362:info: starting fluentd worker pid=19 ppid=7 worker=0
"
I'm seeking a comprehensive explanation or guide outlining the necessary procedures and configurations involved in this process, especially considering the provided ConfigMap snippet. Your insights and expertise in this matter would be greatly appreciated."

**Comment by sumo-drosiek** [comment]
Please reopen if the issue is still valid
