### ISSUE TITLE
Having issues deploying to GKE - Falco fails

### ISSUE THREAD

**Issue by chelapa** [SumoLogic/sumologic-kubernetes-collection#332]
Installing the latest release of sumologic helm chart, it deploys the sources and pods but fails when trying falco.

kubernetes version: 1.14.7-gke.23
helm: v2.14.3

not sure what other info is needed to help 

Runtime error: error opening device /host/dev/falco0. Make sure you have root credentials and that the falco-probe module is loaded.. Exiting.

* Trying to download precompiled module from https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/falco-probe-0.17.1-x86_64-4.14.138%2B-3ed0774cb82bc5c7f3b6f5190c3b82ef.ko

Download failed, consider compiling your own falco-probe and loading it or getting in touch with the sysdig community

**Comment by emcay** [comment]
Im having this issue, but on EKS.

k8s: v1.14.9-eks-c0eccc

App version: 0.10.0

```
Trying to download precompiled module from https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/falco-probe-0.17.1-x86_64-4.14.154-128.181.amzn2.x86_64-2a1b4e38248e08669f1ed37604b3ad74.ko
curl: (22) The requested URL returned error: 404 Not Found

```

**Comment by vsinghal13** [comment]
Have you tried this solution? Seems to have worked.  https://github.com/falcosecurity/falco/issues/624

**Comment by Colbize** [comment]
had same issues, containers were stuck in restarting phase.
K8s: "v1.14.9-eks-c0eccc"

Solution was follow the installation in -> https://falco.org/docs/installation/
on our amz2 linux worker nodes:
`
rpm --import https://s3.amazonaws.com/download.draios.com/DRAIOS-GPG-KEY.public
curl -s -o /etc/yum.repos.d/draios.repo https://s3.amazonaws.com/download.draios.com/stable/rpm/draios.repo
yum -y install kernel-devel-$(uname -r)
yum -y install falco
`

**Comment by daroga0002** [comment]
> Have you tried this solution? Seems to have worked. [falcosecurity/falco#624](https://github.com/falcosecurity/falco/issues/624)

this solution is problematic in case when you use EKS node groups where you are restricted to AWS AMIs to which you cannot pass any additional parameters.

**Comment by vsinghal13** [comment]
@daroga0002 have you tried using v `0.18.0` of falco on EKS 1.14 as other versions do not seem to have the precompiled kernel modules. ?

**Comment by daroga0002** [comment]
yes, even tried to bump version to 0.19 and 0.20 from https://github.com/falcosecurity/falco/releases

**Comment by frankreno** [comment]
@chelapa @emcay @Colbize @daroga0002 - Please see #687 with a workaround. This has been tested in EKS and should work in other environments.
