### ISSUE TITLE
Missing kubelet metrics in AKS

### ISSUE THREAD

**Issue by njparisi** [SumoLogic/sumologic-kubernetes-collection#334]
Per [this guide](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/master/deploy/docs/Troubleshoot_Collection.md#missing-kubelet-metrics) option 2 works when modifying the service monitor. However, using http vs https in insecure and need the ability to allow Prometheus to scrape these endpoints using https.

**Comment by frankreno** [comment]
Recent releases of AKS have resolved this issue.  Closing this out.
