### ISSUE TITLE
Error: timed out waiting for the condition

### ISSUE THREAD

**Issue by kartheekakkur** [SumoLogic/sumologic-kubernetes-collection#338]
When running the below command ran into an issue, where it is timing out with the error
Error: timed out waiting for the condition

helm install sumologic/sumologic --name collection --namespace sumologic --set sumologic.endpoint=https://api.us2.sumologic.com/api/v1/ --set sumologic.accessId=xxxxxxx--set sumologic.accessKey=xxxxxx--set prometheus-operator.prometheus.prometheusSpec.externalLabels.cluster="xxxxx" --set sumologic.clusterName="xxxx-sumo" --no-crd-hook

**Comment by rvmiller89** [comment]
Hi @kartheekakkur  did you mean to set cluster name the same in both 
`--set sumologic.clusterName="xxxx-sumo"` and
`--set prometheus-operator.prometheus.prometheusSpec.externalLabels.cluster="xxxxx"`
(should be `xxxx-sumo`?)

Can you check the pods running in the cluster in the sumologic namespace with
`kubectl get pods -n sumologic`
and provide logs for the collection-setup pod with `kubectl logs <collection-setup-pod>` ?

**Comment by kartheekakkur** [comment]
tested it without xxx-sumo but still got the same error, so I switched it.

here are the requested details


[vasu@usau-cops-cent7 ~]$ kubectl get pods -n sumologic
NAME                               READY   STATUS    RESTARTS   AGE
collection-sumologic-setup-4vc27   1/2     Running   0          53m



[vasu@usau-cops-cent7 ~]$ helm version
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}


[vasu@usau-cops-cent7 ~]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-eks-b8860f", GitCommit:"b8860f6c40640897e52c143f1b9f011a503d6e46", GitTreeState:"clean", BuildDate:"2019-11-25T00:55:38Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

**Comment by rvmiller89** [comment]
Can you provide the output to the following:
`kubectl logs collection-sumologic-setup-4vc27`

**Comment by kartheekakkur** [comment]
Error from server (NotFound): pods "collection-sumologic-setup-4vc27" not found

**Comment by rvmiller89** [comment]
I wonder if enough time elapsed the pod was removed? Could you try to fetch the logs from the setup pod while it is still in `Running` state?

**Comment by kartheekakkur** [comment]
deleted and reran but still the same


NAME                               READY   STATUS    RESTARTS   AGE
collection-sumologic-setup-8pm65   2/2     Running   0          17s


Error from server (NotFound): pods "collection-sumologic-setup-8pm65" not foun

**Comment by kartheekakkur** [comment]
kubectl describe pods -n sumologic collection-sumologic-setup-8pm65
Name:           collection-sumologic-setup-8pm65
Namespace:      sumologic
Priority:       0
Node:           ip-172-16-131-104.ec2.internal/172.16.131.104
Start Time:     Thu, 12 Dec 2019 13:06:04 -0600
Labels:         controller-uid=71ddc7a4-1d12-11ea-804a-02a7d91590f5
                job-name=collection-sumologic-setup
Annotations:    kubernetes.io/psp: eks.privileged
                sidecar.istio.io/status:
                  {"version":"2696c96840179bdcd8f86ed60a643396f0cb250f56458b46a7fc667e6c75ef7f","initContainers":["istio-init"],"containers":["istio-proxy"]...
Status:         Running
IP:             172.16.136.157
IPs:            <none>
Controlled By:  Job/collection-sumologic-setup
Init Containers:
  istio-init:
    Container ID:  docker://5843e42526140d1bc202bdf95438578c23bcc85fd1961056f96cc49e9cd15ecf
    Image:         docker.io/istio/proxy_init:1.3.3
    Image ID:      docker-pullable://istio/proxy_init@sha256:9b6c40ef8e5ff220a67b9cac6e5d9a8ad885a92fbcbbd02936dfb668a06ea409
    Port:          <none>
    Host Port:     <none>
    Args:
      -p
      15001
      -z
      15006
      -u
      1337
      -m
      REDIRECT
      -i
      *
      -x

      -b
      *
      -d
      15020
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 12 Dec 2019 13:06:05 -0600
      Finished:     Thu, 12 Dec 2019 13:06:06 -0600
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  50Mi
    Requests:
      cpu:        10m
      memory:     10Mi
    Environment:  <none>
    Mounts:       <none>
Containers:
  setup:
    Container ID:  docker://2804071aee9651552c346786be24b0ba16630bf0654e4c0486275570467882f5
    Image:         sumologic/kubernetes-fluentd:0.12.0
    Image ID:      docker-pullable://sumologic/kubernetes-fluentd@sha256:1c1876f28f8171502d95847a4cb248d679c6be010b916df8377984df45e43bfd
    Port:          <none>
    Host Port:     <none>
    Command:
      /etc/terraform/setup.sh
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 12 Dec 2019 13:06:35 -0600
      Finished:     Thu, 12 Dec 2019 13:07:08 -0600
    Ready:          False
    Restart Count:  1
    Environment:
      SUMOLOGIC_ACCESSID:   suZpeevOGw1pBx
      SUMOLOGIC_ACCESSKEY:  bWMu8vReenFa41e9SlSjosIiUViUjXeGARJbU3XIzG1BjRcefbWencuEVSEEuT9z
      SUMOLOGIC_BASE_URL:   https://api.us2.sumologic.com/api/v1/
    Mounts:
      /etc/terraform from setup (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from collection-sumologic-setup-token-r4jvm (ro)
  istio-proxy:
    Container ID:  docker://6bf704ea2745c75e2a8cb3751089c5d358683bea8e1fd4af4a08202203206917
    Image:         docker.io/istio/proxyv2:1.3.3
    Image ID:      docker-pullable://istio/proxyv2@sha256:ba3471a9749893afe80f7d8f11119bf0148ffe0f4eaf3f9da66bb27076a8c2a6
    Port:          15090/TCP
    Host Port:     0/TCP
    Args:
      proxy
      sidecar
      --domain
      $(POD_NAMESPACE).svc.cluster.local
      --configPath
      /etc/istio/proxy
      --binaryPath
      /usr/local/bin/envoy
      --serviceCluster
      collection-sumologic-setup.sumologic
      --drainDuration
      45s
      --parentShutdownDuration
      1m0s
      --discoveryAddress
      istio-pilot.istio-system:15010
      --zipkinAddress
      zipkin.istio-system:9411
      --dnsRefreshRate
      300s
      --connectTimeout
      10s
      --proxyAdminPort
      15000
      --concurrency
      2
      --controlPlaneAuthPolicy
      NONE
      --statusPort
      15020
      --applicationPorts

    State:          Running
      Started:      Thu, 12 Dec 2019 13:06:07 -0600
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  1Gi
    Requests:
      cpu:      100m
      memory:   128Mi
    Readiness:  http-get http://:15020/healthz/ready delay=1s timeout=1s period=2s #success=1 #failure=30
    Environment:
      POD_NAME:                          collection-sumologic-setup-8pm65 (v1:metadata.name)
      ISTIO_META_POD_PORTS:              [
                                         ]
      ISTIO_META_CLUSTER_ID:             Kubernetes
      POD_NAMESPACE:                     sumologic (v1:metadata.namespace)
      INSTANCE_IP:                        (v1:status.podIP)
      SERVICE_ACCOUNT:                    (v1:spec.serviceAccountName)
      ISTIO_META_POD_NAME:               collection-sumologic-setup-8pm65 (v1:metadata.name)
      ISTIO_META_CONFIG_NAMESPACE:       sumologic (v1:metadata.namespace)
      SDS_ENABLED:                       false
      ISTIO_META_INTERCEPTION_MODE:      REDIRECT
      ISTIO_META_INCLUDE_INBOUND_PORTS:
      ISTIO_METAJSON_ANNOTATIONS:        {"kubernetes.io/psp":"eks.privileged"}

      ISTIO_METAJSON_LABELS:             {"controller-uid":"71ddc7a4-1d12-11ea-804a-02a7d91590f5","job-name":"collection-sumologic-setup"}

      ISTIO_META_WORKLOAD_NAME:          collection-sumologic-setup
      ISTIO_META_OWNER:                  kubernetes://api/batch/v1/namespaces/sumologic/jobs/collection-sumologic-setup
    Mounts:
      /etc/certs/ from istio-certs (ro)
      /etc/istio/proxy from istio-envoy (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from collection-sumologic-setup-token-r4jvm (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  setup:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      collection-sumologic-setup
    Optional:  false
  collection-sumologic-setup-token-r4jvm:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  collection-sumologic-setup-token-r4jvm
    Optional:    false
  istio-envoy:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  istio-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istio.collection-sumologic-setup
    Optional:    true
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age                   From                                     Message
  ----    ------     ----                  ----                                     -------
  Normal  Scheduled  7m8s                  default-scheduler                        Successfully assigned sumologic/collection-sumologic-setup-8pm65 to ip-172-16-131-104.ec2.internal
  Normal  Pulled     7m7s                  kubelet, ip-172-16-131-104.ec2.internal  Container image "docker.io/istio/proxy_init:1.3.3" already present on machine
  Normal  Created    7m7s                  kubelet, ip-172-16-131-104.ec2.internal  Created container istio-init
  Normal  Started    7m7s                  kubelet, ip-172-16-131-104.ec2.internal  Started container istio-init
  Normal  Pulled     7m6s                  kubelet, ip-172-16-131-104.ec2.internal  Container image "docker.io/istio/proxyv2:1.3.3" already present on machine
  Normal  Created    7m6s                  kubelet, ip-172-16-131-104.ec2.internal  Created container istio-proxy
  Normal  Started    7m5s                  kubelet, ip-172-16-131-104.ec2.internal  Started container istio-proxy
  Normal  Pulled     6m37s (x2 over 7m6s)  kubelet, ip-172-16-131-104.ec2.internal  Container image "sumologic/kubernetes-fluentd:0.12.0" already present on machine
  Normal  Created    6m37s (x2 over 7m6s)  kubelet, ip-172-16-131-104.ec2.internal  Created container setup
  Normal  Started    6m37s (x2 over 7m6s)  kubelet, ip-172-16-131-104.ec2.internal  Started container setup
[vasu@usau-cops-cent7 ~]$

**Comment by vakkur** [comment]
did anyone encounter this issue?

**Comment by grohan2002** [comment]
+1

**Comment by grohan2002** [comment]
My Logs are as follows -
Initializing the backend...

Initializing provider plugins...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.kubernetes: version = "~> 1.9"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
sumologic_collector.collector: Importing from ID "smedaksprod"...
sumologic_collector.collector: Import prepared!
  Prepared sumologic_collector for import
sumologic_collector.collector: Refreshing state... [id=smedaksprod]

Error: collector with name 'smedaksprod' does not exist


sumologic_http_source.default_metrics_source: Importing from ID "smedaksprod/(default-metrics)"...

Error: collector with name 'smedaksprod' does not exist


sumologic_http_source.apiserver_metrics_source: Importing from ID "smedaksprod/apiserver-metrics"...

Error: collector with name 'smedaksprod' does not exist


sumologic_http_source.events_source: Importing from ID "smedaksprod/events"...

Error: collector with name 'smedaksprod' does not exist


sumologic_http_source.kube_controller_manager_metrics_source: Importing from ID "smedaksprod/kube-controller-manager-metrics"...

Error: collector with name 'smedaksprod' does not exist


sumologic_http_source.kube_scheduler_metrics_source: Importing from ID "smedaksprod/kube-scheduler-metrics"...

Error: collector with name 'smedaksprod' does not exist


sumologic_http_source.kube_state_metrics_source: Importing from ID "smedaksprod/kube-state-metrics"...

Error: collector with name 'smedaksprod' does not exist


sumologic_http_source.kubelet_metrics_source: Importing from ID "smedaksprod/kubelet-metrics"...

Error: collector with name 'smedaksprod' does not exist


sumologic_http_source.logs_source: Importing from ID "smedaksprod/logs"...

Error: collector with name 'smedaksprod' does not exist


sumologic_http_source.node_exporter_metrics_source: Importing from ID "smedaksprod/node-exporter-metrics"...

Error: collector with name 'smedaksprod' does not exist


kubernetes_namespace.sumologic_collection_namespace: Importing from ID "sumologic"...
kubernetes_namespace.sumologic_collection_namespace: Import prepared!
  Prepared kubernetes_namespace for import
kubernetes_namespace.sumologic_collection_namespace: Refreshing state... [id=sumologic]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.

kubernetes_secret.sumologic_collection_secret: Importing from ID "sumologic/sumologic"...
kubernetes_secret.sumologic_collection_secret: Import prepared!
  Prepared kubernetes_secret for import
kubernetes_secret.sumologic_collection_secret: Refreshing state... [id=sumologic/sumologic]

Error: Cannot import non-existent remote object

While attempting to import an existing object to
kubernetes_secret.sumologic_collection_secret, the provider detected that no
object exists with the given id. Only pre-existing objects can be imported;
check that the id is correct and that it is associated with the provider's
configured region or endpoint, or use "terraform apply" to create a new remote
object for this resource.

kubernetes_namespace.sumologic_collection_namespace: Refreshing state... [id=sumologic]
sumologic_collector.collector: Creating...

Error: <!DOCTYPE html>

**Comment by rvmiller89** [comment]
@grohan2002  does the log cut off after that, even after waiting 10+ minutes?
```
kubernetes_namespace.sumologic_collection_namespace: Refreshing state... [id=sumologic]
sumologic_collector.collector: Creating...

Error:
```

Seems there should be more to the log about what failed.

**Comment by grohan2002** [comment]
@rvmiller89 

╰─$ kubectl logs collection-sumologic-setup-jv8j4 -n sumologic                                                                                                                                              1 ↵

Initializing the backend...

Initializing provider plugins...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.kubernetes: version = "~> 1.9"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
sumologic_collector.collector: Importing from ID "smedaksprod"...
sumologic_collector.collector: Import prepared!
  Prepared sumologic_collector for import
sumologic_collector.collector: Refreshing state... [id=smedaksprod]

Error: collector with name 'smedaksprod' does not exist


sumologic_http_source.default_metrics_source: Importing from ID "smedaksprod/(default-metrics)"...

Error: collector with name 'smedaksprod' does not exist


sumologic_http_source.apiserver_metrics_source: Importing from ID "smedaksprod/apiserver-metrics"...

Error: collector with name 'smedaksprod' does not exist


sumologic_http_source.events_source: Importing from ID "smedaksprod/events"...

Error: collector with name 'smedaksprod' does not exist


sumologic_http_source.kube_controller_manager_metrics_source: Importing from ID "smedaksprod/kube-controller-manager-metrics"...

Error: collector with name 'smedaksprod' does not exist


sumologic_http_source.kube_scheduler_metrics_source: Importing from ID "smedaksprod/kube-scheduler-metrics"...

Error: collector with name 'smedaksprod' does not exist


sumologic_http_source.kube_state_metrics_source: Importing from ID "smedaksprod/kube-state-metrics"...

Error: collector with name 'smedaksprod' does not exist


sumologic_http_source.kubelet_metrics_source: Importing from ID "smedaksprod/kubelet-metrics"...

Error: collector with name 'smedaksprod' does not exist


sumologic_http_source.logs_source: Importing from ID "smedaksprod/logs"...

Error: collector with name 'smedaksprod' does not exist


sumologic_http_source.node_exporter_metrics_source: Importing from ID "smedaksprod/node-exporter-metrics"...

Error: collector with name 'smedaksprod' does not exist


kubernetes_namespace.sumologic_collection_namespace: Importing from ID "sumologic"...
kubernetes_namespace.sumologic_collection_namespace: Import prepared!
  Prepared kubernetes_namespace for import
kubernetes_namespace.sumologic_collection_namespace: Refreshing state... [id=sumologic]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.

kubernetes_secret.sumologic_collection_secret: Importing from ID "sumologic/sumologic"...
kubernetes_secret.sumologic_collection_secret: Import prepared!
  Prepared kubernetes_secret for import
kubernetes_secret.sumologic_collection_secret: Refreshing state... [id=sumologic/sumologic]

Error: Cannot import non-existent remote object

While attempting to import an existing object to
kubernetes_secret.sumologic_collection_secret, the provider detected that no
object exists with the given id. Only pre-existing objects can be imported;
check that the id is correct and that it is associated with the provider's
configured region or endpoint, or use "terraform apply" to create a new remote
object for this resource.

kubernetes_namespace.sumologic_collection_namespace: Refreshing state... [id=sumologic]
sumologic_collector.collector: Creating...

Error: <!DOCTYPE html>





<html lang="en"> 
<html>



<head>
  <meta charset="utf-8"/>
  <meta HTTP-EQUIV="REFRESH" content="10; url=/ui">
  <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>

  <meta http-equiv="cache-control" content="no-cache" />
  <meta http-equiv="Pragma" content="no-cache" />
  <meta http-equiv="Expires" content="-1" />

  <title>Sumo Logic</title>

  
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>

<style type="text/css">
  @font-face {
    font-family: "LabGrotesque-Light";
    src: url("./ui/font/LabGrotesque-Light.woff") format("woff");
  }

  @font-face {
    font-family: "LabGrotesque-Bold";
    src: url("./ui/font/LabGrotesque-Bold.woff") format("woff");
  }

  @font-face {
    font-family: "LabGrotesque-Regular";
    src: url("./ui/font/LabGrotesque-Regular.woff") format("woff");
  }

  html,body {
    height: 100%;
    width: 100%;
    margin: 0;
    padding: 0;
  }

  #wrapper {
    background: #FFFFFF;
    display: flex;
    flex-direction: column;
    justify-content: space-between;
    align-items: center;
    width: 100%;
    height: 100%;
  }

  #logo {
    padding-top: 36px;
    padding-left: 36px;
    align-self: flex-start;
  }

  #content {
    display: flex;
    flex-direction: column;
    width: 100%;
    height: 100%;
    align-items: center;
    padding-top: 10%;
  }

  #content .content-header {
    padding-top: 24px;
    font-family: 'LabGrotesque-Bold';
    font-size: 36px;
    color: #000000;
    text-align: center;
    line-height: 50px;
  }

  #content .content-body {
    padding-top: 12px;
    font-family: 'LabGrotesque-Light';
    font-size: 20px;
    color: #64696C;
    text-align: center;
    line-height: 25px;
    flex: 1;
  }

  #copyright {
    padding-bottom: 12px;
    color: #8C9296;
    font-family: 'LabGrotesque-Regular';
    font-size: 12px;
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
  }

  #copyright .link {
    text-decoration: none;
    color: #8C9296;
  }
</style>

</head>

<body>

<div id="wrapper">
  <div id="logo">
    <?xml version="1.0" encoding="utf-8"?>
    
    <svg width="240px" height="32px" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
      viewBox="0 0 577 107.3" style="enable-background:new 0 0 577 107.3;" xml:space="preserve">
    <style type="text/css">
      .st0{fill:#000099;}
    </style>
    <title>Asset 1</title>
    <g id="Layer_2_1_">
      <g id="Layer_1-2">
        <path class="st0" d="M118.3,23.8v60.4h-14.1v-6.4C101,83,95.1,86,86.5,86c-14.3,0-21.4-7.4-21.4-19.2V23.8h15.4v38.9
          c0,6.3,3.4,10,10,10c7.7,0,12.4-4.4,12.4-12.5V23.8H118.3z M218.3,42v42.2h-15.4V46.6c0-7.2-2.9-11.6-9.6-11.6s-10.6,5-10.6,12
          v37.2h-15.4V46.6c0-7.7-3.2-11.6-9.6-11.6c-6.8,0-10.6,5-10.6,12v37.2h-15.4V23.8h14.3v6.7c3.5-5.8,9.3-8.7,17.2-8.7
          c7.7,0,13.5,3.2,16.8,8.9c4.1-5.9,10.2-8.9,18.1-8.9C211,21.8,218.3,29.5,218.3,42L218.3,42z M341.9,84.2h-15.4V0.2h15.4V84.2z
          M508.9,84.2h-15.4V23.8h15.4L508.9,84.2z M493.2,14.7h15.9V0h-15.9V14.7z M566.6,63.6c-6.3,6.7-10.6,9.3-16.4,9.3
          c-6.9,0-11.8-4-14-10.2V45.1c2.3-6.3,7.2-10.3,14.2-10.3c5.1,0,9.2,1.8,15.7,7.9l9.6-9.5c-7.7-8.4-15.2-11.5-25.3-11.5
          c-14.1,0-25,7.4-29.3,19.8v24.8C525.3,78.7,536,86,550,86c10.9,0,18.4-3.6,26.8-14L566.6,63.6z M31.7,47c-4.2-0.9-7.2-1.7-8.9-2.1
          c-2.1-0.6-3.7-1.4-4.5-2.5v-4.6c1.4-2.2,4.8-3.6,9.5-3.6c6.5,0,11,1.5,18.1,7.1l8.3-10c-8.4-7-15.6-9.5-26-9.5
          c-12,0-20.3,4.9-23.6,11.9v15.2c2.6,5.1,8.6,8,20.6,10.6c4.3,1,7.2,1.7,8.9,2c2.2,0.7,4.2,1.6,5.3,3.2v5.3
          c-1.5,2.4-5.1,3.7-9.8,3.7c-3.4,0.1-6.7-0.6-9.8-1.9c-3-1.2-6.5-3.5-10.9-7.1L0,74.6C9.6,83.1,17.7,86,29.2,86
          c12.3,0,21-4.7,24.3-12.2V58.5C50.7,52.8,44,49.8,31.7,47z M258.7,21.7c-13.9,0-24.8,7.5-29.3,19.5v25.4
          c4.4,12,15.4,19.5,29.3,19.5c13.9,0,24.7-7.5,29.1-19.4V41.1C283.3,29.2,272.4,21.7,258.7,21.7L258.7,21.7z M272.9,62.8
          c-2.4,6.4-7.5,10.2-14.3,10.2c-6.7,0-12-3.8-14.4-10.2V45c2.4-6.4,7.5-10.3,14.4-10.3c6.8,0,11.8,3.9,14.2,10.3L272.9,62.8z
          M383.1,21.7c-13.9,0-24.8,7.5-29.3,19.5v25.4c4.5,12,15.4,19.5,29.3,19.5s24.7-7.5,29.1-19.4V41.1
          C407.8,29.2,396.9,21.7,383.1,21.7z M397.3,62.8c-2.4,6.4-7.5,10.2-14.2,10.2s-12-3.8-14.4-10.2V45c2.4-6.4,7.5-10.3,14.4-10.3
          s11.8,3.9,14.2,10.3V62.8z M465.8,23.8v6.7c-3.9-5.8-10-8.7-18.4-8.7c-11.4,0-20.6,7-24.6,18.1v24.9c3.9,11.1,13.1,18,24.6,18
          c7.7,0,13.5-2.6,17.6-7.7v4.8c0,10-5.8,14.7-14.8,14.7c-6.7,0-12.2-2-21-7.2l-7.5,11.1c8.5,5.7,18.5,8.8,28.7,8.9
          c17,0,29.5-9.1,29.5-26.1V23.8H465.8z M463.9,60.5c-2.3,5.7-7.1,9.3-13.1,9.3s-10.8-3.5-13.1-9.3V44c2.3-5.7,7-9.2,13.1-9.2
          s10.8,3.5,13.1,9.2V60.5z"/>
      </g>
    </g>
    </svg>
  </div>
  <div id="content">
    <div class="error-icon">
      <?xml version="1.0" encoding="UTF-8"?>
      <svg width="74px" height="57px" viewBox="0 0 74 57" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
          
          <title>icon-apps-2-color copy</title>
          <desc>Created with Sketch.</desc>
          <g id="Organisms" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
              <g id="Table:-States" transform="translate(-631.000000, -3504.000000)">
                  <g id="icon-apps-2-color-copy" transform="translate(632.000000, 3497.000000)">
                      <rect id="bounding-box_icon" x="0" y="0" width="72" height="72"></rect>
                      <rect id="stroke" fill="#0046BE" x="1.95890411" y="17.7534247" width="68.0684932" height="1.97260274"></rect>
                      <rect id="stroke" fill="#0046BE" x="22.6849315" y="9.8630137" width="1.97260274" height="7.89041096"></rect>
                      <polygon id="Fill" fill="#0046BE" points="16.7671233 15.2089041 19.7260274 15.2089041 19.7260274 12.25 16.7671233 12.25"></polygon>
                      <polygon id="Fill" fill="#0046BE" points="10.8356164 15.2089041 13.7945205 15.2089041 13.7945205 12.25 10.8356164 12.25"></polygon>
                      <polygon id="Fill" fill="#0046BE" points="4.91780822 15.2089041 7.87671233 15.2089041 7.87671233 12.25 4.91780822 12.25"></polygon>
                      <rect id="baseline" fill="#0046BE" x="7.89041096" y="61.1506849" width="56.2191781" height="1.97260274"></rect>
                      <polygon id="baseline-copy" fill="#21B9CC" transform="translate(36.562500, 40.125670) rotate(-45.000000) translate(-36.562500, -40.125670) " points="19.1249999 39.0006697 53.9999999 39.0006697 53.9999999 41.2506697 19.1249999 41.2506697"></polygon>
                      <polygon id="baseline-copy-2" fill="#21B9CC" transform="translate(36.562500, 40.125670) scale(-1, 1) rotate(-45.000000) translate(-36.562500, -40.125670) " points="19.1250001 39.0006697 54.0000001 39.0006697 54.0000001 41.2506697 19.1250001 41.2506697"></polygon>
                      <polyline id="stroke" stroke="#0046BE" stroke-width="2" stroke-linecap="square" points="3.57975861 62.1369863 0.98630137 62.1369863 0.98630137 8.87671233 71.009647 8.87671233 71.0136986 62.1369863 68.4161897 62.1369863"></polyline>
                  </g>
              </g>
          </g>
      </svg>
    </div>
    <div class="content-header">Page not found</div>
    <div class="content-body">
      We couldn't find the page you were looking for. It might not exist anymore, or there might be an error in the URL.
    </div>
  </div>
  <div id="copyright">
    <span>Copyright 2010-<script>document.write(new Date().getFullYear())</script> Sumo Logic, Inc. |&nbsp;</span>
    <span><a class="link" target="_blank" href="https://www.sumologic.com/privacy/">Privacy Policy</a> |&nbsp;</span>
    <span><a class="link" target="_blank" href="https://www.sumologic.com/terms-conditions/">Terms &amp; Conditions</a></span>
  </div>
</div>

</body>
</html>


  on sumo-k8s.tf line 29, in resource "sumologic_collector" "collector":
  29: resource "sumologic_collector" "collector" {

**Comment by grohan2002** [comment]
@rvmiller89  I am trying to set it up for AKS cluster. I have an existing prometheus cluster running hence setting up a parallel one dedicated for Sumologic. 
Command used -
```helm install sumologic/sumologic --name collection --namespace sumologic --set sumologic.endpoint=https://service.in.sumologic.com --set sumologic.accessId=suErdIi4WIwhpo --set sumologic.accessKey=SlNabIjVTet5YWrUTvBPbs5l2cPZSaelewNkvui3QbGyVH5VFdWGblBrKfyOoLpx --set prometheus-operator.prometheus.prometheusSpec.externalLabels.cluster="smedaksprod" --set sumologic.clusterName="smedaksprod" --set prometheus-operator.prometheus-node-exporter.service.port=9200 --set prometheus-operator.prometheus-node-exporter.service.targetPort=9200 --no-crd-hook```

**Comment by rvmiller89** [comment]
Okay you will definitely want to revoke access to your Access Id/key now that it has been compromised online.

`--set sumologic.endpoint=https://service.in.sumologic.com` is incorrect.  Instead you should use the API endpoint listed on https://help.sumologic.com/APIs/General-API-Information/Sumo-Logic-Endpoints-and-Firewall-Security

so it should be `--set sumologic.endpoint=https://api.in.sumologic.com/api/v1/`

**Comment by grohan2002** [comment]
@rvmiller89 It is a trial account, i will anyways delete it once i am able to set it up. :)

**Comment by grohan2002** [comment]
@rvmiller89 thank you it worked.

**Comment by vsinghal13** [comment]
@kartheekakkur is this resolved for you? If yes, can we close the issue?

**Comment by vakkur** [comment]
@vsinghal13 you can close it, it is resolved
