### ISSUE TITLE
How to rotate Sumo keys?

### ISSUE THREAD

**Issue by pablokbs** [SumoLogic/sumologic-kubernetes-collection#3395]
Per the recent [security issue](https://www.sumologic.com/security-response-center/), we need to rotate our keys. There is a [secret that has the keys](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/ff59b51b02e68f6f58afcbb5ba5eb685dca53296/deploy/helm/sumologic/README.md?plain=1#L138), but when I rotate the keys inside it, it seems like the collectors don't pick them up. I did some digging and I've found that there is some kind of setup that uses those keys to populate the pods and the configs.

How can I rotate these keys? Do I need to re-trigger the setup? How do I do that?

Thanks!

**Comment by swiatekm-sumo** [comment]
The short answer is that you simply need to use new credentials during your next Helm Chart upgrade, and make sure to delete your old credentials in the Sumo UI.

The Helm Chart only uses the keys to do some setup during installation and upgrades. The keys are only present in your cluster briefly, and the Secret containing them is deleted once it's not necessary anymore. This is done via the [Helm hook](https://helm.sh/docs/topics/charts_hooks/) mechanism.

**Comment by swiatekm-sumo** [comment]
I'm going to pin this issue for more visibility, as it's likely more users will want the same question answered in the near future.

**Comment by pablokbs** [comment]
Can you explain a little bit how to do this?

> use new credentials during your next Helm Chart upgrade

If I already have my chart installed, which command do I need to run? Maybe we should write a quick step-by-step guide :)

**Comment by swiatekm-sumo** [comment]
> If I already have my chart installed, which command do I need to run?

You don't need to do anything with the Chart you already have installed. When you next upgrade it, you'll need credentials to do it, and that's when you use your newly generated ones.

If you store your credentials in a secret store like AWS SSM or Hashicorp vault and inject them at runtime, then just rotate them in that store. No further action is needed.

I'll update my original comment with a more detailed account of what needs to be done.

**Comment by pablokbs** [comment]
Right, you keep saying "next upgrade" but I don't want to upgrade. I want to just rotate the keys. If I'm understanding the process correctly, I think what I need to do is to run the following command, with the same version I'm using. Right?

`helm upgrade --install my-release sumologic/sumologic -f `user-values.yaml` --version=2.0.0` 

[docs](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/docs/installation.md#upgrading-sumo-logic-collection)

**Comment by Shadowssong** [comment]
Just want to echo the sentiment that it is extremely confusing to understand how rotating our access keys affects our helm install.  When debugging the sumo helm chart I found it to be one of the most confusing helm charts (jobs calling custom images, calling shell scripts, running helm templated terraform code to create k8s resources ????).  I forced a sync from Argo (how we manage the sumo helm install), which seemed to have triggered the setup jobs but it didn't automatically cycle any pods so I did that manually as well.  From there I did not see any log loss after deactivating the old key.

**Comment by swiatekm-sumo** [comment]
I've updated my original comment for maximum clarity on this issue. Quoting it below as well. Let me know if you have any other questions or concerns.

> **Deactivating the credentials in Sumo is sufficient. No action involving the Helm Chart is necessary.**
> 
> More detailed answer provided below.
