### ISSUE TITLE
kubelet https fix, command should be updated

### ISSUE THREAD

**Issue by alexbklein91** [SumoLogic/sumologic-kubernetes-collection#342]
In this section:

https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/master/deploy/docs/Troubleshoot_Collection.md#2-disable-the-kubeletservicemonitorhttps-flag-in-the-prometheus-operator

The fix is to install the prometheus-operator we say "helm install stable/prometheus-operator" but that only applies if you are running prometheus-operator separately. We should add this command to just upgrade our release: helm upgrade collection sumologic/sumologic --namespace sumologic --reuse-values --set prometheus-operator.kubelet.serviceMonitor.https=false

**Comment by vsinghal13** [comment]
Closing as this is resolved. Doc is updated.

https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/master/deploy/docs/Troubleshoot_Collection.md#2-disable-the-kubeletservicemonitorhttps-flag-in-the-prometheus-operator
