### ISSUE TITLE
4.3.1 Failed to register k8sprocessor's views: otelsvc/k8s/pod_table_size

### ISSUE THREAD

**Issue by txjjjjj** [SumoLogic/sumologic-kubernetes-collection#3473]
chart v4.3.1
eks 1.28

When I upgraded to 4.3.1(4.2.0 has no this warn), I found that the all pod has this warn, does it have any effect?
```
Failed to register k8sprocessor's views: otelsvc/k8s/pod_table_size: cannot register view "otelsvc/k8s/pod_table_size"; a different view with the same name is already registered
```

**Comment by swiatekm-sumo** [comment]
This was fixed in https://github.com/SumoLogic/sumologic-otel-collector/pull/1415, and will be fixed in Helm Chart version 4.4.0. @rnishtala-sumo
