### ISSUE TITLE
Unable to apply sumologic helm chart v2.19 to v4.3 after upgrading kubernetes v1.25

### ISSUE THREAD

**Issue by mohannayak0147** [SumoLogic/sumologic-kubernetes-collection#3554]
while deploying sumologic helm chart v4.3 using terraform resource "helm_release" getting an error as: 
│ Error: error running dry run for a diff: unable to recognize "": no matches for kind "OpenTelemetryCollector" in version "opentelemetry.io/v1alpha1"

**Comment by astencel-sumo** [comment]
Upgrading from `v2` straight to `v4` is not supported. You need to first follow the [documentation](https://help.sumologic.com/docs/send-data/kubernetes/v3/important-changes/) to upgrade from `v2` to `v3`. After that, follow the [documentation](https://help.sumologic.com/docs/send-data/kubernetes/v4/important-changes/) to upgrade from `v3` to `v4`.
