### ISSUE TITLE
Add Go test for the global options (nodeSelector, affinity, tolerations)

### ISSUE THREAD

**Issue by sumo-drosiek** [SumoLogic/sumologic-kubernetes-collection#3566]
Can we add a Go test for the global nodeSelector? I'd like to have some way to verify that everything we generate follows the setting.

_Originally posted by @swiatekm-sumo in https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/3565#issuecomment-1959470326_

**Comment by swiatekm-sumo** [comment]
Resolved by #3427, #3459 and #3462.
