### ISSUE TITLE
Is opentelemetry-operator installation required?

### ISSUE THREAD

**Issue by bkonicek-calm** [SumoLogic/sumologic-kubernetes-collection#3590]
We upgraded from v3 to v4 yesterday and noticed that another operator running in our clusters could no longer create pods. As soon as we rolled back to v3 it started working again. I'm assuming this is related to the otel operator now being installed and probably requires allowing some new firewall rules (running on GKE). Since we only collect logs with Sumologic is there any problem disabling the operator in our `values.yaml`? Will that cause problems with the `logs-otel` and `events-otel` collections?

**Comment by swiatekm-sumo** [comment]
It's required for metrics and tracing instrumentation, you should be fine disabling it if you don't need either of those.

Which operator did you start having issues with, if I may ask? I'd like to report that issue upstream if can be reliably reproduced.

**Comment by bkonicek-calm** [comment]
Thanks @swiatekm-sumo. The particular operator we had issues with was [Airbyte](https://docs.airbyte.com/deploying-airbyte/on-kubernetes-via-helm#add-helm-repository) - when a data sync is triggered, the worker service tries to create a Pod in the cluster, but after upgrading to v4 it never started and eventually the sync failed and logged a timeout. I wasn't able to actually find anything in the otel operator logs to confirm this, it's just my best guess.

Some more details on the firewall configuration for webhooks here: https://github.com/open-telemetry/opentelemetry-operator/issues/1009

Our `values.yaml` is pretty generic. We just have 

```
sumologic:
  clusterName: *******
  accessId: ******
  accessKey: ******
  traces:
    enabled: false
  metrics:
    enabled: false
  setupEnabled: true
```

**Comment by bkonicek-calm** [comment]
I can confirm that setting `opentelemetry-operator.enabled: false` solved this issue
