### ISSUE TITLE
Add instructions for vagrant for M2 Mac

### ISSUE THREAD

**Issue by sumo-drosiek** [SumoLogic/sumologic-kubernetes-collection#3650]
1. Install provider: https://github.com/ppggff/vagrant-qemu
1. Enable SMB sharing

**Comment by swiatekm-sumo** [comment]
Don't these instructions work: https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/CONTRIBUTING.md#arm-hosts-apple-m1-and-so-on?

**Comment by sumo-drosiek** [comment]
Oh, thats great, I will link it in https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/vagrant/README.md then

**Comment by amdprophet** [comment]
I've updated the instructions in both `vagrant/README.md` and `CHANGELOG.md` to include enabling SMB sharing and setting the default Vagrant provider to QEMU. PR: https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/3691.
