### ISSUE TITLE
installing with helm: --namespace not used in helm 3

### ISSUE THREAD

**Issue by nickpalenchar** [SumoLogic/sumologic-kubernetes-collection#368]
In helm 3, `--namespace` is not supported and errors. It looks like helm picks up [kubernetes namespace instead](https://github.com/helm/helm/issues/5628). Install instructions might need to be updated.

**Comment by frankreno** [comment]
We are working on adding support for Helm3.  I just tested this morning using Helm 3.0.2.  The namespace flag is still supported, however, helm will no longer create the namespaces for you.  Before you install the chart, create the sumologic namespace and let me know how that works.

**Comment by davidham** [comment]
What are the other issues around Helm 3 support?

**Comment by frankreno** [comment]
@davidham have a look at this pending PR with some steps on Helm3. https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/369/files
