### ISSUE TITLE
Add option to allow selected histograms

### ISSUE THREAD

**Issue by sumo-drosiek** [SumoLogic/sumologic-kubernetes-collection#3819]
With the https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/3818 we are filtering all histogram and summary metrics, however we should conditionally allow to send metrics with specific names, so customers can control it

The new option should take into consideration the following:

- metrics may be just metric name or `_bucket` ended metric

The proposition is here: https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/3818#discussion_r1701387701

It should be straightforward to implement integration test for it, as it need only update test cofiguration and add metric to the constants

**Comment by rnishtala-sumo** [comment]
Attempt at implementing this for the next release - https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/3821/files#r1706097735

**Comment by rnishtala-sumo** [comment]
Addressed in the above PR
