### ISSUE TITLE
Log lines over 16KB are truncated

### ISSUE THREAD

**Issue by arjunnayak** [SumoLogic/sumologic-kubernetes-collection#398]
We have found that when a pod produces a single JSON log line over 16kb, the resulting log gets truncated in SumoLogic. We don't see the log being split up into multiple messages in Sumo, instead the first part of the log gets lost and we only see the second "half" of the log.

We've done a bit of research on the issue and found that Docker chunks messages larger than 16KB, so it's essentially up to the log processor/aggregator to recombine the chunked messages. Relevant issues we found on the subject: 
https://github.com/kubernetes/kubernetes/issues/52444
https://github.com/moby/moby/issues/34855

One of the recommendations was to use the fluentd concat plugin https://github.com/fluent-plugins-nursery/fluent-plugin-concat . In the readme, there's an example for "Handle Docker logs splitted in several parts (using partial_message), and do not add new line between parts."
```
<filter>
  @type concat
  key message
  partial_key partial_message
  partial_value true
  separator ""
</filter>
```

We are considering testing this out to vet the solution, but we figured we would open an issue since this might come up for other users of the chart.

**Comment by arjunnayak** [comment]
Just found out about Docker_Mode in fluent-bit. We just tested this and on the surface it looks good https://docs.fluentbit.io/manual/v/1.3/input/tail#docker_mode

Maybe it's worth pointing this out somewhere in documentation?

**Comment by vsinghal13** [comment]
> Just found out about [`Docker_Mode`](https://docs.fluentbit.io/manual/v/1.3/input/tail#docker_mode) in fluent-bit. Maybe it's worth pointing this out somewhere in documentation, or even a flag for the helm chart to enable `Docker_Mode`?
> 
> We just tested this on 0.11.0 and it seems to work well, although it breaks on 0.13.0 since multiline mode was enabled, and these 2 modes cannot be used together.

@arjunnayak Correct, as of now the `Docker_Mode` and the `Multiline` cannot be used together. One of the customers also experienced this issue and turned off the `Multiline` feature as they were confident that they won't have multiline logs. Even if you do have multiline logs, they will be spilt into multiple messages which is still better than loosing data .

**Comment by arjunnayak** [comment]
Sounds good, that's likely what we'll do as well. If there are no future plans to try to solve both problems (truncation & multiline support), then feel free to close the issue. It would be great to have both out of the box!

**Comment by vsinghal13** [comment]
@arjunnayak Documentation for the same has been added. Closing the issue .
https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/master/deploy/docs/Best_Practices.md#log-lines-over-16kb-are-truncated
