### ISSUE TITLE
Setting source category for events source does not get applied with Helm install

### ISSUE THREAD

**Issue by darrenk13** [SumoLogic/sumologic-kubernetes-collection#400]
I am installing the sumo collector via helm and trying to set a custom source category for the events source.  I have downloaded the values.yaml from https://raw.githubusercontent.com/SumoLogic/sumologic-kubernetes-collection/master/deploy/helm/sumologic/values.yaml and updated the section for sumologic.events.sourceCategory.  I first tried setting it to `%{sourceCategoryPrefix}/%{clusterName}/events` and then to a fixed string and in both cases the source category on the logs is set to `Http Input`.  The logs are also tagged with a source name of `Http Input` even though the source tag is set to `events`.

**Comment by maimaisie** [comment]
Hi @darrenk13, which helm chart version are you using? If you are using the latest release version, the `sumologic.events.sourceCategory` field has not been released yet. For the latest release version, please take a look at https://raw.githubusercontent.com/SumoLogic/sumologic-kubernetes-collection/v0.13.0/deploy/helm/sumologic/values.yaml for the available fields

The master branch values.yaml will be released in the next version. We are hoping to publish a new release soon. Thanks.

**Comment by darrenk13** [comment]
I am not specifying any chart version, below is the command I am using to install the chart:
```
helm install sumologic/sumologic --name collection --namespace sumologic -f values.yaml --set sumologic.accessId=${SUMO_ACCESS_ID} --set sumologic.accessKey=${SUMO_ACCESS_KEY} 
```
Here is the command I used to get the values.yaml which points to master
```
curl -LJO https://raw.githubusercontent.com/SumoLogic/sumologic-kubernetes-collection/master/deploy/helm/sumologic/values.yaml
```

Looks like the docs were just updated last week to pin to a specific version of values.yaml in #389 (the page I was using was https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/master/deploy/docs/existingPrometheusDoc.md )

Looking forward to the release of this feature to remove that manual step.
