### ISSUE TITLE
fluent bit config doesn't allow to easily provide a hostname field

### ISSUE THREAD

**Issue by djsly** [SumoLogic/sumologic-kubernetes-collection#407]
When getting logs from fluent-bit 

we can get 
container or system logs 
the container log will have a field `node` and `hostname`
while the systemd logs will have a field `_HOSTNAME`

we started augmenting the fluent bit input and there is no easy way to have the source (hostname) of the new scrapped logs from the nodes with a proper `hostname` field

It would be great if fluent-bit+fluentd could provide a generic solution to have a common fields to query logs based on node/hostname

**Comment by djsly** [comment]
@frankreno  FYI

**Comment by frankreno** [comment]
@djsly - This will be fixed in 1.1 by #725 .  We now ensure the `_HOSTNAME` field is used for systemd log. Marking as closed now.
