### ISSUE TITLE
sumologic-collector-setup job fails with collector not found error.

### ISSUE THREAD

**Issue by spat1492** [SumoLogic/sumologic-kubernetes-collection#414]
```
curl -s https://raw.githubusercontent.com/SumoLogic/sumologic-kubernetes-collection/v0.13.0/deploy/kubernetes/setup-sumologic.yaml.tmpl | \
sed 's/\$NAMESPACE'"/sumologic/g" |
sed 's/\$SUMOLOGIC_ACCESSID'"/<SUMOLOGIC_ACCESSID>/g" | 
sed 's/\$SUMOLOGIC_ACCESSKEY'"/<SUMOLOGIC_ACCESSKEY>/g" | 
sed 's/\$COLLECTOR_NAME'"/collector/g" | 
sed 's/\$CLUSTER_NAME'"/<my-aks-cluster-name>/g" | 
tee setup-sumologic.yaml | 
kubectl -n sumologic apply -f -
```

I ran the above command with the appropriate values as shown above.
The job starts but quickly fails with the following error. 

```
[0m[1m[32mTerraform has been successfully initialized![0m[32m[0m
[0m[32m
You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.[0m
[0m[1msumologic_collector.collector: Importing from ID "collector"...[0m
[0m[1m[32msumologic_collector.collector: Import prepared![0m
[0m[32m  Prepared sumologic_collector for import[0m
[0m[1msumologic_collector.collector: Refreshing state... [id=collector][0m
[31m
[1m[31mError: [0m[0m[1mcollector with name 'collector' does not exist[0m

[0m[0m[0m
[0m[1msumologic_http_source.default_metrics_source: Importing from ID "collector/(default-metrics)"...[0m
[31m
[1m[31mError: [0m[0m[1mcollector with name 'collector' does not exist[0m

[0m[0m[0m
[0m[1msumologic_http_source.apiserver_metrics_source: Importing from ID "collector/apiserver-metrics"...[0m
```

Based on this part of the documentation:
> It will create Kubernetes resources in your environment and run a container that uses the Sumo Logic Terraform provider to create a Hosted Collector and multiple HTTP Sources in Sumo.

It is my understanding that this job is to supposed to create a controller with the name we have passed in as a parameter? 
If this assumption is incorrect -- what is the recommended process for creating this controller? 

I am currently trying the non-helm installation. But when using helm the job fails with the same error. 

This lead me to believe the issue might might have been with the sumologic endpoint, https://api.sumologic.com/api, I have provided but upon curling to the end point does not return errors. [actually it does not return anything]

Might anyone be able to provide any hints as to what might be going wrong?

**Comment by rvmiller89** [comment]
@spat1492 is there any more to the logs generated by the setup container? The errors you see are expected as it first tries to import the collector and sources if they already exist. Otherwise it will proceed to create them. So after the import steps there should be more logs that may indicate what went wrong.

**Comment by spat1492** [comment]
[1m[31mError: [0m[0m[1m<!DOCTYPE html>





<html lang="en"> 
<html>



<head>
  <meta charset="utf-8"/>
  <meta HTTP-EQUIV="REFRESH" content="10; url=/ui">
  <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>

  <meta http-equiv="cache-control" content="no-cache" />
  <meta http-equiv="Pragma" content="no-cache" />
  <meta http-equiv="Expires" content="-1" />

  <title>Sumo Logic</title>

  
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>

<style type="text/css">
  @font-face {
    font-family: "LabGrotesque-Light";
    src: url("./ui/font/LabGrotesque-Light.woff") format("woff");
  }

  @font-face {
    font-family: "LabGrotesque-Bold";
    src: url("./ui/font/LabGrotesque-Bold.woff") format("woff");
  }

  @font-face {
    font-family: "LabGrotesque-Regular";
    src: url("./ui/font/LabGrotesque-Regular.woff") format("woff");
  }

*********

    <div class="content-header">Page not found</div>
    <div class="content-body">
      We couldn't find the page you were looking for. It might not exist anymore, or there might be an error in the URL.
    </div>
  </div>
  <div id="copyright">
    <span>Copyright 2010-<script>document.write(new Date().getFullYear())</script> Sumo Logic, Inc. |&nbsp;</span>
    <span><a class="link" target="_blank" href="https://www.sumologic.com/privacy/">Privacy Policy</a> |&nbsp;</span>
    <span><a class="link" target="_blank" href="https://www.sumologic.com/terms-conditions/">Terms &amp; Conditions</a></span>
  </div>
</div>

</body>
</html>
[0m

[0m  on sumo-k8s.tf line 29, in resource "sumologic_collector" "collector":
  29: resource "sumologic_collector" "collector" [4m{[0m
[0m
[0m[0m

**Comment by rvmiller89** [comment]
Interesting, I think the API endpoint is suspicious here. With the latest version (v0.13) you can actually omit the endpoint and it will resolve it based on your Access ID and Key. I would first try again without specifying any `SUMOLOGIC_BASE_URL`.

It may be the lack of a trailing slash in the URL, e.g. https://api.sumologic.com/api/v1/
based on https://help.sumologic.com/APIs/General-API-Information/Sumo-Logic-Endpoints-and-Firewall-Security

**Comment by spat1492** [comment]
[0m[0m
[0m[1mkubernetes_namespace.sumologic_collection_namespace: Refreshing state... [id=sumologic][0m
[0m[1msumologic_collector.collector: Creating...[0m[0m
[31m
[1m[31mError: [0m[0m[1m{
  "status" : 401,
  "id" : "UYM38-QUKDA-D4T9Q",
  "code" : "unauthorized",
  "message" : "Credential could not be verified."
}[0m

[0m  on sumo-k8s.tf line 29, in resource "sumologic_collector" "collector":
  29: resource "sumologic_collector" "collector" [4m{[0m
[0m
[0m[0m

**Comment by rvmiller89** [comment]
@spat1492 can you confirm your yaml file sets access id and key, but leaves SUMOLOGIC_BASE_URL blank?
```
        env:
        - name: SUMOLOGIC_ACCESSID
          value: su**************
        - name: SUMOLOGIC_ACCESSKEY
          value: ************************************************
        - name: SUMOLOGIC_BASE_URL
          value: 
```

**Comment by spat1492** [comment]
Yes confirmed

**Comment by spat1492** [comment]
Oh wait it worked! You were correct I shouldn't have specified the endpoint
