### ISSUE TITLE
Filesystem Metrics

### ISSUE THREAD

**Issue by abhi-sumo-zz** [SumoLogic/sumologic-kubernetes-collection#416]
Some customers might need Filesystem metrics. These metrics can either describe disks mounted to nodes or persistent volume claims. It would be great if there were some documented steps around how to get at these metrics.

Apparently Prometheus already collects `kubelet_volume_*` metrics. This might be something that you could add to the remoteWrite config section by adding it to one of the regex filters described here:
https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/master/deploy/helm/sumologic/values.yaml#L422

You would just add `|kubelet_volume_*`

**Comment by frankreno** [comment]
The current collection process can be extended to include any additional metrics as needed.  We currently collect a set of respective defaults that are used by the Sumo Logic Apps for Kubernetes.  Additional metrics can be collected by extending the `prometheus-operator.prometheus.prometheusSpec.remoteWrite` to include any additional metrics you want to collect.

https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/master/deploy/docs/additional_prometheus_configuration.md
