### ISSUE TITLE
fluentd deployment prevents safe cluster-autoscaler scale in due to pos-files volume

### ISSUE THREAD

**Issue by wendtek** [SumoLogic/sumologic-kubernetes-collection#435]
Due to the use of a `hostPath` volume for [`pos-files`](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/master/deploy/helm/sumologic/templates/deployment.yaml#L29) in the fluentd deployment, cluster-autoscaler is unable to evict pods for safe rescheduling on another node without risk of duplicate ingestion.

I suspect it may be better to use a persistent volume claim that can follow the pod to a new node, though there may other considerations I'm missing.

**Comment by pmalek-sumo** [comment]
We're not using [`tail` input plugin](https://docs.fluentd.org/input/tail) so this might actually be unused as of now.
I'll take a closer look at it.
