### ISSUE TITLE
Sumologic helm chart approach

### ISSUE THREAD

**Issue by daroga0002** [SumoLogic/sumologic-kubernetes-collection#470]
Current Sumologic proposed solution is working fine, your implementation helm chart contains Falco, Prometheus, Fluentd and Filebeat. 

But a lot of organisations is using Sumologic for log management (without metrics). This Kubernetes deployment approach is somehow forcing organisations to use tools which they dont need or have other equivalent for them (for example metrics are gathered by Sysdig or Datadog).  Could you rethink this chart and release `log_only` chart or allow such customisation in existing chart which can be implemented without any additional stuff like Prometheus/Falco. 

This is very important to some customers because they dont want duplicate or replace existing processes (for example for metrics gathering by other tool) or they simply don`t require such features like Falco. It will also remove some issues which are currently problematic with your chart (like Falco which is failing or require to modify base AMI).

I know that all those pieces which are in chart are creating your super APP in Sumologic (which is really great) but even if this will be cost to loose it it will be still beneficial to customers to have log_only chart.

Digging into chart I found that falco can be disabled by:
```
helm upgrade --namespace sumologic --set sumologic.accessId=*** --set sumologic.accessKey=***  --set sumologic.clusterName=eks-testenvironment --set falco.enabled=false  collection sumologic/sumologic
```

so looks that it is possible, this is not documented anywhere.

**Comment by vsinghal13** [comment]
cc @samjsong  For `v1.0.0` we should add the `enabled` flag for metrics along with the `enabled` flags for different types of logs and also add the same in the documentation.

**Comment by samjsong** [comment]
Agreed that an `enabled` flag for metrics would be great, but this would still deploy Prometheus and would only prevent metrics from being sent to Sumo. Given that Prometheus consumes non-trivial resources, this might be misleading for users who assume that setting `fluentd.metrics.enabled` to false would also disable Prometheus.

@daroga0002 To disable Prometheus, we currently expose `prometheus-operator.enabled`, similar to `falco.enabled` that can be set to false. I would recommend using this flag if you wish to disable metrics collection altogether. Hope this helps!

**Comment by daroga0002** [comment]
Seems following values are giving me desired state:

| parameter  |  value | function |
| ------------ | ------------ | ------------ |
|  fluent-bit.metrics.enabled |  false | disable service for fluent-bit metrics |
| falco.enabled  |  false | disable falco |
|  prometheus-operator.enabled |  false | disable Prometheus |

I am closing this issue, but my advise is to update docs for this chart as probably I am not only one user interested in such setup.

Thx Guys for support.
