### ISSUE TITLE
source_category_replace_dash is not being applied to systemd logs

### ISSUE THREAD

**Issue by bboerst** [SumoLogic/sumologic-kubernetes-collection#484]
After upgrading from the old stable/sumologic helm chart, we noticed that source_category_replace_dash isn't being honored for systemd logs.

Upon inspection, it looks like source_category_replace_dash is missing from both the kubelet and systemd filters: https://github.com/bboerst/sumologic-kubernetes-collection/blob/7cfcf16379e77d72bcc133880e6de8881cb804e8/deploy/helm/sumologic/conf/logs/logs.source.systemd.conf#L36

I opened https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/483 to fix this.  If approved, this would really help our workflow.

**Comment by perk-sumo** [comment]
I'm closing the issue. Thanks @bboerst for your PR :)
