### ISSUE TITLE
annotation stops working

### ISSUE THREAD

**Issue by renperez** [SumoLogic/sumologic-kubernetes-collection#566]
i'm running fluentd version 0.15.0 along with fluentbit 1.3.2. for some reason sumologic annotation is not working. i'm still seeing the stream and timestamp in my sumo logs. 

 sumologic.com/LogFormat: text
 sumologic.com/addStream: "false"
 sumologic.com/addTimestamp: "false"

**Comment by renperez** [comment]
@vsinghal13 thanks for your help today. can you keep me posted on the above request.

**Comment by frankreno** [comment]
At the moment, we do not plan to add the annotation support for addStream and addTimestamp as that configuration has been moved to fluentd.  it is possible to configure fluentd to transform the data and add these kinds of fields - https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/master/deploy/docs/v1_conf_examples.md
