### ISSUE TITLE
Helm Install "Error: unknown flag: --name" 

### ISSUE THREAD

**Issue by JeremyProffitt** [SumoLogic/sumologic-kubernetes-collection#570]
Helm v3 requires the name as part of the install, so the command on the below URL should be updated for Helm v3, which uses 

helm install collector sumologic/sumologic ...

and not

helm install sumologic/sumologic --name collector

https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/master/deploy/docs/Installation_with_Helm.md#installation-steps

**Comment by JeremyProffitt** [comment]
Helm 3 also does not respect the -namespace flag, you must create the namespace manually:

kubectl create namespace sumologic

and set it as the default name space before running helm

kubectl config set-context <cluster-name> --namespace=sumologic

this is discussed here: https://github.com/helm/helm/issues/5628

**Comment by abhi-sumo** [comment]
I believe this is done correctly for the helm3 docs (which are not yet confirmed as supported): https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/master/deploy/docs/Helm3.md. I believe the doc linked (https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/master/deploy/docs/Installation_with_Helm.md#installation-steps) explicitly is only supported for helm2.
