### ISSUE TITLE
Add error or warning during install, if I'm already running a prometheus operator 

### ISSUE THREAD

**Issue by alexbklein91** [SumoLogic/sumologic-kubernetes-collection#594]
If I'm already a customer running a prometheus operator in my cluster, and I install without turning off the included Sumo Logic prometheus operator, there should be some kind of error or warning message on helm install.

**Comment by bergerx** [comment]
a related comment is here: https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/257#issuecomment-652557190
@alexbklein91 did you successfully deploy with disabling the included one, i'm seeing some metrics missing in my tests.

**Comment by frankreno** [comment]
We have documentation advising of multiple install models when you have an existing Prometheus operator running
