### ISSUE TITLE
Lower the default max retry_timeout for FluentD from 72 hours

### ISSUE THREAD

**Issue by perk-sumo** [SumoLogic/sumologic-kubernetes-collection#620]

**Comment by frankreno** [comment]
As retry parameters are all [configured in the buffer section](https://docs.fluentd.org/configuration/buffer-section#retries-parameters), customizing this is already doable via `fluentd.buffer.extraConf`.  The question is do we need to actually lower it by default and if so what should be the value?

**Comment by sumo-drosiek** [comment]
72h is too long. Hard to expect customer to wait three days after some longer failures in the configuration/network. It's working also against us, because we will be caching all this data

**Comment by frankreno** [comment]
Good point.  What do we think is a sensible default?

**Comment by sumo-drosiek** [comment]
Not sure, I would say lower better, but on the other hand it's going to generate logs. My type is between 1 and 6 hours.
@vsinghal13 @samjsong @perk-sumo any thoughts on that?

**Comment by perk-sumo** [comment]
I'd vote for max 1 hour for that. The cost of 1 hour retry is not big (if any) and we should flush everything as soon as possible.
