### ISSUE TITLE
Allow [warn] fluentd log line of the form `retry succeded. chunk_id=xxxx`

### ISSUE THREAD

**Issue by vsinghal13** [SumoLogic/sumologic-kubernetes-collection#621]
We currently only ingest the error log line and not the warn log lines. 

To verify, if the chunk id was retried, we should have a logline confirming that the retry was succeded.

**Comment by vsinghal13** [comment]
We should also expose a config in `values.yaml` to enable/disable the fluentd filter for quick debugging.

**Comment by frankreno** [comment]
The following changes are a workaround to capture the logs:

Edit the configmap for fluentd, and add locate this section

kubectl edit configmap collection-sumologic

    <label @NORMAL>
      #  only match fluentd logs based on fluentd container name
      <filter **collection-sumologic**>
        # only ingest fluentd logs of levels: {error, fatal} and warning messages if buffer is full
        @type grep
        <regexp>
          key log
          pattern /\[error\]|\[fatal\]|drop_oldest_chunk/
        </regexp>
      </filter>

and change the pattern:

          pattern /\[error\]|\[fatal\]|drop_oldest_chunk/|retry succeeded/

Afterward you may need to delete the collection-sumologic fluentd pods to force the config change.
