### ISSUE TITLE
Collect Node Labels

### ISSUE THREAD

**Issue by frankreno** [SumoLogic/sumologic-kubernetes-collection#631]
Currently, the collection process does not capture node labels for the logs and metrics.  This would be useful for customers who take advantage of node labels and wish to search by them.

**Comment by frankreno** [comment]
https://ideas.sumologic.com/ideas/CIP-I-3832

**Comment by dindurthy** [comment]
Any workarounds we can implement for this? I see that there are some [fundamental issues](https://github.com/kubernetes/kubernetes/issues/40610) that make this hard but I wonder if we can run multiple instances of the daemonsets with custom fields or something?

**Comment by mattyb** [comment]
We're attempting to hack this together somehow using `kustomize`. It's a disappointing gap as we consider moving away from Datadog, which supports this out-of-the-box.
