### ISSUE TITLE
Allow for some customization of Setup Job

### ISSUE THREAD

**Issue by frankreno** [SumoLogic/sumologic-kubernetes-collection#643]
Users should be able to:

- create additional sources
- add additional fields to the collector and set fields on sources
- add additional TF config to sources (for example, processing rules)

**Comment by sumo-drosiek** [comment]
Here is the concept #672

**Comment by sumo-drosiek** [comment]
ToDo:
 * generate logs and events endpoints too
 * http source fields reference: https://github.com/terraform-providers/terraform-provider-sumologic/blob/master/sumologic/sumologic_sources.go#L14-L32
