### ISSUE TITLE
Make it optional to collect kubernetes metrics

### ISSUE THREAD

**Issue by victorcq** [SumoLogic/sumologic-kubernetes-collection#678]
Is it possible to make it optional to collect kubernetes metrics in the HELM chart? Similar to kubernetes events https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/master/deploy/helm/sumologic/values.yaml#L395? 

Background for this: we are using other tool to collect kubernetes metrics, and only use Sumo for log aggregation. Because metrics is not optional, the helm chart will always try to create metric service, statefulset, etc.

**Comment by frankreno** [comment]
yes it is.  simply turn off the Prometheus Operator sub chart. Please refer to this comment:

https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/release-v1.0/deploy/helm/sumologic/values.yaml#L535-L538

**Comment by victorcq** [comment]
Hi Frank, that's what I did, here is my values: 
```
sumologic:
  setupEnabled: false
prometheus-operator:
  enabled: false
fluentd:
  events:
    enabled: false
......
......
```
But turning prometheus-operator off does not stop helm chart creating fluentd-metrics statefulset: https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/release-v1.0/deploy/helm/sumologic/templates/metrics-statefulset.yaml. I'd expect a similar `if` statement in the beginning of fluentd-events: https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/release-v1.0/deploy/helm/sumologic/templates/events-statefulset.yaml
Hope this make sense.

**Comment by frankreno** [comment]
Ahh good find! We will get this fixed.

**Comment by victorcq** [comment]
Thanks for jumping on it quickly :) I guess apart from metrics-statefulset, it would need similar logic in metrics-configmap and metrics-service?

**Comment by perk-sumo** [comment]
I think this could be added for `logs` as well (like we do for traces), eg. for some clients who demo the `traces` only.
