### ISSUE TITLE
Add helm post-delete hook that removes the secret

### ISSUE THREAD

**Issue by perk-sumo** [SumoLogic/sumologic-kubernetes-collection#701]

**Comment by vsinghal13** [comment]
https://github.com/helm/charts/blob/55431b17381cb675543f186129fb7c3557a4943d/stable/velero/templates/cleanup-crds.yaml

Something similar to this can be done?

**Comment by perk-sumo** [comment]
I'm closing as this would create problems for the non-helm users.
It's a good feature to add when we have the operator.
