### ISSUE TITLE
Potential Race Condition in Setup

### ISSUE THREAD

**Issue by DWSR** [SumoLogic/sumologic-kubernetes-collection#720]
While I was going through the TF code used for setup, I noticed a potential race condition: The Kubernetes `Secret` that is created by Terraform does not depend on the `Namespace` that Terraform will also create in the same run. In most cases this is _probably_ fine, given that the default parallelism for Terraform is 10 and the Collectors take longer to create than a `Namespace`, but it should be fixed regardless:

https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/d68ccf787d142cb3f5255728ef8fceef2b3862eb/deploy/helm/sumologic/conf/setup/sumo-k8s.tf#L98 should instead be something like this:

```terraform
namespace = kubernetes_namespace.sumologic_collection_namespace.metadata[0].name
```

**Comment by sumo-drosiek** [comment]
Thank you for the issue 👍
