### ISSUE TITLE
Sumologic reapplies namespace via terraform thus removing any metadata added to the namespace when it was first created

### ISSUE THREAD

**Issue by severity1** [SumoLogic/sumologic-kubernetes-collection#741]
In most cases the namespace is created beforehand and people will add metadata.* to their namespaces for audit purposes or for automation purposes.

I tried to install sumologic-kubenretes-collection on a namespace with labels and after installation it always removes the labels.

Upon inspection I found out that `deploy/helm/sumologic/conf/setup/resources.tf` re-applies the namespace thus effectively purging all metadata that was already on that namespace.

I reckon this part is unnecessary and can be removed since sumologic creation job would have already spawned on that namespace to execute all terraform tasks. Also feels like some sort of circular dependency.

```
resource "kubernetes_namespace" "sumologic_collection_namespace" {
  metadata {
    name = var.namespace_name
  }
}
```

proposal:
```
# instead of recreating the namespace just source the existing namespace.
data "kubernetes_namespace" "sumologic_collection_namespace" {
  metadata {
    name = var.namespace_name
  }
}

resource "kubernetes_secret" "sumologic_collection_secret" {
  metadata {
    name = "sumologic"
    namespace = data.kubernetes_namespace.sumologic_collection_namespace.metadata[0].name
  }

  data = {
    {{- $ctx := .Values }}
    {{- range $type, $sources := .Values.sumologic.sources }}
    {{- if eq (include "terraform.sources.component_enabled" (dict "Context" $ctx "Type" $type)) "true" }}
    {{- range $key, $source := $sources }}
    {{ include "terraform.sources.data" (dict "Endpoint" (include "terraform.sources.config-map-variable" (dict "Type" $type "Context" $ctx "Name" $key)) "Name" (include "terraform.sources.name" (dict "Name" $key "Type" $type))) }}
    {{- end }}
    {{- end }}
    {{- end }}
  }

  type = "Opaque"
}
```

**Comment by severity1** [comment]
Happy to submit a PR if ever

**Comment by frankreno** [comment]
We would welcome a PR @severity1. The proposal seems reasonable to me.

**Comment by severity1** [comment]
@frankreno sweet, I will submit a PR in the following days.

**Comment by severity1** [comment]
@frankreno, what is the best way of testing this? just redeploy sumologic with the proposed changes?

**Comment by severity1** [comment]
oh looks like the conf/setup/* tf files are being passed as configmap.

**Comment by severity1** [comment]
I tried to install using 10.0 with the namespace being referenced as datasource but it emits this errror;

```
Error: Invalid data source

  on sumo-k8s.tf line 88, in data "kubernetes_namespace" "sumologic_collection_namespace":
  88: data "kubernetes_namespace" "sumologic_collection_namespace" {

The provider provider.kubernetes does not support data source
"kubernetes_namespace".
```

this is weird because the kubernetes provider exposes this as datasource according to docs.

thinking about this now, helm@2 automatically creates the namespace specified and helm@3 requires that a namespace be created beforehand as a dependency, I don't think there is any value into even referencing to the namespace as a resource or datasource anywhere in the setup job.

thoughts on this?

**Comment by frankreno** [comment]
@severity1 - That's a fair point.  I am good with removing the creation of the namesace from the setup process entirely for the reasons you outlined.

**Comment by severity1** [comment]
will submit a PR later today.

**Comment by severity1** [comment]
pull request is here: https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/745
