### ISSUE TITLE
Migrate Fluent-bit chart off of helm/stable

### ISSUE THREAD

**Issue by frankreno** [SumoLogic/sumologic-kubernetes-collection#750]
As helm/stable is being deprecated in favor of HelmHub, we will need to migrate from the current fluent-bit helm chart in helm stable to its new location - https://github.com/fluent/helm-charts/tree/master/charts

**Comment by perk-sumo** [comment]
This is a breaking change release, it needs to be moved to `2.0`

**Comment by davidnortonjr-sps** [comment]
I would highly recommend finding an alternative for this before 2.0. Perhaps that means hosting the old versions of the charts on your own servers. But according to multiple sources, the GCS buckets hosting this will be deleted in November -- and any users of your 1.x charts would be up a creek:

- https://helm.sh/blog/helm-v2-deprecation-timeline/#helm (To Be Removed: Google Cloud buckets for the stable and incubator chart repositories)
- https://github.com/helm/charts/issues/23742#issuecomment-702128318

**Comment by perk-sumo** [comment]
#1073 will be backported to `release-v1.3` in #1079

**Comment by perk-sumo** [comment]
Same `release-v1.3` backport for metrics-server: https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1081
