### ISSUE TITLE
Support CRI log format

### ISSUE THREAD

**Issue by djsly** [SumoLogic/sumologic-kubernetes-collection#758]
Containerd does not support JSON format, and AKS is moving away from Moby to use instead Containerd. 

To ensure that the sumologic collection solution still works, we would need that it supports CRI logging format out of the box. 

> Containerd sets up logging using the standardized cri logging format (which is different from what you currently get from docker’s json driver). Your logging solution needs to support the cri logging format (like Azure Monitor for Containers)

As noted: https://docs.microsoft.com/en-us/azure/aks/cluster-configuration#containerd-limitationsdifferences

**Comment by perk-sumo** [comment]
Hi @djsly - thank you for this issue, we'll definitely look on how to support CRI logs!
/cc @frankreno

**Comment by frankreno** [comment]
When implementing - make sure you review https://github.com/fluent/fluent-bit/issues/1316
