### ISSUE TITLE
Fluent-bit default forward host name not found

### ISSUE THREAD

**Issue by mfilocha** [SumoLogic/sumologic-kubernetes-collection#761]
The default fluent-bit forward host name defined by https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/release-v1.0/deploy/helm/sumologic/values.yaml#L433 is _${CHART}.${NAMESPACE}.svc.cluster.local._

My clean deployment creates four services:

```
monitoring-fluentdsumo-sumologic-fluentd-logs               ClusterIP
monitoring-fluentdsumo-sumologic-fluentd-logs-headless      ClusterIP 
monitoring-fluentdsumo-sumologic-fluentd-metrics            ClusterIP
monitoring-fluentdsumo-sumologic-fluentd-metrics-headless   ClusterIP
```
where _monitoring-fluentdsumo_ is the name of my helm chart and _monitoring_ is the namespace name of the deployment.

None of them fits to the default. As a workaround, I use _monitoring-fluentdsumo-sumologic-fluentd-logs.monitoring.svc.cluster.local._ 

Is this default host name supposed to work out-of-the-box?

I'm using version 1.0.0 of the helm chart.

**Comment by frankreno** [comment]
@mfilocha - Yes the default configuration should work out of the box. 

These come from environment variables that are injected into a configMap and then into the fluent-bit pods.  The syntax is just the environment variable syntax that fluent-bit supports.

https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/release-v1.0/deploy/helm/sumologic/values.yaml#L418-L427

CHART is set to the a value stored in the sumologic-configmap.  

https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/release-v1.0/deploy/helm/sumologic/templates/chart-configmap.yaml#L6

And NAMESPACE is read from the downward API.

This is how we handle the fluent-bit forwarding dynamically, based on the helm release name and the namespace is it installed in. 

Did you have issues that caused you to hardcode it?

**Comment by mfilocha** [comment]
@frankreno Thanks for your reply! 

Indeed, I had hardcoded host name - left from the older version of the helm chart. I've removed it and all is working as expected now!
