### ISSUE TITLE
Link broken for falco ref in values.yaml

### ISSUE THREAD

**Issue by alexbklein91** [SumoLogic/sumologic-kubernetes-collection#766]
In the values.yaml there is a broken link to a falco chart:

https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/release-v1.1/deploy/helm/sumologic/values.yaml#L1181

This is the link:

https://github.com/helm/charts/blob/master/stable/falco/values.yaml

**Comment by frankreno** [comment]
This is because Falco has been removed from helm/stable and moved to its new location. In the 1.1 release, we will be switching over.  https://github.com/falcosecurity/charts/tree/master/falco
