### ISSUE TITLE
Support for Security Context for containers in sumologic-kubernetes-collection 

### ISSUE THREAD

**Issue by blame19** [SumoLogic/sumologic-kubernetes-collection#786]
As part of Kubernetes' best practices, I'd like to set Security Context values in all the containers deployed on my infrastructure. As of now, the charts in weave-scope lack this capability.

ATM, the only value that get instantiated is the fsGroup:
```
securityContext:
        fsGroup: {{ .Values.fluentd.securityContext.fsGroup }}
```
If we had something like
```
securityContext:
        {{ toYaml .Values.resources | indent 4 }}
```
we could add a full scope of securityContext options to the containers.

**Comment by frankreno** [comment]
@blame19 - makes sense.  If you have time to submit a PR, we would welcome it.  Otherwise, we will tackle this in the comings weeks as part of work we are planning for the 1.3 Release

**Comment by blame19** [comment]
@frankreno Thanks, I will take care of this in the following days.
