### ISSUE TITLE
Unable to Override values of sumologic accesskey and accessid using custom values.yaml file

### ISSUE THREAD

**Issue by jeff-auth0** [SumoLogic/sumologic-kubernetes-collection#787]
Hi there,

I am trying to release using helm 3 and `helmfile sync` . I am providing my own values.yaml file to override the values in chart yaml file but somehow it is not setting up the accessKey and accessId. 

I am using HELM 3

I get the following error:

```
in ./helmfile.yaml: failed processing release sumologic: helm exited with status 1:
  Error: execution error at (sumologic/charts/sumologic/templates/setup/setup-job.yaml:37:20): A valid .Values.sumologic.accessId entry required!
```

I am seeing that these keys have been commented out I am wondering if that is causing the issue. https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/master/deploy/helm/sumologic/values.yaml#L20

I am providing above values like this

`name: sumologic
    namespace: sumologic
    chart: ./sumologic
    values:
      - sumologic:
          accessId: {{ requiredEnv "SUMOLOGIC_ACCESSID" }}
          accessKey: {{ requiredEnv "SUMOLOGIC_ACCESSKEY" }}`

Thank you for help.

**Comment by jeff-auth0** [comment]
Here are more details 

`$ export $SUMOLOGIC_ACCESSID="suE2cT3FFBtsfS"
$ export $SUMOLOGIC_ACCESSKEY="somerandomg"
$ vi helmfile.yaml 
$ helmfile lint
Building dependency release=sumologic, chart=.
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "falcosecurity" chart repository
...Successfully got an update from the "sumologic" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading sumologic from repo https://sumologic.github.io/sumologic-kubernetes-collection
Deleting outdated charts

Linting release=sumologic, chart=.
==> Linting .
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: template: sumologic/templates/serviceaccount.yaml:1:14: executing "sumologic/templates/serviceaccount.yaml" at <.Values.serviceAccount.create>: nil pointer evaluating interface {}.create


in ./helmfile.yaml: helm exited with status 1:
  engine.go:159: [INFO] Missing required value: A valid .Values.sumologic.accessId entry required!
  engine.go:159: [INFO] Missing required value: A valid .Values.sumologic.accessKey entry required!
  Error: 1 chart(s) linted, 1 chart(s) failed 
`

**Comment by frankreno** [comment]
@jeff-auth0: hrmm we have had customers install with `helmfile` w/o this issue. How are you injecting the environment variables? I do not see that in the above output? Can you share your entire helmfile.yaml? The error indicates your environment variables are not being passed to `sumologic.accessId` correctly.

**Comment by jeff-auth0** [comment]
> @jeff-auth0: hrmm we have had customers install with `helmfile` w/o this issue. How are you injecting the environment variables? I do not see that in the above output? Can you share your entire helmfile.yaml? The error indicates your environment variables are not being passed to `sumologic.accessId` correctly.

Thank you @frankreno for reply. Here is the helmfile.

```
releases:
  - name: sumologic
    namespace: sumologic
    chart: ./
    values:
      sumologic:
        # If enabled, a pre-install hook will create Collector and Sources in Sumo Logic
        setupEnabled: false
        collectorName: "my-collector"
        accessId: "someid"
        accessKey: "somekey"
```

**Comment by jeff-auth0** [comment]
I figured it out. All good.

**Comment by perk-sumo** [comment]
Hi @jeff-auth0!
Was there anything specific you needed to do to make `helmfile` working?

**Comment by jeff-auth0** [comment]
Hi @perk-sumo 
My chart was living under directory sumologic and in helmfile I was overriding the values like this:
` values:
       sumologic:
              accessId: 'something' 
`

What I had to do to make it work is 

` values:
       sumologic:
            sumologic:
              accessId: 'something' 
`
