### ISSUE TITLE
Helm chart support for setting custom annotations on statefulsets and daemonsets

### ISSUE THREAD

**Issue by zmotu** [SumoLogic/sumologic-kubernetes-collection#797]
Currently custom labels can be provided but not custom annotations.

**Comment by perk-sumo** [comment]
Yeah, it's a reasonable thing to add - thank you for filing this issue!

It seems like it's a `good first issue` so in case you'd like to contribute a PR please feel free to do so :)

**Comment by pmalek-sumo** [comment]
This got merged as of https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/822.

Please comment if that's what you've meant

**Comment by zmotu** [comment]
LGTM, thanks for the quick turn around, will definitely be making use of this.
