### ISSUE TITLE
Capture container cpu throttling

### ISSUE THREAD

**Issue by frankreno** [SumoLogic/sumologic-kubernetes-collection#801]

**Comment by vsinghal13** [comment]
@frankreno found these two cadvisor metrics. Are you referrign to these?
`container_cpu_cfs_throttled_periods_total`
`container_cpu_cfs_throttled_seconds_total `
Ref: https://github.com/google/cadvisor/blob/90f391fddf71801f76f408d8ed191ddc006df323/docs/storage/prometheus.md

**Comment by frankreno** [comment]
`container_cpu_cfs_throttled_seconds_total` should be all we need for the moment.  Thanks @vsinghal13 !
