### ISSUE TITLE
Ignore Older not working correctly due to lack of timestamp parsing specified

### ISSUE THREAD

**Issue by frankreno** [SumoLogic/sumologic-kubernetes-collection#803]
Discussed in https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/664#issuecomment-662809474

**Comment by Adhira-Deogade** [comment]
I am using the Collector source config which installs the collector through terraform script. This feature would be really useful.

**Comment by frankreno** [comment]
Leaving open.  Docs are updated with workaround, but let's leave open until we hear back - https://github.com/fluent/fluent-bit/issues/2466

**Comment by frankreno** [comment]
As the upstream issue has still seen no traction, moving to 2.1 milestone.

**Comment by perk-sumo** [comment]
There is no traction in the upstream bug and we have information in the documentation that explains the situation. I'm closing this one.
