### ISSUE TITLE
Add script for simple dev Vagrant collection setup targeted to local receiver-mock

### ISSUE THREAD

**Issue by perk-sumo** [SumoLogic/sumologic-kubernetes-collection#807]
The script should install the collection on the local microk8s cluster inside the Vagrant development environment and send data to local receiver-mock instance.

Depends on https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/806

**Comment by sumo-drosiek** [comment]
We should update contribution doc as well as part of this issue
