### ISSUE TITLE
Support Installation Tokens for setup-sumologic script

### ISSUE THREAD

**Issue by dmattatall-teradici** [SumoLogic/sumologic-kubernetes-collection#810]
Sumologic have recently enabled Installation Tokens for creation and configuration of hosted collectors

Can we have this enabled for setup-sumologic script?

**Comment by frankreno** [comment]
@dmattatall-teradici - at the moment, installation tokens are supported by installed collectors only, not hosted collectors.

**Comment by vsinghal13** [comment]
Closing this since this is not supported as per the above comment.
