### ISSUE TITLE
Support custom annotations for prometheus operator

### ISSUE THREAD

**Issue by pmalek-sumo** [SumoLogic/sumologic-kubernetes-collection#825]
As noticed by @sumo-drosiek in https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/822#discussion_r467778979 it would be nice to support custom annotations for prometheus operator https://github.com/helm/charts/tree/master/stable/prometheus-operator#exporters

As of now this is unfortunately impossible since it only exposes `prometheus-node-exporter.podLabels`

**Comment by frankreno** [comment]
I believe this is possible:

`podMetadata` lets you add labels and annotations to the Prometheus pods according to the `PrometheusSpec` in the Prometheus operator API:

https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#prometheusspec

It is also exposed in the prometheus-operator helm chart.

https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/prometheus/prometheus.yaml#L166

**Comment by pmalek-sumo** [comment]
So, if I understand the suggestion correctly we shall add `podMetadata` key in https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/08ceace47fa85635725e27faf00cea729eecbd6e/deploy/helm/sumologic/values.yaml#L906-L933 ?

I guess we should move both `podLabels` and `podAnnotations` from
https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/08ceace47fa85635725e27faf00cea729eecbd6e/deploy/helm/sumologic/values.yaml#L809-L813
there as well, right?

That would seem a bit different than what we're doing for other services (probably causing confusion?).

**Comment by frankreno** [comment]
Agree it would be confusing, as discussed on standup lets see if we can get a PR together to improve this.

**Comment by pmalek-sumo** [comment]
This have been added in https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/822/files#diff-1afd7b203a6373f36b3fdb4d68d7ddb5R809-R813

I'm not 100% sure but I'd say this is already done unless I'm missing something.
