### ISSUE TITLE
[doc][non-helm] Add instruction how to generate `overrides` files

### ISSUE THREAD

**Issue by sumo-drosiek** [SumoLogic/sumologic-kubernetes-collection#827]
Documentation is updated regarding usage of `kubernetes-tools` templating model, but we still recommend usage of the `*-overrides` files. We need to update documentation to get rid of any of a static generated file. I believe we can add some parameter to kubernetes-tools to not force anyone to install additional software (`yq` or similar).

**Comment by frankreno** [comment]
Ref: https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/master/deploy/docs/existingPrometheusDoc.md#update-existing-prometheus-operator-helm-chart

**Comment by sumo-drosiek** [comment]
Solved by #1052
