### ISSUE TITLE
CVE Rake OS Command Injection in rake program in Ruby

### ISSUE THREAD

**Issue by dmattatall-teradici** [SumoLogic/sumologic-kubernetes-collection#829]
sumologic-kubernetes-collection has one critical vulnerability in ruby.
https://www.cybersecurity-help.cz/vdb/SB2020030203

scanning docker.io/sumologic/kubernetes-fluentd:1.1.0 for criticals 

VULNDB-212604           rake-12.3.2                                 Critical          12.3.3                    

Could you update this dependency to 12.3.3 for the new sumologic-kubernetes-collection release?

**Comment by sumo-drosiek** [comment]
Thank you for reporting it. Current version of the `fluent/fluentd:v1.11.1-debian-1.0` already contains the patched rake, so we need to rebuild images.

cc: @perk-sumo

**Comment by frankreno** [comment]
This should be fixed by #817 and will go our with our 1.2 release.

**Comment by dmattatall-teradici** [comment]
Thanks all!

**Comment by pmalek-sumo** [comment]
1.2 and 1.3 have already been released and contain the above changes
