### ISSUE TITLE
Thanos sidecar has no limits set

### ISSUE THREAD

**Issue by perk-sumo** [SumoLogic/sumologic-kubernetes-collection#862]
On of containers is not limited by default - and it should be as sumo warns about not-limited containers.

Container name: thanos-sidecar
StatefulSet name: prometheus-collection-prometheus-oper-prometheus
Helm chart version affected: all

**Comment by perk-sumo** [comment]
There are no limits for `thanos` in the prometheus-operator values: https://github.com/helm/charts/blob/master/stable/prometheus-operator/values.yaml#L1961

**Comment by vsinghal13** [comment]
User can set it as follows:
https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#thanosspec

**Comment by perk** [comment]
Yeah, the thing is:
1) sumo k8s app warns about not-limited containers
2) thanos sidecar is not limited by default in the upstream chart like others

So you install the collection and instantly get the warning about collection, that's not a good experience.
