### ISSUE TITLE
Fix tests for fluent-plugin-enhance-k8s-metadata

### ISSUE THREAD

**Issue by perk-sumo** [SumoLogic/sumologic-kubernetes-collection#871]
When `kubeclient` version `4.9.1` is used we get the following error:

```
Error: test: get_pod_metadata load labels from API(CacheStrategyTest):
  WebMock::NetConnectNotAllowedError: Real HTTP connections are disabled. Unregistered request: GET http://localhost:8080/apis/api/extensions/v1beta1/namespaces/sumologic/replicasets/curl-byi-5bf5d48c57 with headers {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'Host'=>'localhost:8080', 'User-Agent'=>'rest-client/2.1.0 (linux-gnu x86_64) ruby/2.5.1p57'}
```

**Comment by pmalek-sumo** [comment]
Example of broken build: https://travis-ci.org/github/SumoLogic/sumologic-kubernetes-collection/builds/722575758

**Comment by perk-sumo** [comment]
The kubeclient `4.9.0` has been set by: https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/870

**Comment by pmalek-sumo** [comment]
https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/870 has been merged already.
Is there anything else needed? @perk-sumo

**Comment by perk-sumo** [comment]
Yeah, actually it would be great to check why tests fail with `4.9.1` and what can we do about it :)

**Comment by pmalek-sumo** [comment]
Apparently this has been broken specifically by https://github.com/abonas/kubeclient/commit/2542ff80ad0e2ddee58d6bd93497261d57bf64be in this PR https://github.com/abonas/kubeclient/pull/457

I've posted a comment to ask if we're using this library 100% correctly https://github.com/abonas/kubeclient/issues/318#issuecomment-693567436 or maybe our use case falls under 

> `Client.new('https://host:6443/apis', 'batch/v1')` — partially works?! undocumented, not fully intended.

mentioned in https://github.com/abonas/kubeclient/issues/318#issuecomment-404546444
