### ISSUE TITLE
Prometheus container has no limits set by default

### ISSUE THREAD

**Issue by perk-sumo** [SumoLogic/sumologic-kubernetes-collection#885]

**Comment by perk-sumo** [comment]
@frankreno we need to figure out how much memory/CPU we want to give here. I'd say for the small cluster, WDYT?

**Comment by frankreno** [comment]
I think @pmaciolek was doing some benchmarking on this? or maybe @vsinghal13 ? we need to benchmark what it uses. I would say the size of the cluster should have little impact on the setup.  Its doing the same setup no matter what cluster.

**Comment by frankreno** [comment]
just make sure we set for max usage, not average.

**Comment by perk-sumo** [comment]
But max usage would be 128GB or sth.

**Comment by frankreno** [comment]
Hah, I misread this, this is for Prometheus (not setup). I would say based on a small cluster and documented that it may need adjustments.

**Comment by perk-sumo** [comment]
It should be based on our findings from: https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/900

**Comment by sumo-drosiek** [comment]
#959

**Comment by perk-sumo** [comment]
The fix has been reverted and will be reintroduced in `2.0`

**Comment by perk-sumo** [comment]
This made into 1.3 eventually: https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/978
