### ISSUE TITLE
Log Details

### ISSUE THREAD

**Issue by arunpatyal** [SumoLogic/sumologic-kubernetes-collection#89]
It will be really helpful to mention in the readme as what logs are we capturing like container logs, controller manager, kubelet etc.

**Comment by vsinghal13** [comment]
Please refer to the below doc: 
https://help.sumologic.com/Solutions/Kubernetes_Solution/02Set_up_collection_for_Kubernetes

**Comment by vsinghal13** [comment]
closing this as we have separate sections for each type of log that we collect in the `v1.0.0` `values.yaml` file.
