### ISSUE TITLE
Metadata Enrichment Plugins can result in SNAT port exhaustion on Azure AKS

### ISSUE THREAD

**Issue by frankreno** [SumoLogic/sumologic-kubernetes-collection#891]
The metadata service query logic is causing SNAT port exhaustion on the LoadBalancer for each backend pool member where the fluent services are running.

**Comment by astencel-sumo** [comment]
This is now fixed in the following versions of collection:
* [v2.0.2](https://github.com/SumoLogic/sumologic-kubernetes-collection/releases/tag/v2.0.2) (#1434)
* [v1.3.6](https://github.com/SumoLogic/sumologic-kubernetes-collection/releases/tag/v1.3.6) (#1390)
