### ISSUE TITLE
Pod annotation/labels not being pulled into sumologic logs

### ISSUE THREAD

**Issue by jeff-auth0** [SumoLogic/sumologic-kubernetes-collection#906]
Hi there, 

Our pod deployment adds extra labels like this: 

`labels:
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        app.kubernetes.io/name: {{ template "app.name" . }}
        customlabel: 1234
`

These labels do not appear in sumologic logs especially the customlabel since we moved to the sumologic k8s app. Is there a flag or something I need to enable to get these labels in sumologic. ?

Thanks in advance.

**Comment by frankreno** [comment]
@jeff-auth0 - the new collection process sends the metadata as HTTP headers, which get translated to Sumo Logic log metadata fields.  You can view the dropped fields page to see what is being dropped and then allow them to be sent. - https://help.sumologic.com/Manage/Fields#View_dropped_fields

**Comment by jeff-auth0** [comment]
Thank you @frankreno That worked. Cheers
