### ISSUE TITLE
 Setup process does not work with external Proxy

### ISSUE THREAD

**Issue by frankreno** [SumoLogic/sumologic-kubernetes-collection#914]
When your proxy is running in the k8s cluster, say squid proxy, the setup process can work correctly. However, when using an external proxy it cannot.  The issue stems from the Kubernetes provider that creates the secret.

https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/master/deploy/helm/sumologic/conf/setup/setup.sh#L9-L10

We use the above environment variables, which are leveraged by the underlying Go HTTP client that TF providers use.  The problem is when using an external proxy, the request to create the Kubernetes secret gets routed to the proxy and when it is an external proxy, it cannot resolve to the correct URL.

**Comment by sumo-drosiek** [comment]
I believe using `NO_PROXY` should solve this issue: https://github.com/hashicorp/terraform/issues/17386#issuecomment-370276866
Going to perform tests and prepare PR for that
