### ISSUE TITLE
Fix shellcheck issues and enforce it's check

### ISSUE THREAD

**Issue by perk-sumo** [SumoLogic/sumologic-kubernetes-collection#919]
Additionally refactor script so that every variable usage is enclosed in `${}`

**Comment by pmalek-sumo** [comment]
This is already done with https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/2d64283f6fb5c6d10e494c940d8b46069780b215/.github/workflows/pull_requests.yml#L22-L31
