### ISSUE TITLE
Fix chart versions on the Artifact Hub

### ISSUE THREAD

**Issue by perk-sumo** [SumoLogic/sumologic-kubernetes-collection#987]
We have two problems with chart versions on the Artifact Hub:
* there are development charts listed
* we have broken publish dates as we overwrite everything with current time on every build

https://artifacthub.io/packages/helm/sumologic/sumologic

**Comment by kkujawa-sumo** [comment]
Issue is resolved by following pull requests:
https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1122
https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1123
https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1125
https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1130
https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1090
https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1093

cc: @perk-sumo
