### ISSUE TITLE
Prepare the GitHub issue template

### ISSUE THREAD

**Issue by perk-sumo** [SumoLogic/sumologic-kubernetes-collection#989]
Info needed: 
* collection version
* k8s version
* logs if possible

**Comment by kkujawa-sumo** [comment]
Closed by https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1163, https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1164, https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1165
